-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accel_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_28 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    i_3 : IN STD_LOGIC_VECTOR (6 downto 0);
    j_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    tmp_42 : IN STD_LOGIC_VECTOR (6 downto 0);
    weights2 : IN STD_LOGIC_VECTOR (63 downto 0);
    acc_34_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_34_out_ap_vld : OUT STD_LOGIC;
    feat1_p_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_ce0 : OUT STD_LOGIC;
    feat1_p_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_10_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_10_ce0 : OUT STD_LOGIC;
    feat1_p_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_11_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_11_ce0 : OUT STD_LOGIC;
    feat1_p_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_12_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_12_ce0 : OUT STD_LOGIC;
    feat1_p_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_13_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_13_ce0 : OUT STD_LOGIC;
    feat1_p_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_14_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_14_ce0 : OUT STD_LOGIC;
    feat1_p_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_15_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_15_ce0 : OUT STD_LOGIC;
    feat1_p_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feat1_p_16_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    feat1_p_16_ce0 : OUT STD_LOGIC;
    feat1_p_16_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1268_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1268_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1268_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1268_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1268_p_ce : OUT STD_LOGIC;
    grp_fu_2859_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2859_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2859_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2859_p_ce : OUT STD_LOGIC );
end;


architecture behav of cnn_accel_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_48 : STD_LOGIC_VECTOR (6 downto 0) := "1001000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv15_9F : STD_LOGIC_VECTOR (14 downto 0) := "000000010011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln151_reg_757 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln151_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln151_reg_757_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_reg_757_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln151_fu_416_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln151_reg_761 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln153_fu_444_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln153_reg_766 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln153_reg_766_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln155_fu_464_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln155_reg_771 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln155_reg_771_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal gmem_addr_reg_776 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal tmp_8_fu_629_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_reg_827 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_addr_read_reg_832 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal bitcast_ln157_fu_668_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul3_reg_842 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_reg_852 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal p_cast2_fu_618_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal sext_ln157_fu_548_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal acc_fu_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal c_fu_140 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln155_fu_558_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal q_fu_144 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal indvar_flatten75_fu_148 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln153_1_fu_570_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_fu_152 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal indvar_flatten90_fu_156 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln151_1_fu_360_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal feat1_p_ce0_local : STD_LOGIC;
    signal feat1_p_10_ce0_local : STD_LOGIC;
    signal feat1_p_11_ce0_local : STD_LOGIC;
    signal feat1_p_12_ce0_local : STD_LOGIC;
    signal feat1_p_13_ce0_local : STD_LOGIC;
    signal feat1_p_14_ce0_local : STD_LOGIC;
    signal feat1_p_15_ce0_local : STD_LOGIC;
    signal feat1_p_16_ce0_local : STD_LOGIC;
    signal icmp_ln153_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln155_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln149_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln151_fu_378_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln149_fu_390_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln149_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln153_fu_424_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_1_mid2_fu_436_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln155_fu_460_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln156_fu_468_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl1_fu_477_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln156_fu_473_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln156_fu_485_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln151_fu_452_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln156_1_fu_491_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_501_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln156_1_fu_497_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln156_1_fu_509_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln153_fu_456_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln156_2_fu_515_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_521_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln157_fu_529_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln157_fu_533_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_538_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln153_1_fu_564_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage2_grp0 : BOOLEAN;
    signal zext_ln153_1_fu_606_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_90_fu_609_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_684_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_8_fu_629_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_684_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_684_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_684_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal grp_fu_313_ce : STD_LOGIC;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal grp_fu_317_ce : STD_LOGIC;
    signal grp_fu_684_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_684_p00 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_684_p30 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_8_fu_629_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_629_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accel_faddfsub_32ns_32ns_32_3_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_accel_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_accel_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_accel_ama_addmuladd_2ns_7ns_8ns_8ns_15_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (1 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component cnn_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_32_1_1_U76 : component cnn_accel_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => feat1_p_q0,
        din1 => feat1_p_10_q0,
        din2 => feat1_p_11_q0,
        din3 => feat1_p_12_q0,
        din4 => feat1_p_13_q0,
        din5 => feat1_p_14_q0,
        din6 => feat1_p_15_q0,
        din7 => feat1_p_16_q0,
        def => tmp_8_fu_629_p17,
        sel => trunc_ln155_reg_771_pp0_iter1_reg,
        dout => tmp_8_fu_629_p19);

    ama_addmuladd_2ns_7ns_8ns_8ns_15_4_1_U77 : component cnn_accel_ama_addmuladd_2ns_7ns_8ns_8ns_15_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 2,
        din1_WIDTH => 7,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_684_p0,
        din1 => i_3,
        din2 => grp_fu_684_p2,
        din3 => grp_fu_684_p3,
        ce => grp_fu_684_ce,
        dout => grp_fu_684_p4);

    flow_control_loop_pipe_sequential_init_U : component cnn_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2)) then 
                        ap_block_pp0_stage2_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    acc_fu_136 <= acc_28;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    acc_fu_136 <= acc_2_reg_852;
                end if;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    c_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                c_fu_140 <= ap_const_lv4_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln151_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                c_fu_140 <= add_ln155_fu_558_p2;
            end if; 
        end if;
    end process;

    indvar_flatten75_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten75_fu_148 <= ap_const_lv6_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln151_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten75_fu_148 <= select_ln153_1_fu_570_p3;
            end if; 
        end if;
    end process;

    indvar_flatten90_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten90_fu_156 <= ap_const_lv7_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln151_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten90_fu_156 <= add_ln151_1_fu_360_p2;
            end if; 
        end if;
    end process;

    p_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_fu_152 <= ap_const_lv2_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln151_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_fu_152 <= select_ln151_fu_416_p3;
            end if; 
        end if;
    end process;

    q_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                q_fu_144 <= ap_const_lv2_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln151_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                q_fu_144 <= select_ln153_fu_444_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                acc_2_reg_852 <= grp_fu_1268_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                gmem_addr_read_reg_832 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                gmem_addr_reg_776 <= sext_ln157_fu_548_p1;
                icmp_ln151_reg_757 <= icmp_ln151_fu_354_p2;
                icmp_ln151_reg_757_pp0_iter1_reg <= icmp_ln151_reg_757;
                icmp_ln151_reg_757_pp0_iter2_reg <= icmp_ln151_reg_757_pp0_iter1_reg;
                select_ln151_reg_761 <= select_ln151_fu_416_p3;
                select_ln153_reg_766 <= select_ln153_fu_444_p3;
                select_ln153_reg_766_pp0_iter1_reg <= select_ln153_reg_766;
                trunc_ln155_reg_771 <= trunc_ln155_fu_464_p1;
                trunc_ln155_reg_771_pp0_iter1_reg <= trunc_ln155_reg_771;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul3_reg_842 <= grp_fu_2859_p_dout0;
                tmp_8_reg_827 <= tmp_8_fu_629_p19;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2, ap_idle_pp0_1to4, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    acc_34_out <= acc_fu_136;

    acc_34_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln151_reg_757_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln151_reg_757_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_34_out_ap_vld <= ap_const_logic_1;
        else 
            acc_34_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln151_1_fu_360_p2 <= std_logic_vector(unsigned(indvar_flatten90_fu_156) + unsigned(ap_const_lv7_1));
    add_ln151_fu_378_p2 <= std_logic_vector(unsigned(p_fu_152) + unsigned(ap_const_lv2_1));
    add_ln153_1_fu_564_p2 <= std_logic_vector(unsigned(indvar_flatten75_fu_148) + unsigned(ap_const_lv6_1));
    add_ln153_fu_424_p2 <= std_logic_vector(unsigned(select_ln149_fu_390_p3) + unsigned(ap_const_lv2_1));
    add_ln155_fu_558_p2 <= std_logic_vector(unsigned(c_1_mid2_fu_436_p3) + unsigned(ap_const_lv4_1));
    add_ln156_1_fu_491_p2 <= std_logic_vector(unsigned(sub_ln156_fu_485_p2) + unsigned(zext_ln151_fu_452_p1));
    add_ln156_2_fu_515_p2 <= std_logic_vector(unsigned(sub_ln156_1_fu_509_p2) + unsigned(zext_ln153_fu_456_p1));
    add_ln156_fu_468_p2 <= std_logic_vector(unsigned(zext_ln155_fu_460_p1) + unsigned(tmp_42));
    add_ln157_fu_533_p2 <= std_logic_vector(unsigned(zext_ln157_fu_529_p1) + unsigned(weights2));
    and_ln149_fu_410_p2 <= (xor_ln149_fu_398_p2 and icmp_ln155_fu_404_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0_reg, m_axi_gmem_0_RVALID, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_11001 <= (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem_0_RVALID = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state3_io_grp1));
    end process;


    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_0_RVALID, ap_block_pp0_stage2_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem_0_RVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage2_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0_reg, m_axi_gmem_0_RVALID, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_subdone <= (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem_0_RVALID = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage2_subdone_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state3_io_grp1));
    end process;


    ap_block_pp0_stage2_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_0_RVALID, ap_block_pp0_stage2_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage2_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem_0_RVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_grp1_assign_proc : process(icmp_ln151_reg_757, m_axi_gmem_0_ARREADY)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_gmem_0_ARREADY = ap_const_logic_0) and (icmp_ln151_reg_757 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln151_reg_757)
    begin
        if (((icmp_ln151_reg_757 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln151_reg_757_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln151_reg_757_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln157_fu_668_p1 <= gmem_addr_read_reg_832;
    c_1_mid2_fu_436_p3 <= 
        ap_const_lv4_0 when (empty_fu_430_p2(0) = '1') else 
        c_fu_140;
    empty_90_fu_609_p2 <= std_logic_vector(unsigned(zext_ln153_1_fu_606_p1) + unsigned(j_3));
    empty_fu_430_p2 <= (icmp_ln153_fu_384_p2 or and_ln149_fu_410_p2);
    feat1_p_10_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_10_ce0 <= feat1_p_10_ce0_local;

    feat1_p_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_10_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_11_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_11_ce0 <= feat1_p_11_ce0_local;

    feat1_p_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_11_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_12_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_12_ce0 <= feat1_p_12_ce0_local;

    feat1_p_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_12_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_13_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_13_ce0 <= feat1_p_13_ce0_local;

    feat1_p_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_13_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_14_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_14_ce0 <= feat1_p_14_ce0_local;

    feat1_p_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_14_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_15_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_15_ce0 <= feat1_p_15_ce0_local;

    feat1_p_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_15_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_16_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_16_ce0 <= feat1_p_16_ce0_local;

    feat1_p_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_16_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    feat1_p_address0 <= p_cast2_fu_618_p1(15 - 1 downto 0);
    feat1_p_ce0 <= feat1_p_ce0_local;

    feat1_p_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            feat1_p_ce0_local <= ap_const_logic_1;
        else 
            feat1_p_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln151_reg_757, m_axi_gmem_0_ARREADY, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg)
    begin
        if (((icmp_ln151_reg_757 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            gmem_blk_n_AR <= m_axi_gmem_0_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_0_RVALID, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, ap_block_pp0_stage2_subdone_grp2_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            gmem_blk_n_R <= m_axi_gmem_0_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_1268_p_ce <= grp_fu_313_ce;
    grp_fu_1268_p_din0 <= acc_fu_136;
    grp_fu_1268_p_din1 <= mul3_reg_842;
    grp_fu_1268_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_2859_p_ce <= grp_fu_317_ce;
    grp_fu_2859_p_din0 <= tmp_8_reg_827;
    grp_fu_2859_p_din1 <= bitcast_ln157_fu_668_p1;

    grp_fu_313_ce_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_313_ce <= ap_const_logic_1;
        else 
            grp_fu_313_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_317_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_317_ce <= ap_const_logic_1;
        else 
            grp_fu_317_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_684_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_684_ce <= ap_const_logic_1;
        else 
            grp_fu_684_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_684_p0 <= grp_fu_684_p00(2 - 1 downto 0);
    grp_fu_684_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln151_reg_761),7));
    grp_fu_684_p2 <= ap_const_lv15_9F(8 - 1 downto 0);
    grp_fu_684_p3 <= grp_fu_684_p30(8 - 1 downto 0);
    grp_fu_684_p30 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_90_fu_609_p2),15));
    icmp_ln151_fu_354_p2 <= "1" when (indvar_flatten90_fu_156 = ap_const_lv7_48) else "0";
    icmp_ln153_fu_384_p2 <= "1" when (indvar_flatten75_fu_148 = ap_const_lv6_18) else "0";
    icmp_ln155_fu_404_p2 <= "1" when (c_fu_140 = ap_const_lv4_8) else "0";
    m_axi_gmem_0_ARADDR <= gmem_addr_reg_776;
    m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln151_reg_757, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_11001_grp1)
    begin
        if (((icmp_ln151_reg_757 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            m_axi_gmem_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp2_done_reg, ap_block_pp0_stage2_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            m_axi_gmem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;
    p_cast2_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_684_p4),64));
    p_shl1_fu_477_p3 <= (add_ln156_fu_468_p2 & ap_const_lv2_0);
    p_shl_fu_501_p3 <= (add_ln156_1_fu_491_p2 & ap_const_lv2_0);
    select_ln149_fu_390_p3 <= 
        ap_const_lv2_0 when (icmp_ln153_fu_384_p2(0) = '1') else 
        q_fu_144;
    select_ln151_fu_416_p3 <= 
        add_ln151_fu_378_p2 when (icmp_ln153_fu_384_p2(0) = '1') else 
        p_fu_152;
    select_ln153_1_fu_570_p3 <= 
        ap_const_lv6_1 when (icmp_ln153_fu_384_p2(0) = '1') else 
        add_ln153_1_fu_564_p2;
    select_ln153_fu_444_p3 <= 
        add_ln153_fu_424_p2 when (and_ln149_fu_410_p2(0) = '1') else 
        select_ln149_fu_390_p3;
        sext_ln157_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_538_p4),64));

    shl_ln_fu_521_p3 <= (add_ln156_2_fu_515_p2 & ap_const_lv2_0);
    sub_ln156_1_fu_509_p2 <= std_logic_vector(unsigned(p_shl_fu_501_p3) - unsigned(zext_ln156_1_fu_497_p1));
    sub_ln156_fu_485_p2 <= std_logic_vector(unsigned(p_shl1_fu_477_p3) - unsigned(zext_ln156_fu_473_p1));
    tmp_8_fu_629_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln155_fu_464_p1 <= c_1_mid2_fu_436_p3(3 - 1 downto 0);
    trunc_ln_fu_538_p4 <= add_ln157_fu_533_p2(63 downto 2);
    xor_ln149_fu_398_p2 <= (icmp_ln153_fu_384_p2 xor ap_const_lv1_1);
    zext_ln151_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln151_fu_416_p3),9));
    zext_ln153_1_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln153_reg_766_pp0_iter1_reg),8));
    zext_ln153_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln153_fu_444_p3),11));
    zext_ln155_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_mid2_fu_436_p3),7));
    zext_ln156_1_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln156_1_fu_491_p2),11));
    zext_ln156_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln156_fu_468_p2),9));
    zext_ln157_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_521_p3),64));
end behav;
