// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_exp_generic_double_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [63:0] x;
output  [63:0] ap_return;

wire   [7:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [57:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1;
wire   [7:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [41:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [0:0] es_sign_fu_284_p3;
reg   [0:0] es_sign_reg_1126;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] es_sign_reg_1126_pp0_iter1_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter2_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter3_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter4_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter5_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter6_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter7_reg;
reg   [0:0] es_sign_reg_1126_pp0_iter8_reg;
wire   [0:0] x_is_NaN_fu_316_p2;
reg   [0:0] x_is_NaN_reg_1131;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter1_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter2_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter3_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter4_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter5_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter6_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter7_reg;
reg   [0:0] x_is_NaN_reg_1131_pp0_iter8_reg;
wire   [0:0] x_is_inf_fu_328_p2;
reg   [0:0] x_is_inf_reg_1138;
reg   [0:0] x_is_inf_reg_1138_pp0_iter1_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter2_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter3_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter4_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter5_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter6_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter7_reg;
reg   [0:0] x_is_inf_reg_1138_pp0_iter8_reg;
reg   [0:0] tmp_2_reg_1144;
reg   [0:0] tmp_2_reg_1144_pp0_iter1_reg;
wire   [58:0] trunc_ln255_fu_484_p1;
reg   [58:0] trunc_ln255_reg_1154;
reg   [58:0] trunc_ln255_reg_1154_pp0_iter1_reg;
reg   [58:0] trunc_ln255_reg_1154_pp0_iter2_reg;
reg   [58:0] trunc_ln255_reg_1154_pp0_iter3_reg;
wire   [0:0] icmp_ln309_fu_488_p2;
reg   [0:0] icmp_ln309_reg_1159;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter1_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter2_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter3_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter4_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter5_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter6_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter7_reg;
reg   [0:0] icmp_ln309_reg_1159_pp0_iter8_reg;
wire   [0:0] icmp_ln309_2_fu_510_p2;
reg   [0:0] icmp_ln309_2_reg_1167;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter1_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter2_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter3_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter4_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter5_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter6_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter7_reg;
reg   [0:0] icmp_ln309_2_reg_1167_pp0_iter8_reg;
reg   [0:0] tmp_10_reg_1172;
reg   [0:0] tmp_10_reg_1172_pp0_iter1_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter2_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter3_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter4_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter5_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter6_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter7_reg;
reg   [0:0] tmp_10_reg_1172_pp0_iter8_reg;
wire  signed [12:0] r_exp_fu_574_p3;
reg  signed [12:0] r_exp_reg_1182;
reg  signed [12:0] r_exp_reg_1182_pp0_iter4_reg;
reg  signed [12:0] r_exp_reg_1182_pp0_iter5_reg;
reg  signed [12:0] r_exp_reg_1182_pp0_iter6_reg;
reg  signed [12:0] r_exp_reg_1182_pp0_iter7_reg;
reg  signed [12:0] r_exp_reg_1182_pp0_iter8_reg;
reg   [7:0] m_diff_hi_reg_1189;
reg   [7:0] m_diff_hi_reg_1189_pp0_iter5_reg;
reg   [7:0] m_diff_hi_reg_1189_pp0_iter6_reg;
reg   [7:0] Z2_reg_1194;
reg   [7:0] Z2_reg_1194_pp0_iter5_reg;
reg   [7:0] Z2_reg_1194_pp0_iter6_reg;
reg   [7:0] Z2_reg_1194_pp0_iter7_reg;
reg   [7:0] Z3_reg_1201;
reg   [7:0] Z3_reg_1201_pp0_iter5_reg;
wire   [34:0] Z4_fu_639_p1;
reg   [34:0] Z4_reg_1207;
reg   [34:0] Z4_reg_1207_pp0_iter5_reg;
reg   [7:0] Z4_ind_reg_1212;
wire   [35:0] exp_Z4_m_1_fu_678_p2;
reg   [35:0] exp_Z4_m_1_reg_1227;
wire   [42:0] exp_Z3_m_1_fu_684_p4;
reg   [42:0] exp_Z3_m_1_reg_1232;
reg   [19:0] tmp_9_reg_1237;
wire   [43:0] exp_Z2P_m_1_fu_736_p2;
reg   [43:0] exp_Z2P_m_1_reg_1252;
wire   [39:0] tmp_s_fu_742_p4;
reg   [39:0] tmp_s_reg_1257;
reg   [35:0] tmp_1_reg_1262;
reg   [57:0] exp_Z1_reg_1267;
wire   [98:0] mul_ln297_fu_276_p2;
reg   [98:0] mul_ln297_reg_1272;
wire   [63:0] zext_ln114_fu_653_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln119_fu_657_p1;
wire   [63:0] zext_ln138_fu_713_p1;
wire   [63:0] zext_ln292_fu_717_p1;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
wire   [42:0] mul_ln123_fu_268_p0;
wire   [35:0] mul_ln123_fu_268_p1;
wire   [48:0] mul_ln142_fu_272_p0;
wire   [43:0] mul_ln142_fu_272_p1;
wire   [49:0] mul_ln297_fu_276_p0;
wire   [49:0] mul_ln297_fu_276_p1;
wire   [63:0] data_fu_280_p1;
wire   [10:0] es_exp_fu_292_p3;
wire   [51:0] es_sig_fu_300_p1;
wire   [0:0] icmp_ln18_fu_304_p2;
wire   [0:0] icmp_ln18_1_fu_310_p2;
wire   [0:0] icmp_ln18_2_fu_322_p2;
wire   [11:0] zext_ln486_fu_334_p1;
wire   [52:0] e_frac_fu_344_p3;
wire   [53:0] zext_ln221_fu_352_p1;
wire   [53:0] e_frac_1_fu_356_p2;
wire   [53:0] e_frac_2_fu_362_p3;
wire   [60:0] m_frac_l_fu_370_p3;
wire   [11:0] m_exp_fu_338_p2;
wire   [10:0] sub_ln229_fu_390_p2;
wire   [0:0] tmp_fu_382_p3;
wire  signed [11:0] sext_ln229_fu_396_p1;
wire   [11:0] select_ln229_fu_400_p3;
wire  signed [31:0] sext_ln229_1_fu_408_p1;
wire  signed [70:0] sext_ln227_fu_378_p1;
wire   [70:0] zext_ln229_fu_412_p1;
wire   [70:0] ashr_ln229_fu_416_p2;
wire   [70:0] shl_ln229_fu_422_p2;
wire   [70:0] m_fix_fu_428_p3;
wire   [63:0] m_fix_l_fu_436_p4;
wire   [63:0] zext_ln230_fu_446_p1;
wire  signed [15:0] m_fix_hi_fu_462_p4;
wire   [63:0] shl_ln230_fu_450_p2;
wire   [63:0] ashr_ln230_fu_456_p2;
wire   [63:0] select_ln230_fu_494_p3;
wire   [70:0] shl_ln2_fu_502_p3;
wire  signed [18:0] shl_ln_fu_524_p3;
wire  signed [30:0] grp_fu_1115_p3;
wire   [17:0] trunc_ln243_fu_551_p1;
wire   [12:0] tmp_9_cast_fu_535_p4;
wire   [0:0] icmp_ln243_fu_554_p2;
wire   [12:0] add_ln243_1_fu_560_p2;
wire   [0:0] tmp_3_fu_544_p3;
wire   [12:0] select_ln243_fu_566_p3;
wire   [70:0] mul_ln249_fu_263_p2;
wire   [57:0] tmp_8_fu_586_p4;
wire   [58:0] and_ln_fu_596_p3;
wire   [58:0] sub_ln255_fu_604_p2;
wire   [9:0] f_Z4_fu_661_p4;
wire   [35:0] zext_ln115_fu_671_p1;
wire   [35:0] zext_ln115_1_fu_674_p1;
wire   [78:0] mul_ln123_fu_268_p2;
wire   [35:0] zext_ln126_1_fu_724_p1;
wire   [35:0] add_ln126_fu_727_p2;
wire   [43:0] zext_ln126_fu_732_p1;
wire   [43:0] zext_ln120_fu_721_p1;
wire   [48:0] exp_Z2_m_1_fu_752_p4;
wire   [92:0] mul_ln142_fu_272_p2;
wire   [50:0] and_ln1_fu_781_p5;
wire   [43:0] zext_ln145_2_fu_795_p1;
wire   [43:0] add_ln145_fu_798_p2;
wire   [51:0] zext_ln145_1_fu_803_p1;
wire   [51:0] zext_ln145_fu_791_p1;
wire   [51:0] exp_Z1P_m_1_l_fu_807_p2;
wire   [49:0] exp_Z1_hi_fu_823_p4;
wire   [49:0] exp_Z1P_m_1_fu_813_p4;
wire   [0:0] xor_ln182_fu_843_p2;
wire   [0:0] x_is_pinf_fu_848_p2;
wire   [0:0] or_ln185_fu_853_p2;
wire   [63:0] select_ln185_fu_858_p3;
wire   [57:0] add_ln297_fu_877_p2;
wire   [106:0] shl_ln1_fu_882_p3;
wire   [106:0] zext_ln297_2_fu_890_p1;
wire   [106:0] add_ln297_1_fu_893_p2;
wire   [0:0] tmp_5_fu_899_p3;
wire   [12:0] r_exp_1_fu_907_p2;
wire   [12:0] r_exp_2_fu_912_p3;
wire   [2:0] tmp_7_fu_919_p4;
wire   [0:0] icmp_ln309_1_fu_929_p2;
wire   [10:0] trunc_ln336_fu_953_p1;
wire   [51:0] tmp_4_fu_963_p4;
wire   [51:0] tmp_6_fu_973_p4;
wire   [10:0] out_exp_fu_957_p2;
wire   [51:0] select_ln303_fu_983_p3;
wire   [62:0] t_fu_991_p3;
wire   [63:0] zext_ln479_fu_999_p1;
wire   [0:0] or_ln309_fu_935_p2;
wire   [0:0] xor_ln309_fu_1012_p2;
wire   [0:0] and_ln309_fu_1007_p2;
wire   [0:0] and_ln309_1_fu_1017_p2;
wire   [0:0] or_ln185_1_fu_865_p2;
wire   [0:0] or_ln309_1_fu_1023_p2;
wire   [0:0] xor_ln185_fu_1029_p2;
wire   [0:0] xor_ln309_1_fu_1041_p2;
wire   [0:0] or_ln309_2_fu_1052_p2;
wire   [0:0] and_ln309_3_fu_1047_p2;
wire   [0:0] xor_ln309_2_fu_1057_p2;
wire   [0:0] or_ln309_3_fu_1063_p2;
wire   [0:0] and_ln309_4_fu_1069_p2;
wire   [0:0] icmp_ln326_fu_947_p2;
wire   [0:0] and_ln309_2_fu_1035_p2;
wire   [0:0] and_ln309_5_fu_1075_p2;
wire   [63:0] retval_1_fu_1091_p2;
wire   [63:0] retval_1_fu_1091_p4;
wire   [63:0] retval_1_fu_1091_p8;
wire   [63:0] retval_1_fu_1091_p9;
wire   [2:0] retval_1_fu_1091_p10;
wire   [14:0] grp_fu_1115_p1;
wire   [63:0] retval_1_fu_1091_p11;
reg   [63:0] x_int_reg;
wire   [78:0] mul_ln123_fu_268_p00;
wire   [78:0] mul_ln123_fu_268_p10;
wire   [92:0] mul_ln142_fu_272_p00;
wire   [92:0] mul_ln142_fu_272_p10;
wire   [98:0] mul_ln297_fu_276_p00;
wire   [98:0] mul_ln297_fu_276_p10;
wire  signed [2:0] retval_1_fu_1091_p1;
wire   [2:0] retval_1_fu_1091_p3;
wire   [2:0] retval_1_fu_1091_p5;
wire   [2:0] retval_1_fu_1091_p7;
wire    ap_ce_reg;

cnn_accel_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

cnn_accel_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0),
    .address1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1),
    .ce1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local),
    .q1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1)
);

cnn_accel_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

cnn_accel_mul_13s_71s_71_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_1_U163(
    .din0(r_exp_reg_1182),
    .din1(71'd1636647506585939924452),
    .dout(mul_ln249_fu_263_p2)
);

cnn_accel_mul_43ns_36ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 43 ),
    .din1_WIDTH( 36 ),
    .dout_WIDTH( 79 ))
mul_43ns_36ns_79_1_1_U164(
    .din0(mul_ln123_fu_268_p0),
    .din1(mul_ln123_fu_268_p1),
    .dout(mul_ln123_fu_268_p2)
);

cnn_accel_mul_49ns_44ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44ns_93_1_1_U165(
    .din0(mul_ln142_fu_272_p0),
    .din1(mul_ln142_fu_272_p1),
    .dout(mul_ln142_fu_272_p2)
);

cnn_accel_mul_50ns_50ns_99_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 99 ))
mul_50ns_50ns_99_1_1_U166(
    .din0(mul_ln297_fu_276_p0),
    .din1(mul_ln297_fu_276_p1),
    .dout(mul_ln297_fu_276_p2)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_9_3_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_9_3_64_1_1_U167(
    .din0(retval_1_fu_1091_p2),
    .din1(retval_1_fu_1091_p4),
    .din2(64'd0),
    .din3(retval_1_fu_1091_p8),
    .def(retval_1_fu_1091_p9),
    .sel(retval_1_fu_1091_p10),
    .dout(retval_1_fu_1091_p11)
);

cnn_accel_mac_muladd_16s_15ns_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_19s_31_4_1_U168(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_fu_462_p4),
    .din1(grp_fu_1115_p1),
    .din2(shl_ln_fu_524_p3),
    .ce(1'b1),
    .dout(grp_fu_1115_p3)
);

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Z2_reg_1194 <= {{sub_ln255_fu_604_p2[50:43]}};
        Z2_reg_1194_pp0_iter5_reg <= Z2_reg_1194;
        Z2_reg_1194_pp0_iter6_reg <= Z2_reg_1194_pp0_iter5_reg;
        Z2_reg_1194_pp0_iter7_reg <= Z2_reg_1194_pp0_iter6_reg;
        Z3_reg_1201 <= {{sub_ln255_fu_604_p2[42:35]}};
        Z3_reg_1201_pp0_iter5_reg <= Z3_reg_1201;
        Z4_ind_reg_1212 <= {{sub_ln255_fu_604_p2[34:27]}};
        Z4_reg_1207 <= Z4_fu_639_p1;
        Z4_reg_1207_pp0_iter5_reg <= Z4_reg_1207;
        es_sign_reg_1126 <= data_fu_280_p1[32'd63];
        es_sign_reg_1126_pp0_iter1_reg <= es_sign_reg_1126;
        es_sign_reg_1126_pp0_iter2_reg <= es_sign_reg_1126_pp0_iter1_reg;
        es_sign_reg_1126_pp0_iter3_reg <= es_sign_reg_1126_pp0_iter2_reg;
        es_sign_reg_1126_pp0_iter4_reg <= es_sign_reg_1126_pp0_iter3_reg;
        es_sign_reg_1126_pp0_iter5_reg <= es_sign_reg_1126_pp0_iter4_reg;
        es_sign_reg_1126_pp0_iter6_reg <= es_sign_reg_1126_pp0_iter5_reg;
        es_sign_reg_1126_pp0_iter7_reg <= es_sign_reg_1126_pp0_iter6_reg;
        es_sign_reg_1126_pp0_iter8_reg <= es_sign_reg_1126_pp0_iter7_reg;
        exp_Z1_reg_1267 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
        exp_Z2P_m_1_reg_1252 <= exp_Z2P_m_1_fu_736_p2;
        exp_Z3_m_1_reg_1232[25 : 0] <= exp_Z3_m_1_fu_684_p4[25 : 0];
exp_Z3_m_1_reg_1232[42 : 35] <= exp_Z3_m_1_fu_684_p4[42 : 35];
        exp_Z4_m_1_reg_1227 <= exp_Z4_m_1_fu_678_p2;
        icmp_ln309_2_reg_1167 <= icmp_ln309_2_fu_510_p2;
        icmp_ln309_2_reg_1167_pp0_iter1_reg <= icmp_ln309_2_reg_1167;
        icmp_ln309_2_reg_1167_pp0_iter2_reg <= icmp_ln309_2_reg_1167_pp0_iter1_reg;
        icmp_ln309_2_reg_1167_pp0_iter3_reg <= icmp_ln309_2_reg_1167_pp0_iter2_reg;
        icmp_ln309_2_reg_1167_pp0_iter4_reg <= icmp_ln309_2_reg_1167_pp0_iter3_reg;
        icmp_ln309_2_reg_1167_pp0_iter5_reg <= icmp_ln309_2_reg_1167_pp0_iter4_reg;
        icmp_ln309_2_reg_1167_pp0_iter6_reg <= icmp_ln309_2_reg_1167_pp0_iter5_reg;
        icmp_ln309_2_reg_1167_pp0_iter7_reg <= icmp_ln309_2_reg_1167_pp0_iter6_reg;
        icmp_ln309_2_reg_1167_pp0_iter8_reg <= icmp_ln309_2_reg_1167_pp0_iter7_reg;
        icmp_ln309_reg_1159 <= icmp_ln309_fu_488_p2;
        icmp_ln309_reg_1159_pp0_iter1_reg <= icmp_ln309_reg_1159;
        icmp_ln309_reg_1159_pp0_iter2_reg <= icmp_ln309_reg_1159_pp0_iter1_reg;
        icmp_ln309_reg_1159_pp0_iter3_reg <= icmp_ln309_reg_1159_pp0_iter2_reg;
        icmp_ln309_reg_1159_pp0_iter4_reg <= icmp_ln309_reg_1159_pp0_iter3_reg;
        icmp_ln309_reg_1159_pp0_iter5_reg <= icmp_ln309_reg_1159_pp0_iter4_reg;
        icmp_ln309_reg_1159_pp0_iter6_reg <= icmp_ln309_reg_1159_pp0_iter5_reg;
        icmp_ln309_reg_1159_pp0_iter7_reg <= icmp_ln309_reg_1159_pp0_iter6_reg;
        icmp_ln309_reg_1159_pp0_iter8_reg <= icmp_ln309_reg_1159_pp0_iter7_reg;
        m_diff_hi_reg_1189 <= {{sub_ln255_fu_604_p2[58:51]}};
        m_diff_hi_reg_1189_pp0_iter5_reg <= m_diff_hi_reg_1189;
        m_diff_hi_reg_1189_pp0_iter6_reg <= m_diff_hi_reg_1189_pp0_iter5_reg;
        mul_ln297_reg_1272 <= mul_ln297_fu_276_p2;
        r_exp_reg_1182 <= r_exp_fu_574_p3;
        r_exp_reg_1182_pp0_iter4_reg <= r_exp_reg_1182;
        r_exp_reg_1182_pp0_iter5_reg <= r_exp_reg_1182_pp0_iter4_reg;
        r_exp_reg_1182_pp0_iter6_reg <= r_exp_reg_1182_pp0_iter5_reg;
        r_exp_reg_1182_pp0_iter7_reg <= r_exp_reg_1182_pp0_iter6_reg;
        r_exp_reg_1182_pp0_iter8_reg <= r_exp_reg_1182_pp0_iter7_reg;
        tmp_10_reg_1172 <= e_frac_2_fu_362_p3[32'd53];
        tmp_10_reg_1172_pp0_iter1_reg <= tmp_10_reg_1172;
        tmp_10_reg_1172_pp0_iter2_reg <= tmp_10_reg_1172_pp0_iter1_reg;
        tmp_10_reg_1172_pp0_iter3_reg <= tmp_10_reg_1172_pp0_iter2_reg;
        tmp_10_reg_1172_pp0_iter4_reg <= tmp_10_reg_1172_pp0_iter3_reg;
        tmp_10_reg_1172_pp0_iter5_reg <= tmp_10_reg_1172_pp0_iter4_reg;
        tmp_10_reg_1172_pp0_iter6_reg <= tmp_10_reg_1172_pp0_iter5_reg;
        tmp_10_reg_1172_pp0_iter7_reg <= tmp_10_reg_1172_pp0_iter6_reg;
        tmp_10_reg_1172_pp0_iter8_reg <= tmp_10_reg_1172_pp0_iter7_reg;
        tmp_1_reg_1262 <= {{mul_ln142_fu_272_p2[92:57]}};
        tmp_2_reg_1144 <= m_fix_fu_428_p3[32'd70];
        tmp_2_reg_1144_pp0_iter1_reg <= tmp_2_reg_1144;
        tmp_9_reg_1237 <= {{mul_ln123_fu_268_p2[78:59]}};
        tmp_s_reg_1257 <= {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0[41:2]}};
        trunc_ln255_reg_1154 <= trunc_ln255_fu_484_p1;
        trunc_ln255_reg_1154_pp0_iter1_reg <= trunc_ln255_reg_1154;
        trunc_ln255_reg_1154_pp0_iter2_reg <= trunc_ln255_reg_1154_pp0_iter1_reg;
        trunc_ln255_reg_1154_pp0_iter3_reg <= trunc_ln255_reg_1154_pp0_iter2_reg;
        x_is_NaN_reg_1131 <= x_is_NaN_fu_316_p2;
        x_is_NaN_reg_1131_pp0_iter1_reg <= x_is_NaN_reg_1131;
        x_is_NaN_reg_1131_pp0_iter2_reg <= x_is_NaN_reg_1131_pp0_iter1_reg;
        x_is_NaN_reg_1131_pp0_iter3_reg <= x_is_NaN_reg_1131_pp0_iter2_reg;
        x_is_NaN_reg_1131_pp0_iter4_reg <= x_is_NaN_reg_1131_pp0_iter3_reg;
        x_is_NaN_reg_1131_pp0_iter5_reg <= x_is_NaN_reg_1131_pp0_iter4_reg;
        x_is_NaN_reg_1131_pp0_iter6_reg <= x_is_NaN_reg_1131_pp0_iter5_reg;
        x_is_NaN_reg_1131_pp0_iter7_reg <= x_is_NaN_reg_1131_pp0_iter6_reg;
        x_is_NaN_reg_1131_pp0_iter8_reg <= x_is_NaN_reg_1131_pp0_iter7_reg;
        x_is_inf_reg_1138 <= x_is_inf_fu_328_p2;
        x_is_inf_reg_1138_pp0_iter1_reg <= x_is_inf_reg_1138;
        x_is_inf_reg_1138_pp0_iter2_reg <= x_is_inf_reg_1138_pp0_iter1_reg;
        x_is_inf_reg_1138_pp0_iter3_reg <= x_is_inf_reg_1138_pp0_iter2_reg;
        x_is_inf_reg_1138_pp0_iter4_reg <= x_is_inf_reg_1138_pp0_iter3_reg;
        x_is_inf_reg_1138_pp0_iter5_reg <= x_is_inf_reg_1138_pp0_iter4_reg;
        x_is_inf_reg_1138_pp0_iter6_reg <= x_is_inf_reg_1138_pp0_iter5_reg;
        x_is_inf_reg_1138_pp0_iter7_reg <= x_is_inf_reg_1138_pp0_iter6_reg;
        x_is_inf_reg_1138_pp0_iter8_reg <= x_is_inf_reg_1138_pp0_iter7_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b0;
    end
end

assign Z4_fu_639_p1 = sub_ln255_fu_604_p2[34:0];

assign add_ln126_fu_727_p2 = (exp_Z4_m_1_reg_1227 + zext_ln126_1_fu_724_p1);

assign add_ln145_fu_798_p2 = (exp_Z2P_m_1_reg_1252 + zext_ln145_2_fu_795_p1);

assign add_ln243_1_fu_560_p2 = (tmp_9_cast_fu_535_p4 + 13'd1);

assign add_ln297_1_fu_893_p2 = (shl_ln1_fu_882_p3 + zext_ln297_2_fu_890_p1);

assign add_ln297_fu_877_p2 = (exp_Z1_reg_1267 + 58'd16);

assign and_ln1_fu_781_p5 = {{{{Z2_reg_1194_pp0_iter7_reg}, {1'd0}}, {tmp_s_reg_1257}}, {2'd0}};

assign and_ln309_1_fu_1017_p2 = (xor_ln309_fu_1012_p2 & icmp_ln309_1_fu_929_p2);

assign and_ln309_2_fu_1035_p2 = (xor_ln185_fu_1029_p2 & or_ln309_1_fu_1023_p2);

assign and_ln309_3_fu_1047_p2 = (xor_ln309_1_fu_1041_p2 & icmp_ln309_reg_1159_pp0_iter8_reg);

assign and_ln309_4_fu_1069_p2 = (xor_ln185_fu_1029_p2 & or_ln309_3_fu_1063_p2);

assign and_ln309_5_fu_1075_p2 = (icmp_ln326_fu_947_p2 & and_ln309_4_fu_1069_p2);

assign and_ln309_fu_1007_p2 = (or_ln309_fu_935_p2 & icmp_ln309_reg_1159_pp0_iter8_reg);

assign and_ln_fu_596_p3 = {{tmp_8_fu_586_p4}, {1'd0}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = retval_1_fu_1091_p11;

assign ashr_ln229_fu_416_p2 = $signed(sext_ln227_fu_378_p1) >>> zext_ln229_fu_412_p1;

assign ashr_ln230_fu_456_p2 = $signed(m_fix_l_fu_436_p4) >>> zext_ln230_fu_446_p1;

assign data_fu_280_p1 = x_int_reg;

assign e_frac_1_fu_356_p2 = (54'd0 - zext_ln221_fu_352_p1);

assign e_frac_2_fu_362_p3 = ((es_sign_fu_284_p3[0:0] == 1'b1) ? e_frac_1_fu_356_p2 : zext_ln221_fu_352_p1);

assign e_frac_fu_344_p3 = {{1'd1}, {es_sig_fu_300_p1}};

assign es_exp_fu_292_p3 = {{data_fu_280_p1[62:52]}};

assign es_sig_fu_300_p1 = data_fu_280_p1[51:0];

assign es_sign_fu_284_p3 = data_fu_280_p1[32'd63];

assign exp_Z1P_m_1_fu_813_p4 = {{exp_Z1P_m_1_l_fu_807_p2[51:2]}};

assign exp_Z1P_m_1_l_fu_807_p2 = (zext_ln145_1_fu_803_p1 + zext_ln145_fu_791_p1);

assign exp_Z1_hi_fu_823_p4 = {{table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0[57:8]}};

assign exp_Z2P_m_1_fu_736_p2 = (zext_ln126_fu_732_p1 + zext_ln120_fu_721_p1);

assign exp_Z2_m_1_fu_752_p4 = {{{Z2_reg_1194_pp0_iter6_reg}, {1'd0}}, {tmp_s_fu_742_p4}};

assign exp_Z3_m_1_fu_684_p4 = {{{Z3_reg_1201_pp0_iter5_reg}, {9'd0}}, {table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0}};

assign exp_Z4_m_1_fu_678_p2 = (zext_ln115_fu_671_p1 + zext_ln115_1_fu_674_p1);

assign f_Z4_fu_661_p4 = {{table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1[25:16]}};

assign grp_fu_1115_p1 = 31'd23637;

assign icmp_ln18_1_fu_310_p2 = ((es_sig_fu_300_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_322_p2 = ((es_sig_fu_300_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_304_p2 = ((es_exp_fu_292_p3 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_554_p2 = ((trunc_ln243_fu_551_p1 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln309_1_fu_929_p2 = (($signed(tmp_7_fu_919_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln309_2_fu_510_p2 = ((shl_ln2_fu_502_p3 != sext_ln227_fu_378_p1) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_488_p2 = (($signed(m_exp_fu_338_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_947_p2 = (($signed(r_exp_2_fu_912_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign m_exp_fu_338_p2 = ($signed(zext_ln486_fu_334_p1) + $signed(12'd3073));

assign m_fix_fu_428_p3 = ((tmp_fu_382_p3[0:0] == 1'b1) ? ashr_ln229_fu_416_p2 : shl_ln229_fu_422_p2);

assign m_fix_hi_fu_462_p4 = {{m_fix_fu_428_p3[70:55]}};

assign m_fix_l_fu_436_p4 = {{m_fix_fu_428_p3[70:7]}};

assign m_frac_l_fu_370_p3 = {{e_frac_2_fu_362_p3}, {7'd0}};

assign mul_ln123_fu_268_p0 = mul_ln123_fu_268_p00;

assign mul_ln123_fu_268_p00 = exp_Z3_m_1_fu_684_p4;

assign mul_ln123_fu_268_p1 = mul_ln123_fu_268_p10;

assign mul_ln123_fu_268_p10 = exp_Z4_m_1_fu_678_p2;

assign mul_ln142_fu_272_p0 = mul_ln142_fu_272_p00;

assign mul_ln142_fu_272_p00 = exp_Z2_m_1_fu_752_p4;

assign mul_ln142_fu_272_p1 = mul_ln142_fu_272_p10;

assign mul_ln142_fu_272_p10 = exp_Z2P_m_1_fu_736_p2;

assign mul_ln297_fu_276_p0 = mul_ln297_fu_276_p00;

assign mul_ln297_fu_276_p00 = exp_Z1P_m_1_fu_813_p4;

assign mul_ln297_fu_276_p1 = mul_ln297_fu_276_p10;

assign mul_ln297_fu_276_p10 = exp_Z1_hi_fu_823_p4;

assign or_ln185_1_fu_865_p2 = (x_is_inf_reg_1138_pp0_iter8_reg | x_is_NaN_reg_1131_pp0_iter8_reg);

assign or_ln185_fu_853_p2 = (x_is_pinf_fu_848_p2 | x_is_NaN_reg_1131_pp0_iter8_reg);

assign or_ln309_1_fu_1023_p2 = (and_ln309_fu_1007_p2 | and_ln309_1_fu_1017_p2);

assign or_ln309_2_fu_1052_p2 = (icmp_ln309_reg_1159_pp0_iter8_reg | icmp_ln309_1_fu_929_p2);

assign or_ln309_3_fu_1063_p2 = (xor_ln309_2_fu_1057_p2 | and_ln309_3_fu_1047_p2);

assign or_ln309_fu_935_p2 = (icmp_ln309_2_reg_1167_pp0_iter8_reg | icmp_ln309_1_fu_929_p2);

assign out_exp_fu_957_p2 = (trunc_ln336_fu_953_p1 + 11'd1023);

assign r_exp_1_fu_907_p2 = ($signed(r_exp_reg_1182_pp0_iter8_reg) + $signed(13'd8191));

assign r_exp_2_fu_912_p3 = ((tmp_5_fu_899_p3[0:0] == 1'b1) ? r_exp_reg_1182_pp0_iter8_reg : r_exp_1_fu_907_p2);

assign r_exp_fu_574_p3 = ((tmp_3_fu_544_p3[0:0] == 1'b1) ? select_ln243_fu_566_p3 : tmp_9_cast_fu_535_p4);

assign retval_1_fu_1091_p10 = {{{or_ln185_1_fu_865_p2}, {and_ln309_2_fu_1035_p2}}, {and_ln309_5_fu_1075_p2}};

assign retval_1_fu_1091_p2 = ((or_ln185_fu_853_p2[0:0] == 1'b1) ? select_ln185_fu_858_p3 : 64'd0);

assign retval_1_fu_1091_p4 = ((tmp_10_reg_1172_pp0_iter8_reg[0:0] == 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign retval_1_fu_1091_p8 = zext_ln479_fu_999_p1;

assign retval_1_fu_1091_p9 = 'bx;

assign select_ln185_fu_858_p3 = ((x_is_NaN_reg_1131_pp0_iter8_reg[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd9218868437227405312);

assign select_ln229_fu_400_p3 = ((tmp_fu_382_p3[0:0] == 1'b1) ? sext_ln229_fu_396_p1 : m_exp_fu_338_p2);

assign select_ln230_fu_494_p3 = ((tmp_fu_382_p3[0:0] == 1'b1) ? shl_ln230_fu_450_p2 : ashr_ln230_fu_456_p2);

assign select_ln243_fu_566_p3 = ((icmp_ln243_fu_554_p2[0:0] == 1'b1) ? add_ln243_1_fu_560_p2 : tmp_9_cast_fu_535_p4);

assign select_ln303_fu_983_p3 = ((tmp_5_fu_899_p3[0:0] == 1'b1) ? tmp_4_fu_963_p4 : tmp_6_fu_973_p4);

assign sext_ln227_fu_378_p1 = $signed(m_frac_l_fu_370_p3);

assign sext_ln229_1_fu_408_p1 = $signed(select_ln229_fu_400_p3);

assign sext_ln229_fu_396_p1 = $signed(sub_ln229_fu_390_p2);

assign shl_ln1_fu_882_p3 = {{add_ln297_fu_877_p2}, {49'd0}};

assign shl_ln229_fu_422_p2 = sext_ln227_fu_378_p1 << zext_ln229_fu_412_p1;

assign shl_ln230_fu_450_p2 = m_fix_l_fu_436_p4 << zext_ln230_fu_446_p1;

assign shl_ln2_fu_502_p3 = {{select_ln230_fu_494_p3}, {7'd0}};

assign shl_ln_fu_524_p3 = {{tmp_2_reg_1144_pp0_iter1_reg}, {18'd131072}};

assign sub_ln229_fu_390_p2 = (11'd1023 - es_exp_fu_292_p3);

assign sub_ln255_fu_604_p2 = (trunc_ln255_reg_1154_pp0_iter3_reg - and_ln_fu_596_p3);

assign t_fu_991_p3 = {{out_exp_fu_957_p2}, {select_ln303_fu_983_p3}};

assign table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln292_fu_717_p1;

assign table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln138_fu_713_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln119_fu_657_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1 = zext_ln114_fu_653_p1;

assign tmp_3_fu_544_p3 = grp_fu_1115_p3[32'd30];

assign tmp_4_fu_963_p4 = {{add_ln297_1_fu_893_p2[105:54]}};

assign tmp_5_fu_899_p3 = add_ln297_1_fu_893_p2[32'd106];

assign tmp_6_fu_973_p4 = {{add_ln297_1_fu_893_p2[104:53]}};

assign tmp_7_fu_919_p4 = {{r_exp_2_fu_912_p3[12:10]}};

assign tmp_8_fu_586_p4 = {{mul_ln249_fu_263_p2[70:13]}};

assign tmp_9_cast_fu_535_p4 = {{grp_fu_1115_p3[30:18]}};

assign tmp_fu_382_p3 = m_exp_fu_338_p2[32'd11];

assign tmp_s_fu_742_p4 = {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0[41:2]}};

assign trunc_ln243_fu_551_p1 = grp_fu_1115_p3[17:0];

assign trunc_ln255_fu_484_p1 = m_fix_fu_428_p3[58:0];

assign trunc_ln336_fu_953_p1 = r_exp_2_fu_912_p3[10:0];

assign x_is_NaN_fu_316_p2 = (icmp_ln18_fu_304_p2 & icmp_ln18_1_fu_310_p2);

assign x_is_inf_fu_328_p2 = (icmp_ln18_fu_304_p2 & icmp_ln18_2_fu_322_p2);

assign x_is_pinf_fu_848_p2 = (xor_ln182_fu_843_p2 & x_is_inf_reg_1138_pp0_iter8_reg);

assign xor_ln182_fu_843_p2 = (es_sign_reg_1126_pp0_iter8_reg ^ 1'd1);

assign xor_ln185_fu_1029_p2 = (or_ln185_1_fu_865_p2 ^ 1'd1);

assign xor_ln309_1_fu_1041_p2 = (or_ln309_fu_935_p2 ^ 1'd1);

assign xor_ln309_2_fu_1057_p2 = (or_ln309_2_fu_1052_p2 ^ 1'd1);

assign xor_ln309_fu_1012_p2 = (icmp_ln309_reg_1159_pp0_iter8_reg ^ 1'd1);

assign zext_ln114_fu_653_p1 = Z4_ind_reg_1212;

assign zext_ln115_1_fu_674_p1 = f_Z4_fu_661_p4;

assign zext_ln115_fu_671_p1 = Z4_reg_1207_pp0_iter5_reg;

assign zext_ln119_fu_657_p1 = Z3_reg_1201;

assign zext_ln120_fu_721_p1 = exp_Z3_m_1_reg_1232;

assign zext_ln126_1_fu_724_p1 = tmp_9_reg_1237;

assign zext_ln126_fu_732_p1 = add_ln126_fu_727_p2;

assign zext_ln138_fu_713_p1 = Z2_reg_1194_pp0_iter5_reg;

assign zext_ln145_1_fu_803_p1 = add_ln145_fu_798_p2;

assign zext_ln145_2_fu_795_p1 = tmp_1_reg_1262;

assign zext_ln145_fu_791_p1 = and_ln1_fu_781_p5;

assign zext_ln221_fu_352_p1 = e_frac_fu_344_p3;

assign zext_ln229_fu_412_p1 = $unsigned(sext_ln229_1_fu_408_p1);

assign zext_ln230_fu_446_p1 = $unsigned(sext_ln229_1_fu_408_p1);

assign zext_ln292_fu_717_p1 = m_diff_hi_reg_1189_pp0_iter6_reg;

assign zext_ln297_2_fu_890_p1 = mul_ln297_reg_1272;

assign zext_ln479_fu_999_p1 = t_fu_991_p3;

assign zext_ln486_fu_334_p1 = es_exp_fu_292_p3;

always @ (posedge ap_clk) begin
    exp_Z3_m_1_reg_1232[34:26] <= 9'b000000000;
end

endmodule //cnn_accel_exp_generic_double_s
