// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feat2_p_address0,
        feat2_p_ce0,
        feat2_p_q0,
        feat2_p_26_address0,
        feat2_p_26_ce0,
        feat2_p_26_q0,
        feat2_p_27_address0,
        feat2_p_27_ce0,
        feat2_p_27_q0,
        feat2_p_28_address0,
        feat2_p_28_ce0,
        feat2_p_28_q0,
        feat2_p_29_address0,
        feat2_p_29_ce0,
        feat2_p_29_q0,
        feat2_p_30_address0,
        feat2_p_30_ce0,
        feat2_p_30_q0,
        feat2_p_31_address0,
        feat2_p_31_ce0,
        feat2_p_31_q0,
        feat2_p_32_address0,
        feat2_p_32_ce0,
        feat2_p_32_q0,
        feat2_p_33_address0,
        feat2_p_33_ce0,
        feat2_p_33_q0,
        feat2_p_34_address0,
        feat2_p_34_ce0,
        feat2_p_34_q0,
        p_ZZ9cnn_accelE7feat2_p_10_address0,
        p_ZZ9cnn_accelE7feat2_p_10_ce0,
        p_ZZ9cnn_accelE7feat2_p_10_q0,
        p_ZZ9cnn_accelE7feat2_p_11_address0,
        p_ZZ9cnn_accelE7feat2_p_11_ce0,
        p_ZZ9cnn_accelE7feat2_p_11_q0,
        p_ZZ9cnn_accelE7feat2_p_12_address0,
        p_ZZ9cnn_accelE7feat2_p_12_ce0,
        p_ZZ9cnn_accelE7feat2_p_12_q0,
        p_ZZ9cnn_accelE7feat2_p_13_address0,
        p_ZZ9cnn_accelE7feat2_p_13_ce0,
        p_ZZ9cnn_accelE7feat2_p_13_q0,
        p_ZZ9cnn_accelE7feat2_p_14_address0,
        p_ZZ9cnn_accelE7feat2_p_14_ce0,
        p_ZZ9cnn_accelE7feat2_p_14_q0,
        p_ZZ9cnn_accelE7feat2_p_15_address0,
        p_ZZ9cnn_accelE7feat2_p_15_ce0,
        p_ZZ9cnn_accelE7feat2_p_15_q0,
        vec1_address0,
        vec1_ce0,
        vec1_we0,
        vec1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] feat2_p_address0;
output   feat2_p_ce0;
input  [31:0] feat2_p_q0;
output  [12:0] feat2_p_26_address0;
output   feat2_p_26_ce0;
input  [31:0] feat2_p_26_q0;
output  [12:0] feat2_p_27_address0;
output   feat2_p_27_ce0;
input  [31:0] feat2_p_27_q0;
output  [12:0] feat2_p_28_address0;
output   feat2_p_28_ce0;
input  [31:0] feat2_p_28_q0;
output  [12:0] feat2_p_29_address0;
output   feat2_p_29_ce0;
input  [31:0] feat2_p_29_q0;
output  [12:0] feat2_p_30_address0;
output   feat2_p_30_ce0;
input  [31:0] feat2_p_30_q0;
output  [12:0] feat2_p_31_address0;
output   feat2_p_31_ce0;
input  [31:0] feat2_p_31_q0;
output  [12:0] feat2_p_32_address0;
output   feat2_p_32_ce0;
input  [31:0] feat2_p_32_q0;
output  [12:0] feat2_p_33_address0;
output   feat2_p_33_ce0;
input  [31:0] feat2_p_33_q0;
output  [12:0] feat2_p_34_address0;
output   feat2_p_34_ce0;
input  [31:0] feat2_p_34_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_10_address0;
output   p_ZZ9cnn_accelE7feat2_p_10_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_10_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_11_address0;
output   p_ZZ9cnn_accelE7feat2_p_11_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_11_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_12_address0;
output   p_ZZ9cnn_accelE7feat2_p_12_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_12_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_13_address0;
output   p_ZZ9cnn_accelE7feat2_p_13_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_13_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_14_address0;
output   p_ZZ9cnn_accelE7feat2_p_14_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_14_q0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_15_address0;
output   p_ZZ9cnn_accelE7feat2_p_15_ce0;
input  [31:0] p_ZZ9cnn_accelE7feat2_p_15_q0;
output  [16:0] vec1_address0;
output   vec1_ce0;
output   vec1_we0;
output  [31:0] vec1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln188_fu_428_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln189_fu_452_p2;
reg   [0:0] icmp_ln189_reg_850;
reg   [0:0] icmp_ln189_reg_850_pp0_iter2_reg;
reg   [0:0] icmp_ln189_reg_850_pp0_iter3_reg;
reg   [0:0] icmp_ln189_reg_850_pp0_iter4_reg;
wire   [0:0] and_ln188_fu_523_p2;
reg   [0:0] and_ln188_reg_865;
reg   [0:0] and_ln188_reg_865_pp0_iter4_reg;
wire   [3:0] trunc_ln190_fu_560_p1;
reg   [3:0] trunc_ln190_reg_876;
reg   [3:0] trunc_ln190_reg_876_pp0_iter4_reg;
wire   [63:0] p_cast_fu_580_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln190_fu_649_p1;
reg   [4:0] m_fu_124;
wire   [4:0] add_ln190_1_fu_564_p2;
wire    ap_loop_init;
reg   [16:0] cnt_1_fu_128;
wire   [16:0] add_ln192_fu_726_p2;
reg   [16:0] add_ln188_134_fu_132;
wire   [16:0] add_ln188_1_fu_738_p2;
reg   [16:0] cnt_fu_136;
wire   [16:0] select_ln189_fu_642_p3;
reg   [16:0] add_ln19036_fu_140;
wire   [16:0] add_ln190_fu_732_p2;
reg   [6:0] j_fu_144;
wire   [6:0] select_ln189_1_fu_548_p3;
reg   [11:0] indvar_flatten117_fu_148;
wire   [11:0] select_ln189_2_fu_476_p3;
reg   [5:0] i_fu_152;
wire   [5:0] select_ln188_4_fu_458_p3;
reg   [16:0] indvars_iv182_fu_156;
wire   [16:0] select_ln188_3_fu_628_p3;
reg   [16:0] indvar_flatten135_fu_160;
wire   [16:0] add_ln188_2_fu_434_p2;
reg    feat2_p_ce0_local;
reg    feat2_p_26_ce0_local;
reg    feat2_p_27_ce0_local;
reg    feat2_p_28_ce0_local;
reg    feat2_p_29_ce0_local;
reg    feat2_p_30_ce0_local;
reg    feat2_p_31_ce0_local;
reg    feat2_p_32_ce0_local;
reg    feat2_p_33_ce0_local;
reg    feat2_p_34_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_10_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_11_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_12_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_13_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_14_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_15_ce0_local;
reg    vec1_we0_local;
wire   [31:0] tmp_7_fu_654_p35;
reg    vec1_ce0_local;
wire   [5:0] add_ln188_fu_446_p2;
wire   [11:0] add_ln189_1_fu_470_p2;
wire   [0:0] icmp_ln190_fu_517_p2;
wire   [0:0] xor_ln188_fu_512_p2;
wire   [6:0] select_ln188_1_fu_505_p3;
wire   [0:0] empty_fu_535_p2;
wire   [6:0] add_ln189_fu_529_p2;
wire   [4:0] m_4_mid2_fu_540_p3;
wire   [12:0] grp_fu_769_p3;
wire   [16:0] select_ln188_2_fu_621_p3;
wire   [16:0] select_ln188_fu_614_p3;
wire   [16:0] cnt_1_mid2_fu_635_p3;
wire   [31:0] tmp_7_fu_654_p33;
wire   [6:0] grp_fu_769_p0;
wire   [5:0] grp_fu_769_p1;
wire   [6:0] grp_fu_769_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] grp_fu_769_p10;
wire   [12:0] grp_fu_769_p20;
wire   [3:0] tmp_7_fu_654_p1;
wire   [3:0] tmp_7_fu_654_p3;
wire   [3:0] tmp_7_fu_654_p5;
wire   [3:0] tmp_7_fu_654_p7;
wire   [3:0] tmp_7_fu_654_p9;
wire   [3:0] tmp_7_fu_654_p11;
wire   [3:0] tmp_7_fu_654_p13;
wire   [3:0] tmp_7_fu_654_p15;
wire  signed [3:0] tmp_7_fu_654_p17;
wire  signed [3:0] tmp_7_fu_654_p19;
wire  signed [3:0] tmp_7_fu_654_p21;
wire  signed [3:0] tmp_7_fu_654_p23;
wire  signed [3:0] tmp_7_fu_654_p25;
wire  signed [3:0] tmp_7_fu_654_p27;
wire  signed [3:0] tmp_7_fu_654_p29;
wire  signed [3:0] tmp_7_fu_654_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 m_fu_124 = 5'd0;
#0 cnt_1_fu_128 = 17'd0;
#0 add_ln188_134_fu_132 = 17'd0;
#0 cnt_fu_136 = 17'd0;
#0 add_ln19036_fu_140 = 17'd0;
#0 j_fu_144 = 7'd0;
#0 indvar_flatten117_fu_148 = 12'd0;
#0 i_fu_152 = 6'd0;
#0 indvars_iv182_fu_156 = 17'd0;
#0 indvar_flatten135_fu_160 = 17'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U136(
    .din0(feat2_p_q0),
    .din1(feat2_p_26_q0),
    .din2(feat2_p_27_q0),
    .din3(feat2_p_28_q0),
    .din4(feat2_p_29_q0),
    .din5(feat2_p_30_q0),
    .din6(feat2_p_31_q0),
    .din7(feat2_p_32_q0),
    .din8(feat2_p_33_q0),
    .din9(feat2_p_34_q0),
    .din10(p_ZZ9cnn_accelE7feat2_p_10_q0),
    .din11(p_ZZ9cnn_accelE7feat2_p_11_q0),
    .din12(p_ZZ9cnn_accelE7feat2_p_12_q0),
    .din13(p_ZZ9cnn_accelE7feat2_p_13_q0),
    .din14(p_ZZ9cnn_accelE7feat2_p_14_q0),
    .din15(p_ZZ9cnn_accelE7feat2_p_15_q0),
    .def(tmp_7_fu_654_p33),
    .sel(trunc_ln190_reg_876_pp0_iter4_reg),
    .dout(tmp_7_fu_654_p35)
);

cnn_accel_mac_muladd_7ns_6ns_7ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 13 ))
mac_muladd_7ns_6ns_7ns_13_4_1_U137(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_769_p0),
    .din1(grp_fu_769_p1),
    .din2(grp_fu_769_p2),
    .ce(1'b1),
    .dout(grp_fu_769_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnt_1_fu_128 <= 17'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            cnt_1_fu_128 <= add_ln192_fu_726_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnt_fu_136 <= 17'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            cnt_fu_136 <= select_ln189_fu_642_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_152 <= 6'd0;
        end else if (((icmp_ln188_fu_428_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_152 <= select_ln188_4_fu_458_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten117_fu_148 <= 12'd0;
        end else if (((icmp_ln188_fu_428_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten117_fu_148 <= select_ln189_2_fu_476_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten135_fu_160 <= 17'd0;
        end else if (((icmp_ln188_fu_428_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten135_fu_160 <= add_ln188_2_fu_434_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvars_iv182_fu_156 <= 17'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            indvars_iv182_fu_156 <= select_ln188_3_fu_628_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            j_fu_144 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            j_fu_144 <= select_ln189_1_fu_548_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m_fu_124 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            m_fu_124 <= add_ln190_1_fu_564_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        add_ln188_134_fu_132 <= add_ln188_1_fu_738_p2;
        add_ln19036_fu_140 <= add_ln190_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln188_reg_865 <= and_ln188_fu_523_p2;
        and_ln188_reg_865_pp0_iter4_reg <= and_ln188_reg_865;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln189_reg_850_pp0_iter2_reg <= icmp_ln189_reg_850;
        icmp_ln189_reg_850_pp0_iter3_reg <= icmp_ln189_reg_850_pp0_iter2_reg;
        icmp_ln189_reg_850_pp0_iter4_reg <= icmp_ln189_reg_850_pp0_iter3_reg;
        trunc_ln190_reg_876 <= trunc_ln190_fu_560_p1;
        trunc_ln190_reg_876_pp0_iter4_reg <= trunc_ln190_reg_876;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln189_reg_850 <= icmp_ln189_fu_452_p2;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_428_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_26_ce0_local = 1'b1;
    end else begin
        feat2_p_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_27_ce0_local = 1'b1;
    end else begin
        feat2_p_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_28_ce0_local = 1'b1;
    end else begin
        feat2_p_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_29_ce0_local = 1'b1;
    end else begin
        feat2_p_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_30_ce0_local = 1'b1;
    end else begin
        feat2_p_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_31_ce0_local = 1'b1;
    end else begin
        feat2_p_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_32_ce0_local = 1'b1;
    end else begin
        feat2_p_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_33_ce0_local = 1'b1;
    end else begin
        feat2_p_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_34_ce0_local = 1'b1;
    end else begin
        feat2_p_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        feat2_p_ce0_local = 1'b1;
    end else begin
        feat2_p_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_10_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_11_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_12_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_13_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_14_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZZ9cnn_accelE7feat2_p_15_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        vec1_ce0_local = 1'b1;
    end else begin
        vec1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        vec1_we0_local = 1'b1;
    end else begin
        vec1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln188_1_fu_738_p2 = (select_ln188_3_fu_628_p3 + 17'd1248);

assign add_ln188_2_fu_434_p2 = (indvar_flatten135_fu_160 + 17'd1);

assign add_ln188_fu_446_p2 = (i_fu_152 + 6'd1);

assign add_ln189_1_fu_470_p2 = (indvar_flatten117_fu_148 + 12'd1);

assign add_ln189_fu_529_p2 = (select_ln188_1_fu_505_p3 + 7'd1);

assign add_ln190_1_fu_564_p2 = (m_4_mid2_fu_540_p3 + 5'd1);

assign add_ln190_fu_732_p2 = (select_ln189_fu_642_p3 + 17'd16);

assign add_ln192_fu_726_p2 = (cnt_1_mid2_fu_635_p3 + 17'd1);

assign and_ln188_fu_523_p2 = (xor_ln188_fu_512_p2 & icmp_ln190_fu_517_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign cnt_1_mid2_fu_635_p3 = ((and_ln188_reg_865_pp0_iter4_reg[0:0] == 1'b1) ? add_ln19036_fu_140 : select_ln188_2_fu_621_p3);

assign empty_fu_535_p2 = (icmp_ln189_reg_850_pp0_iter2_reg | and_ln188_fu_523_p2);

assign feat2_p_26_address0 = p_cast_fu_580_p1;

assign feat2_p_26_ce0 = feat2_p_26_ce0_local;

assign feat2_p_27_address0 = p_cast_fu_580_p1;

assign feat2_p_27_ce0 = feat2_p_27_ce0_local;

assign feat2_p_28_address0 = p_cast_fu_580_p1;

assign feat2_p_28_ce0 = feat2_p_28_ce0_local;

assign feat2_p_29_address0 = p_cast_fu_580_p1;

assign feat2_p_29_ce0 = feat2_p_29_ce0_local;

assign feat2_p_30_address0 = p_cast_fu_580_p1;

assign feat2_p_30_ce0 = feat2_p_30_ce0_local;

assign feat2_p_31_address0 = p_cast_fu_580_p1;

assign feat2_p_31_ce0 = feat2_p_31_ce0_local;

assign feat2_p_32_address0 = p_cast_fu_580_p1;

assign feat2_p_32_ce0 = feat2_p_32_ce0_local;

assign feat2_p_33_address0 = p_cast_fu_580_p1;

assign feat2_p_33_ce0 = feat2_p_33_ce0_local;

assign feat2_p_34_address0 = p_cast_fu_580_p1;

assign feat2_p_34_ce0 = feat2_p_34_ce0_local;

assign feat2_p_address0 = p_cast_fu_580_p1;

assign feat2_p_ce0 = feat2_p_ce0_local;

assign grp_fu_769_p0 = 13'd78;

assign grp_fu_769_p1 = grp_fu_769_p10;

assign grp_fu_769_p10 = select_ln188_4_fu_458_p3;

assign grp_fu_769_p2 = grp_fu_769_p20;

assign grp_fu_769_p20 = select_ln189_1_fu_548_p3;

assign icmp_ln188_fu_428_p2 = ((indvar_flatten135_fu_160 == 17'd72384) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_452_p2 = ((indvar_flatten117_fu_148 == 12'd1248) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_517_p2 = ((m_fu_124 == 5'd16) ? 1'b1 : 1'b0);

assign m_4_mid2_fu_540_p3 = ((empty_fu_535_p2[0:0] == 1'b1) ? 5'd0 : m_fu_124);

assign p_ZZ9cnn_accelE7feat2_p_10_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_10_ce0 = p_ZZ9cnn_accelE7feat2_p_10_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_11_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_11_ce0 = p_ZZ9cnn_accelE7feat2_p_11_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_12_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_12_ce0 = p_ZZ9cnn_accelE7feat2_p_12_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_13_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_13_ce0 = p_ZZ9cnn_accelE7feat2_p_13_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_14_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_14_ce0 = p_ZZ9cnn_accelE7feat2_p_14_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_15_address0 = p_cast_fu_580_p1;

assign p_ZZ9cnn_accelE7feat2_p_15_ce0 = p_ZZ9cnn_accelE7feat2_p_15_ce0_local;

assign p_cast_fu_580_p1 = grp_fu_769_p3;

assign select_ln188_1_fu_505_p3 = ((icmp_ln189_reg_850_pp0_iter2_reg[0:0] == 1'b1) ? 7'd0 : j_fu_144);

assign select_ln188_2_fu_621_p3 = ((icmp_ln189_reg_850_pp0_iter4_reg[0:0] == 1'b1) ? add_ln188_134_fu_132 : cnt_1_fu_128);

assign select_ln188_3_fu_628_p3 = ((icmp_ln189_reg_850_pp0_iter4_reg[0:0] == 1'b1) ? add_ln188_134_fu_132 : indvars_iv182_fu_156);

assign select_ln188_4_fu_458_p3 = ((icmp_ln189_fu_452_p2[0:0] == 1'b1) ? add_ln188_fu_446_p2 : i_fu_152);

assign select_ln188_fu_614_p3 = ((icmp_ln189_reg_850_pp0_iter4_reg[0:0] == 1'b1) ? add_ln188_134_fu_132 : cnt_fu_136);

assign select_ln189_1_fu_548_p3 = ((and_ln188_fu_523_p2[0:0] == 1'b1) ? add_ln189_fu_529_p2 : select_ln188_1_fu_505_p3);

assign select_ln189_2_fu_476_p3 = ((icmp_ln189_fu_452_p2[0:0] == 1'b1) ? 12'd1 : add_ln189_1_fu_470_p2);

assign select_ln189_fu_642_p3 = ((and_ln188_reg_865_pp0_iter4_reg[0:0] == 1'b1) ? add_ln19036_fu_140 : select_ln188_fu_614_p3);

assign tmp_7_fu_654_p33 = 'bx;

assign trunc_ln190_fu_560_p1 = m_4_mid2_fu_540_p3[3:0];

assign vec1_address0 = zext_ln190_fu_649_p1;

assign vec1_ce0 = vec1_ce0_local;

assign vec1_d0 = tmp_7_fu_654_p35;

assign vec1_we0 = vec1_we0_local;

assign xor_ln188_fu_512_p2 = (icmp_ln189_reg_850_pp0_iter2_reg ^ 1'd1);

assign zext_ln190_fu_649_p1 = cnt_1_mid2_fu_635_p3;

endmodule //cnn_accel_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2
