

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Foutmem_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.IMGmem_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_stream_img_fu_112"},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_stream_img_fu_112.grp_stream_img_Pipeline_VITIS_LOOP_35_1_fu_53"},
	{"ID" : "7", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_stream_img_fu_112.grp_stream_img_Pipeline_VITIS_LOOP_35_1_fu_53.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_fc2_fu_121"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv1_stream_fu_129"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv1_stream_fu_129.grp_conv1_stream_Pipeline_PIX_CH_fu_71"},
	{"ID" : "11", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv1_stream_fu_129.grp_conv1_stream_Pipeline_PIX_CH_fu_71.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv1_stream_fu_129.grp_conv1_stream_Pipeline_VITIS_LOOP_82_4_fu_77"},
	{"ID" : "13", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv1_stream_fu_129.grp_conv1_stream_Pipeline_VITIS_LOOP_82_4_fu_77.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool1_stream_fu_135"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool1_stream_fu_135.buf_1_U"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool1_stream_fu_135.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv2_stream_fu_143"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv2_stream_fu_143.grp_conv2_stream_Pipeline_CH2_fu_71"},
	{"ID" : "19", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv2_stream_fu_143.grp_conv2_stream_Pipeline_CH2_fu_71.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv2_stream_fu_143.grp_conv2_stream_Pipeline_VITIS_LOOP_158_4_fu_77"},
	{"ID" : "21", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_conv2_stream_fu_143.grp_conv2_stream_Pipeline_VITIS_LOOP_158_4_fu_77.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool2_stream_fu_149"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool2_stream_fu_149.buf_r_U"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_pool2_stream_fu_149.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_flatten_stream_fu_157"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.grp_flatten_stream_fu_157.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.feat2_p_strm_fifo_U"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.feat2_strm_fifo_U"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.feat1_p_strm_fifo_U"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.feat1_strm_fifo_U"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_U0.img_strm_fifo_U"}]}
set DependenceCheckSize 0
