

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "20", "28", "37", "47", "51", "71", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98"],
		"CDFG" : "cnn_accel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "64570463", "EstimateLatencyMax" : "64570463",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "12", "Name" : "load_img_U0"},
			{"ID" : "14", "Name" : "conv1_U0"},
			{"ID" : "28", "Name" : "conv2_U0"},
			{"ID" : "51", "Name" : "fc1_U0"},
			{"ID" : "71", "Name" : "fc2_U0"}],
		"OutputProcess" : [
			{"ID" : "71", "Name" : "fc2_U0"}],
		"Port" : [
			{"Name" : "IMGmem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "load_img_U0", "Port" : "IMGmem"}]},
			{"Name" : "W1mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "W1mem"}]},
			{"Name" : "B1mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "B1mem"}]},
			{"Name" : "W2mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "W2mem"}]},
			{"Name" : "B2mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "B2mem"}]},
			{"Name" : "W3mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "W3mem"}]},
			{"Name" : "B3mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "B3mem"}]},
			{"Name" : "W4mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "fc2_U0", "Port" : "W4mem"}]},
			{"Name" : "B4mem", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "fc2_U0", "Port" : "B4mem"}]},
			{"Name" : "Foutmem", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "fc2_U0", "Port" : "Foutmem"}]},
			{"Name" : "img_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias2", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC1_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC1_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC2_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC2_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "flag_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "load_img_U0", "Port" : "local_img"},
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "local_img"}]},
			{"Name" : "local_img_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "load_img_U0", "Port" : "local_img_1"},
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "local_img_1"}]},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "feat1"},
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1"}]},
			{"Name" : "feat1_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "feat1_2"},
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_2"}]},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "feat1_3"},
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_3"}]},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "conv1_U0", "Port" : "feat1_4"},
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_4"}]},
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_p"},
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat1_p"}]},
			{"Name" : "feat1_p_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_p_5"},
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat1_p_5"}]},
			{"Name" : "feat1_p_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_p_6"},
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat1_p_6"}]},
			{"Name" : "feat1_p_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "pool1_U0", "Port" : "feat1_p_7"},
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat1_p_7"}]},
			{"Name" : "feat2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat2"},
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2"}]},
			{"Name" : "feat2_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat2_10"},
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_10"}]},
			{"Name" : "feat2_8", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat2_8"},
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_8"}]},
			{"Name" : "feat2_9", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "conv2_U0", "Port" : "feat2_9"},
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_9"}]},
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_p"},
					{"ID" : "47", "SubInstance" : "flatten_U0", "Port" : "feat2_p"}]},
			{"Name" : "feat2_p_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_p_11"},
					{"ID" : "47", "SubInstance" : "flatten_U0", "Port" : "feat2_p_11"}]},
			{"Name" : "feat2_p_12", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_p_12"},
					{"ID" : "47", "SubInstance" : "flatten_U0", "Port" : "feat2_p_12"}]},
			{"Name" : "feat2_p_13", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "pool2_U0", "Port" : "feat2_p_13"},
					{"ID" : "47", "SubInstance" : "flatten_U0", "Port" : "feat2_p_13"}]},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "47", "SubInstance" : "flatten_U0", "Port" : "vec1"},
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "vec1"}]},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array"}]},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array"}]},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array"}]},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "51", "SubInstance" : "fc1_U0", "Port" : "vec2"},
					{"ID" : "71", "SubInstance" : "fc2_U0", "Port" : "vec2"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B1mem_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B2mem_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B3mem_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.B4mem_m_axi_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Foutmem_m_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.IMGmem_m_axi_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.W1mem_m_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.W2mem_m_axi_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.W3mem_m_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.W4mem_m_axi_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.load_img_U0", "Parent" : "0", "Child" : ["13"],
		"CDFG" : "load_img",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "691209", "EstimateLatencyMax" : "691209",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "IMGmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "IMGmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "IMGmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "img_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["14"], "DependentChan" : "79"},
			{"Name" : "local_img_1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["14"], "DependentChan" : "80"}],
		"Loop" : [
			{"Name" : "LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_img_U0.flow_control_loop_delay_pipe_U", "Parent" : "12"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv1_U0", "Parent" : "0", "Child" : ["15", "16", "17", "18", "19"],
		"CDFG" : "conv1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16347889", "EstimateLatencyMax" : "16347889",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "W1mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "W1mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "W1mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "weights1", "Type" : "None", "Direction" : "I"},
			{"Name" : "B1mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "B1mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "B1mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "bias1", "Type" : "None", "Direction" : "I"},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["20"], "DependentChan" : "81"},
			{"Name" : "feat1_2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["20"], "DependentChan" : "82"},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["20"], "DependentChan" : "83"},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["20"], "DependentChan" : "84"},
			{"Name" : "local_img", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["12"], "DependentChan" : "79"},
			{"Name" : "local_img_1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["12"], "DependentChan" : "80"}],
		"Loop" : [
			{"Name" : "CONV1_ROW_CONV1_COL_CONV1_FIL", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "27", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage8", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage8_subdone", "QuitState" : "ap_ST_fsm_pp0_stage8", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage8_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv1_U0.fadd_32ns_32ns_32_5_full_dsp_1_U5", "Parent" : "14"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv1_U0.fmul_32ns_32ns_32_4_max_dsp_1_U6", "Parent" : "14"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv1_U0.fcmp_32ns_32ns_1_2_no_dsp_1_U7", "Parent" : "14"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv1_U0.mac_muladd_9ns_8ns_9ns_17_4_1_U8", "Parent" : "14"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv1_U0.flow_control_loop_pipe_U", "Parent" : "14"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_U0", "Parent" : "0", "Child" : ["21", "22", "23", "24", "25", "26", "27"],
		"CDFG" : "pool1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "454115", "EstimateLatencyMax" : "454115",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["28"], "DependentChan" : "85"},
			{"Name" : "feat1_p_5", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["28"], "DependentChan" : "86"},
			{"Name" : "feat1_p_6", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["28"], "DependentChan" : "87"},
			{"Name" : "feat1_p_7", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["28"], "DependentChan" : "88"},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["14"], "DependentChan" : "81"},
			{"Name" : "feat1_2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["14"], "DependentChan" : "82"},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["14"], "DependentChan" : "83"},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["14"], "DependentChan" : "84"}],
		"Loop" : [
			{"Name" : "POOL1_ROW_POOL1_COL_POOL1_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.fcmp_32ns_32ns_1_2_no_dsp_1_U23", "Parent" : "20"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.sparsemux_9_2_32_1_1_U24", "Parent" : "20"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.sparsemux_9_2_32_1_1_U25", "Parent" : "20"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.mul_8ns_10ns_17_1_1_U26", "Parent" : "20"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.mul_8ns_10ns_17_1_1_U27", "Parent" : "20"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.mac_muladd_8ns_7ns_8ns_15_4_1_U28", "Parent" : "20"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool1_U0.flow_control_loop_delay_pipe_U", "Parent" : "20"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_U0", "Parent" : "0", "Child" : ["29", "30", "31", "32", "33", "34", "35", "36"],
		"CDFG" : "conv2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "21161458", "EstimateLatencyMax" : "21161458",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "W2mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "W2mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "W2mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "weights2", "Type" : "None", "Direction" : "I"},
			{"Name" : "B2mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "B2mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "B2mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "bias2", "Type" : "None", "Direction" : "I"},
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "85"},
			{"Name" : "feat1_p_5", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "86"},
			{"Name" : "feat1_p_6", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "87"},
			{"Name" : "feat1_p_7", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["20"], "DependentChan" : "88"},
			{"Name" : "feat2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["37"], "DependentChan" : "89"},
			{"Name" : "feat2_10", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["37"], "DependentChan" : "90"},
			{"Name" : "feat2_8", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["37"], "DependentChan" : "91"},
			{"Name" : "feat2_9", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["37"], "DependentChan" : "92"}],
		"Loop" : [
			{"Name" : "CONV2_ROW_CONV2_COL_CONV2_FIL", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "72", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage8", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage8_subdone", "QuitState" : "ap_ST_fsm_pp0_stage8", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage8_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.fadd_32ns_32ns_32_5_full_dsp_1_U40", "Parent" : "28"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.fmul_32ns_32ns_32_4_max_dsp_1_U41", "Parent" : "28"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.fcmp_32ns_32ns_1_2_no_dsp_1_U42", "Parent" : "28"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.mul_7ns_9ns_15_1_1_U43", "Parent" : "28"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.mul_7ns_9ns_15_1_1_U44", "Parent" : "28"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.mul_7ns_9ns_15_1_1_U45", "Parent" : "28"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.mac_muladd_8ns_7ns_8ns_15_4_1_U46", "Parent" : "28"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.conv2_U0.flow_control_loop_pipe_U", "Parent" : "28"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool2_U0", "Parent" : "0", "Child" : ["38", "39", "40", "41", "42", "43", "44", "45", "46"],
		"CDFG" : "pool2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "217162", "EstimateLatencyMax" : "217162",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["47"], "DependentChan" : "93"},
			{"Name" : "feat2_p_11", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["47"], "DependentChan" : "94"},
			{"Name" : "feat2_p_12", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["47"], "DependentChan" : "95"},
			{"Name" : "feat2_p_13", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["47"], "DependentChan" : "96"},
			{"Name" : "feat2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["28"], "DependentChan" : "89"},
			{"Name" : "feat2_8", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["28"], "DependentChan" : "91"},
			{"Name" : "feat2_9", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["28"], "DependentChan" : "92"},
			{"Name" : "feat2_10", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["28"], "DependentChan" : "90"}],
		"Loop" : [
			{"Name" : "POOL2_ROW_POOL2_COL_POOL2_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.fcmp_32ns_32ns_1_2_no_dsp_1_U60", "Parent" : "37"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.mul_7ns_9ns_15_1_1_U61", "Parent" : "37"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.mul_7ns_9ns_15_1_1_U62", "Parent" : "37"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.sparsemux_9_2_32_1_1_U63", "Parent" : "37"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.sparsemux_9_2_32_1_1_U64", "Parent" : "37"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.sparsemux_9_2_32_1_1_U65", "Parent" : "37"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.sparsemux_9_2_32_1_1_U66", "Parent" : "37"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.mac_muladd_7ns_6ns_7ns_13_4_1_U67", "Parent" : "37"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pool2_U0.flow_control_loop_pipe_U", "Parent" : "37"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.flatten_U0", "Parent" : "0", "Child" : ["48", "49", "50"],
		"CDFG" : "flatten",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "217155", "EstimateLatencyMax" : "217155",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["37"], "DependentChan" : "93"},
			{"Name" : "feat2_p_11", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["37"], "DependentChan" : "94"},
			{"Name" : "feat2_p_12", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["37"], "DependentChan" : "95"},
			{"Name" : "feat2_p_13", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["37"], "DependentChan" : "96"},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["51"], "DependentChan" : "97"}],
		"Loop" : [
			{"Name" : "FLATTEN_VITIS_LOOP_252_1_VITIS_LOOP_253_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.flatten_U0.sparsemux_9_2_32_1_1_U77", "Parent" : "47"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.flatten_U0.mac_muladd_7ns_6ns_7ns_13_4_1_U78", "Parent" : "47"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.flatten_U0.flow_control_loop_delay_pipe_U", "Parent" : "47"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc1_U0", "Parent" : "0", "Child" : ["52", "69", "70"],
		"CDFG" : "fc1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "25481289", "EstimateLatencyMax" : "25481289",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "W3mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "W3mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "W3mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "FC1_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "B3mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "B3mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "B3mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "FC1_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["47"], "DependentChan" : "97"},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["71"], "DependentChan" : "98"},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "52", "SubInstance" : "grp_generic_tanh_float_s_fu_175", "Port" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "23", "Inst_end_state" : "84"}]},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "52", "SubInstance" : "grp_generic_tanh_float_s_fu_175", "Port" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "23", "Inst_end_state" : "84"}]},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "52", "SubInstance" : "grp_generic_tanh_float_s_fu_175", "Port" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "23", "Inst_end_state" : "84"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_270_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "84", "FirstState" : "ap_ST_fsm_state12", "LastState" : ["ap_ST_fsm_state22"], "QuitState" : ["ap_ST_fsm_state12"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state23"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "FC1_OUT", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "84", "FirstState" : "ap_ST_fsm_state9", "LastState" : ["ap_ST_fsm_state84"], "QuitState" : ["ap_ST_fsm_state9"], "PreState" : ["ap_ST_fsm_state8"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175", "Parent" : "51", "Child" : ["53", "63", "64", "65", "66", "67", "68"],
		"CDFG" : "generic_tanh_float_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "3",
		"VariableLatency" : "0", "ExactLatency" : "61", "EstimateLatencyMin" : "61", "EstimateLatencyMax" : "61",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "t_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array"}]},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array"}]},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array"}]}]},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89", "Parent" : "52", "Child" : ["54", "55", "56", "57", "58", "59", "60", "61", "62"],
		"CDFG" : "exp_generic_double_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "21", "EstimateLatencyMin" : "21", "EstimateLatencyMax" : "21",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"}]},
	{"ID" : "54", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "53"},
	{"ID" : "55", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "53"},
	{"ID" : "56", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "53"},
	{"ID" : "57", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.mul_13s_71s_71_5_0_U84", "Parent" : "53"},
	{"ID" : "58", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.mul_43ns_36ns_79_2_0_U85", "Parent" : "53"},
	{"ID" : "59", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.mul_49ns_44ns_93_2_0_U86", "Parent" : "53"},
	{"ID" : "60", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.mul_50ns_50ns_99_2_0_U87", "Parent" : "53"},
	{"ID" : "61", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.sparsemux_9_3_64_1_0_U88", "Parent" : "53"},
	{"ID" : "62", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.grp_exp_generic_double_s_fu_89.mac_muladd_16s_15ns_19s_31_4_0_U89", "Parent" : "53"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.faddfsub_32ns_32ns_32_5_full_dsp_1_U101", "Parent" : "52"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.fdiv_32ns_32ns_32_12_no_dsp_1_U103", "Parent" : "52"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.fptrunc_64ns_32_2_no_dsp_1_U104", "Parent" : "52"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.fpext_32ns_64_2_no_dsp_1_U105", "Parent" : "52"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.fcmp_32ns_32ns_1_2_no_dsp_1_U106", "Parent" : "52"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc1_U0.grp_generic_tanh_float_s_fu_175.dadd_64ns_64ns_64_5_full_dsp_1_U107", "Parent" : "52"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc1_U0.faddfsub_32ns_32ns_32_5_full_dsp_1_U114", "Parent" : "51"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc1_U0.fmul_32ns_32ns_32_4_max_dsp_1_U115", "Parent" : "51"},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc2_U0", "Parent" : "0", "Child" : ["72", "75", "76", "77", "78"],
		"CDFG" : "fc2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "179", "EstimateLatencyMax" : "179",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "FC2_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "B4mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "B4mem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "B4mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "W4mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "W4mem_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_fc2_Pipeline_FC2_LOOP_fu_149", "Port" : "W4mem", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "FC2_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "Foutmem", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "Foutmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "Foutmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "Foutmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "flag_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["51"], "DependentChan" : "98",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_fc2_Pipeline_FC2_LOOP_fu_149", "Port" : "vec2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]}]},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc2_U0.grp_fc2_Pipeline_FC2_LOOP_fu_149", "Parent" : "71", "Child" : ["73", "74"],
		"CDFG" : "fc2_Pipeline_FC2_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "135", "EstimateLatencyMax" : "135",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc2", "Type" : "None", "Direction" : "I"},
			{"Name" : "W4mem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "W4mem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln286", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc2_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "FC2_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc2_U0.grp_fc2_Pipeline_FC2_LOOP_fu_149.fmul_32ns_32ns_32_4_max_dsp_1_U124", "Parent" : "72"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.fc2_U0.grp_fc2_Pipeline_FC2_LOOP_fu_149.flow_control_loop_pipe_sequential_init_U", "Parent" : "72"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc2_U0.fadd_32ns_32ns_32_5_full_dsp_1_U130", "Parent" : "71"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc2_U0.fdiv_32ns_32ns_32_12_no_dsp_1_U131", "Parent" : "71"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc2_U0.fcmp_32ns_32ns_1_2_no_dsp_1_U132", "Parent" : "71"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.fc2_U0.fexp_32ns_32ns_32_8_full_dsp_1_U133", "Parent" : "71"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_img_U", "Parent" : "0"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_img_1_U", "Parent" : "0"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_U", "Parent" : "0"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_2_U", "Parent" : "0"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_3_U", "Parent" : "0"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_4_U", "Parent" : "0"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_U", "Parent" : "0"},
	{"ID" : "86", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_5_U", "Parent" : "0"},
	{"ID" : "87", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_6_U", "Parent" : "0"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_7_U", "Parent" : "0"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_U", "Parent" : "0"},
	{"ID" : "90", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_10_U", "Parent" : "0"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_8_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_9_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_11_U", "Parent" : "0"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_12_U", "Parent" : "0"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_13_U", "Parent" : "0"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vec1_U", "Parent" : "0"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vec2_U", "Parent" : "0"}]}
