

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "56", "58", "65", "72", "76", "80", "82", "96", "98", "99", "100", "101", "102", "103", "104", "105"],
		"CDFG" : "cnn_accel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "125926547", "EstimateLatencyMax" : "125927699",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991", "Port" : "gmem", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "gmem", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "gmem", "Inst_start_state" : "34", "Inst_end_state" : "35"},
					{"ID" : "80", "SubInstance" : "grp_cnn_accel_Pipeline_VITIS_LOOP_202_3_fu_1233", "Port" : "gmem", "Inst_start_state" : "52", "Inst_end_state" : "53"},
					{"ID" : "96", "SubInstance" : "grp_cnn_accel_Pipeline_FC2_LOOP_fu_1257", "Port" : "gmem", "Inst_start_state" : "65", "Inst_end_state" : "66"}]},
			{"Name" : "img_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights1", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias1", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bias2", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC1_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC1_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC2_W", "Type" : "None", "Direction" : "I"},
			{"Name" : "FC2_B", "Type" : "None", "Direction" : "I"},
			{"Name" : "flag_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctrl", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991", "Port" : "local_img", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "local_img_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991", "Port" : "local_img_1", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "local_img_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991", "Port" : "local_img_2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_3", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_3", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_4", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_4", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_5", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_5", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_6", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_6", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_7", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_7", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_8", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_8", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_8", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_9", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "56", "SubInstance" : "grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Port" : "feat1_9", "Inst_start_state" : "18", "Inst_end_state" : "19"},
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_9", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_10", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_10", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_11", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_11", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_12", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_12", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_12", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_13", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_13", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_13", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_14", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_14", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_14", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_15", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_15", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_15", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat1_p_16", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Port" : "feat1_p_16", "Inst_start_state" : "20", "Inst_end_state" : "21"},
					{"ID" : "72", "SubInstance" : "grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Port" : "feat1_p_16", "Inst_start_state" : "34", "Inst_end_state" : "35"}]},
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_17", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_17", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_18", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_18", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_19", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_19", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_20", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_20", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_21", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_21", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_22", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_22", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_23", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_23", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_24", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_24", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_25", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_25", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_10", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_11", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_12", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_12", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_13", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_13", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_14", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_14", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "p_ZZ9cnn_accelE5feat2_15", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE5feat2_15", "Inst_start_state" : "22", "Inst_end_state" : "39"}]},
			{"Name" : "feat2_p_26", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_26", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_26", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_27", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_27", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_27", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_28", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_28", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_28", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_29", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_29", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_29", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_30", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_30", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_30", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_31", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_31", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_31", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_32", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_32", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_32", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_33", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_33", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_33", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "feat2_p_34", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "feat2_p_34", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "feat2_p_34", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_10", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_10", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_11", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_11", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_12", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_12", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_12", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_13", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_13", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_13", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_14", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_14", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_14", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_15", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Port" : "p_ZZ9cnn_accelE7feat2_p_15", "Inst_start_state" : "22", "Inst_end_state" : "39"},
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "p_ZZ9cnn_accelE7feat2_p_15", "Inst_start_state" : "40", "Inst_end_state" : "41"}]},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "76", "SubInstance" : "grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Port" : "vec1", "Inst_start_state" : "40", "Inst_end_state" : "41"},
					{"ID" : "80", "SubInstance" : "grp_cnn_accel_Pipeline_VITIS_LOOP_202_3_fu_1233", "Port" : "vec1", "Inst_start_state" : "52", "Inst_end_state" : "53"}]},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_generic_tanh_float_s_fu_1245", "Port" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "54", "Inst_end_state" : "55"}]},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_generic_tanh_float_s_fu_1245", "Port" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "54", "Inst_end_state" : "55"}]},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_generic_tanh_float_s_fu_1245", "Port" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "54", "Inst_end_state" : "55"}]},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "96", "SubInstance" : "grp_cnn_accel_Pipeline_FC2_LOOP_fu_1257", "Port" : "vec2", "Inst_start_state" : "65", "Inst_end_state" : "66"}]}],
		"Loop" : [
			{"Name" : "CONV1_COL", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state13", "LastState" : ["ap_ST_fsm_state19"], "QuitState" : ["ap_ST_fsm_state19"], "PreState" : ["ap_ST_fsm_state12"], "PostState" : ["ap_ST_fsm_state12", "ap_ST_fsm_state20"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "CONV1_ROW", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state12", "LastState" : ["ap_ST_fsm_state19"], "QuitState" : ["ap_ST_fsm_state19"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state20"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "CONV2_FIL", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state24", "LastState" : ["ap_ST_fsm_state38"], "QuitState" : ["ap_ST_fsm_state24"], "PreState" : ["ap_ST_fsm_state23"], "PostState" : ["ap_ST_fsm_state23"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "CONV2_COL", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state23", "LastState" : ["ap_ST_fsm_state24"], "QuitState" : ["ap_ST_fsm_state23"], "PreState" : ["ap_ST_fsm_state22"], "PostState" : ["ap_ST_fsm_state22"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "CONV2_ROW", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state22", "LastState" : ["ap_ST_fsm_state23"], "QuitState" : ["ap_ST_fsm_state22"], "PreState" : ["ap_ST_fsm_state21"], "PostState" : ["ap_ST_fsm_state39"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "FC1_OUT", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "90", "FirstState" : "ap_ST_fsm_state42", "LastState" : ["ap_ST_fsm_state55"], "QuitState" : ["ap_ST_fsm_state42"], "PreState" : ["ap_ST_fsm_state41"], "PostState" : ["ap_ST_fsm_state56"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_img_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_img_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_img_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_3_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_4_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_5_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_6_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_7_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_8_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_9_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_10_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_11_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_12_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_13_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_14_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_15_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat1_p_16_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_17_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_18_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_19_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_20_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_21_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_22_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_23_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_24_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_25_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_10_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_11_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_12_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_13_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_14_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE5feat2_15_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_26_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_27_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_28_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_29_U", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_30_U", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_31_U", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_32_U", "Parent" : "0"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_33_U", "Parent" : "0"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.feat2_p_34_U", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_10_U", "Parent" : "0"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_11_U", "Parent" : "0"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_12_U", "Parent" : "0"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_13_U", "Parent" : "0"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_14_U", "Parent" : "0"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ9cnn_accelE7feat2_p_15_U", "Parent" : "0"},
	{"ID" : "52", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vec1_U", "Parent" : "0"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vec2_U", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991", "Parent" : "0", "Child" : ["55"],
		"CDFG" : "cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "230403", "EstimateLatencyMax" : "230403",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln85", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_img_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_img_2", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_LOAD_IMG_ROWS_LOAD_IMG_COLS_LOAD_IMG_CH_fu_991.flow_control_loop_pipe_sequential_init_U", "Parent" : "54"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004", "Parent" : "0", "Child" : ["57"],
		"CDFG" : "cnn_accel_Pipeline_CONV1_FIL",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "293", "EstimateLatencyMax" : "293",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln99", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights1", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_load_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_1_load_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_img_2_load_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_9", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "CONV1_FIL", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "28", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage11", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage11_subdone", "QuitState" : "ap_ST_fsm_pp0_stage11", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage11_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV1_FIL_fu_1004.flow_control_loop_pipe_sequential_init_U", "Parent" : "56"},
	{"ID" : "58", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062", "Parent" : "0", "Child" : ["59", "60", "61", "62", "63", "64"],
		"CDFG" : "cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "302740", "EstimateLatencyMax" : "302740",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat1_p_16", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "POOL1_ROW_POOL1_COL_POOL1_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.sparsemux_17_3_32_1_1_U50", "Parent" : "58"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.sparsemux_17_3_32_1_1_U51", "Parent" : "58"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.mul_8ns_10ns_17_1_1_U52", "Parent" : "58"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.mul_8ns_10ns_17_1_1_U53", "Parent" : "58"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.mac_muladd_8ns_7ns_8ns_15_4_1_U54", "Parent" : "58"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL1_ROW_POOL1_COL_POOL1_CH_fu_1062.flow_control_loop_pipe_sequential_init_U", "Parent" : "58"},
	{"ID" : "65", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098", "Parent" : "0", "Child" : ["66", "67", "68", "69", "70", "71"],
		"CDFG" : "cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "144772", "EstimateLatencyMax" : "144772",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE5feat2_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_32", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_33", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "feat2_p_34", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_15", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "POOL2_ROW_POOL2_COL_POOL2_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.sparsemux_33_4_32_1_1_U96", "Parent" : "65"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.sparsemux_33_4_32_1_1_U97", "Parent" : "65"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.mul_7ns_9ns_15_1_1_U98", "Parent" : "65"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.mul_7ns_9ns_15_1_1_U99", "Parent" : "65"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.mac_muladd_7ns_6ns_7ns_13_4_1_U100", "Parent" : "65"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH_fu_1098.flow_control_loop_pipe_sequential_init_U", "Parent" : "65"},
	{"ID" : "72", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166", "Parent" : "0", "Child" : ["73", "74", "75"],
		"CDFG" : "cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "302", "EstimateLatencyMax" : "302",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "i_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "j_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp_42", "Type" : "None", "Direction" : "I"},
			{"Name" : "weights2", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feat1_p", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat1_p_16", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "CONV2_KR_CONV2_KC_CONV2_CH", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166.sparsemux_17_3_32_1_1_U76", "Parent" : "72"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166.ama_addmuladd_2ns_7ns_8ns_8ns_15_4_1_U77", "Parent" : "72"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_CONV2_KR_CONV2_KC_CONV2_CH_fu_1166.flow_control_loop_pipe_sequential_init_U", "Parent" : "72"},
	{"ID" : "76", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195", "Parent" : "0", "Child" : ["77", "78", "79"],
		"CDFG" : "cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "72389", "EstimateLatencyMax" : "72389",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feat2_p", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_31", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_32", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_33", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "feat2_p_34", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ9cnn_accelE7feat2_p_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195.sparsemux_33_4_32_1_1_U136", "Parent" : "76"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195.mac_muladd_7ns_6ns_7ns_13_4_1_U137", "Parent" : "76"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FLATTEN_VITIS_LOOP_189_1_VITIS_LOOP_190_2_fu_1195.flow_control_loop_pipe_sequential_init_U", "Parent" : "76"},
	{"ID" : "80", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_VITIS_LOOP_202_3_fu_1233", "Parent" : "0", "Child" : ["81"],
		"CDFG" : "cnn_accel_Pipeline_VITIS_LOOP_202_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "289549", "EstimateLatencyMax" : "289549",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_33", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln199", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln201", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "vec1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_202_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage3", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage3_subdone", "QuitState" : "ap_ST_fsm_pp0_stage3", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage3_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_VITIS_LOOP_202_3_fu_1233.flow_control_loop_pipe_sequential_init_U", "Parent" : "80"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245", "Parent" : "0", "Child" : ["83", "93", "94", "95"],
		"CDFG" : "generic_tanh_float_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "38",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "t_in", "Type" : "None", "Direction" : "I"},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "83", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "8", "Inst_end_state" : "18"}]},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "83", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "8", "Inst_end_state" : "18"}]},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "83", "SubInstance" : "grp_exp_generic_double_s_fu_89", "Port" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Inst_start_state" : "8", "Inst_end_state" : "18"}]}]},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89", "Parent" : "82", "Child" : ["84", "85", "86", "87", "88", "89", "90", "91", "92"],
		"CDFG" : "exp_generic_double_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "9", "EstimateLatencyMin" : "9", "EstimateLatencyMax" : "9",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"},
			{"Name" : "table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array", "Type" : "Memory", "Direction" : "I"}]},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "83"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "83"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U", "Parent" : "83"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.mul_13s_71s_71_1_1_U163", "Parent" : "83"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.mul_43ns_36ns_79_1_1_U164", "Parent" : "83"},
	{"ID" : "89", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.mul_49ns_44ns_93_1_1_U165", "Parent" : "83"},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.mul_50ns_50ns_99_1_1_U166", "Parent" : "83"},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.sparsemux_9_3_64_1_1_U167", "Parent" : "83"},
	{"ID" : "92", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.grp_exp_generic_double_s_fu_89.mac_muladd_16s_15ns_19s_31_4_1_U168", "Parent" : "83"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.fptrunc_64ns_32_2_no_dsp_1_U182", "Parent" : "82"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.fpext_32ns_64_1_no_dsp_1_U183", "Parent" : "82"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_generic_tanh_float_s_fu_1245.dadd_64ns_64ns_64_4_full_dsp_1_U185", "Parent" : "82"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FC2_LOOP_fu_1257", "Parent" : "0", "Child" : ["97"],
		"CDFG" : "cnn_accel_Pipeline_FC2_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "133", "EstimateLatencyMax" : "133",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc2", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln212", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc2_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "vec2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "FC2_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage3", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage3_subdone", "QuitState" : "ap_ST_fsm_pp0_stage3", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage3_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "97", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_cnn_accel_Pipeline_FC2_LOOP_fu_1257.flow_control_loop_pipe_sequential_init_U", "Parent" : "96"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "99", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "100", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.faddfsub_32ns_32ns_32_3_full_dsp_1_U197", "Parent" : "0"},
	{"ID" : "101", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fdiv_32ns_32ns_32_8_no_dsp_1_U198", "Parent" : "0"},
	{"ID" : "102", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U199", "Parent" : "0"},
	{"ID" : "103", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fexp_32ns_32ns_32_5_full_dsp_1_U200", "Parent" : "0"},
	{"ID" : "104", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_2_max_dsp_1_U201", "Parent" : "0"},
	{"ID" : "105", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U202", "Parent" : "0"}]}
