// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feat2_p_address0,
        feat2_p_ce0,
        feat2_p_we0,
        feat2_p_d0,
        feat2_address0,
        feat2_ce0,
        feat2_q0,
        feat2_address1,
        feat2_ce1,
        feat2_q1,
        feat2_17_address0,
        feat2_17_ce0,
        feat2_17_q0,
        feat2_17_address1,
        feat2_17_ce1,
        feat2_17_q1,
        feat2_18_address0,
        feat2_18_ce0,
        feat2_18_q0,
        feat2_18_address1,
        feat2_18_ce1,
        feat2_18_q1,
        feat2_19_address0,
        feat2_19_ce0,
        feat2_19_q0,
        feat2_19_address1,
        feat2_19_ce1,
        feat2_19_q1,
        feat2_20_address0,
        feat2_20_ce0,
        feat2_20_q0,
        feat2_20_address1,
        feat2_20_ce1,
        feat2_20_q1,
        feat2_21_address0,
        feat2_21_ce0,
        feat2_21_q0,
        feat2_21_address1,
        feat2_21_ce1,
        feat2_21_q1,
        feat2_22_address0,
        feat2_22_ce0,
        feat2_22_q0,
        feat2_22_address1,
        feat2_22_ce1,
        feat2_22_q1,
        feat2_23_address0,
        feat2_23_ce0,
        feat2_23_q0,
        feat2_23_address1,
        feat2_23_ce1,
        feat2_23_q1,
        feat2_24_address0,
        feat2_24_ce0,
        feat2_24_q0,
        feat2_24_address1,
        feat2_24_ce1,
        feat2_24_q1,
        feat2_25_address0,
        feat2_25_ce0,
        feat2_25_q0,
        feat2_25_address1,
        feat2_25_ce1,
        feat2_25_q1,
        p_ZZ9cnn_accelE5feat2_10_address0,
        p_ZZ9cnn_accelE5feat2_10_ce0,
        p_ZZ9cnn_accelE5feat2_10_q0,
        p_ZZ9cnn_accelE5feat2_10_address1,
        p_ZZ9cnn_accelE5feat2_10_ce1,
        p_ZZ9cnn_accelE5feat2_10_q1,
        p_ZZ9cnn_accelE5feat2_11_address0,
        p_ZZ9cnn_accelE5feat2_11_ce0,
        p_ZZ9cnn_accelE5feat2_11_q0,
        p_ZZ9cnn_accelE5feat2_11_address1,
        p_ZZ9cnn_accelE5feat2_11_ce1,
        p_ZZ9cnn_accelE5feat2_11_q1,
        p_ZZ9cnn_accelE5feat2_12_address0,
        p_ZZ9cnn_accelE5feat2_12_ce0,
        p_ZZ9cnn_accelE5feat2_12_q0,
        p_ZZ9cnn_accelE5feat2_12_address1,
        p_ZZ9cnn_accelE5feat2_12_ce1,
        p_ZZ9cnn_accelE5feat2_12_q1,
        p_ZZ9cnn_accelE5feat2_13_address0,
        p_ZZ9cnn_accelE5feat2_13_ce0,
        p_ZZ9cnn_accelE5feat2_13_q0,
        p_ZZ9cnn_accelE5feat2_13_address1,
        p_ZZ9cnn_accelE5feat2_13_ce1,
        p_ZZ9cnn_accelE5feat2_13_q1,
        p_ZZ9cnn_accelE5feat2_14_address0,
        p_ZZ9cnn_accelE5feat2_14_ce0,
        p_ZZ9cnn_accelE5feat2_14_q0,
        p_ZZ9cnn_accelE5feat2_14_address1,
        p_ZZ9cnn_accelE5feat2_14_ce1,
        p_ZZ9cnn_accelE5feat2_14_q1,
        p_ZZ9cnn_accelE5feat2_15_address0,
        p_ZZ9cnn_accelE5feat2_15_ce0,
        p_ZZ9cnn_accelE5feat2_15_q0,
        p_ZZ9cnn_accelE5feat2_15_address1,
        p_ZZ9cnn_accelE5feat2_15_ce1,
        p_ZZ9cnn_accelE5feat2_15_q1,
        feat2_p_26_address0,
        feat2_p_26_ce0,
        feat2_p_26_we0,
        feat2_p_26_d0,
        feat2_p_27_address0,
        feat2_p_27_ce0,
        feat2_p_27_we0,
        feat2_p_27_d0,
        feat2_p_28_address0,
        feat2_p_28_ce0,
        feat2_p_28_we0,
        feat2_p_28_d0,
        feat2_p_29_address0,
        feat2_p_29_ce0,
        feat2_p_29_we0,
        feat2_p_29_d0,
        feat2_p_30_address0,
        feat2_p_30_ce0,
        feat2_p_30_we0,
        feat2_p_30_d0,
        feat2_p_31_address0,
        feat2_p_31_ce0,
        feat2_p_31_we0,
        feat2_p_31_d0,
        feat2_p_32_address0,
        feat2_p_32_ce0,
        feat2_p_32_we0,
        feat2_p_32_d0,
        feat2_p_33_address0,
        feat2_p_33_ce0,
        feat2_p_33_we0,
        feat2_p_33_d0,
        feat2_p_34_address0,
        feat2_p_34_ce0,
        feat2_p_34_we0,
        feat2_p_34_d0,
        p_ZZ9cnn_accelE7feat2_p_10_address0,
        p_ZZ9cnn_accelE7feat2_p_10_ce0,
        p_ZZ9cnn_accelE7feat2_p_10_we0,
        p_ZZ9cnn_accelE7feat2_p_10_d0,
        p_ZZ9cnn_accelE7feat2_p_11_address0,
        p_ZZ9cnn_accelE7feat2_p_11_ce0,
        p_ZZ9cnn_accelE7feat2_p_11_we0,
        p_ZZ9cnn_accelE7feat2_p_11_d0,
        p_ZZ9cnn_accelE7feat2_p_12_address0,
        p_ZZ9cnn_accelE7feat2_p_12_ce0,
        p_ZZ9cnn_accelE7feat2_p_12_we0,
        p_ZZ9cnn_accelE7feat2_p_12_d0,
        p_ZZ9cnn_accelE7feat2_p_13_address0,
        p_ZZ9cnn_accelE7feat2_p_13_ce0,
        p_ZZ9cnn_accelE7feat2_p_13_we0,
        p_ZZ9cnn_accelE7feat2_p_13_d0,
        p_ZZ9cnn_accelE7feat2_p_14_address0,
        p_ZZ9cnn_accelE7feat2_p_14_ce0,
        p_ZZ9cnn_accelE7feat2_p_14_we0,
        p_ZZ9cnn_accelE7feat2_p_14_d0,
        p_ZZ9cnn_accelE7feat2_p_15_address0,
        p_ZZ9cnn_accelE7feat2_p_15_ce0,
        p_ZZ9cnn_accelE7feat2_p_15_we0,
        p_ZZ9cnn_accelE7feat2_p_15_d0,
        grp_fu_1278_p_din0,
        grp_fu_1278_p_din1,
        grp_fu_1278_p_opcode,
        grp_fu_1278_p_dout0,
        grp_fu_1278_p_ce,
        grp_fu_2863_p_din0,
        grp_fu_2863_p_din1,
        grp_fu_2863_p_opcode,
        grp_fu_2863_p_dout0,
        grp_fu_2863_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] feat2_p_address0;
output   feat2_p_ce0;
output   feat2_p_we0;
output  [31:0] feat2_p_d0;
output  [14:0] feat2_address0;
output   feat2_ce0;
input  [31:0] feat2_q0;
output  [14:0] feat2_address1;
output   feat2_ce1;
input  [31:0] feat2_q1;
output  [14:0] feat2_17_address0;
output   feat2_17_ce0;
input  [31:0] feat2_17_q0;
output  [14:0] feat2_17_address1;
output   feat2_17_ce1;
input  [31:0] feat2_17_q1;
output  [14:0] feat2_18_address0;
output   feat2_18_ce0;
input  [31:0] feat2_18_q0;
output  [14:0] feat2_18_address1;
output   feat2_18_ce1;
input  [31:0] feat2_18_q1;
output  [14:0] feat2_19_address0;
output   feat2_19_ce0;
input  [31:0] feat2_19_q0;
output  [14:0] feat2_19_address1;
output   feat2_19_ce1;
input  [31:0] feat2_19_q1;
output  [14:0] feat2_20_address0;
output   feat2_20_ce0;
input  [31:0] feat2_20_q0;
output  [14:0] feat2_20_address1;
output   feat2_20_ce1;
input  [31:0] feat2_20_q1;
output  [14:0] feat2_21_address0;
output   feat2_21_ce0;
input  [31:0] feat2_21_q0;
output  [14:0] feat2_21_address1;
output   feat2_21_ce1;
input  [31:0] feat2_21_q1;
output  [14:0] feat2_22_address0;
output   feat2_22_ce0;
input  [31:0] feat2_22_q0;
output  [14:0] feat2_22_address1;
output   feat2_22_ce1;
input  [31:0] feat2_22_q1;
output  [14:0] feat2_23_address0;
output   feat2_23_ce0;
input  [31:0] feat2_23_q0;
output  [14:0] feat2_23_address1;
output   feat2_23_ce1;
input  [31:0] feat2_23_q1;
output  [14:0] feat2_24_address0;
output   feat2_24_ce0;
input  [31:0] feat2_24_q0;
output  [14:0] feat2_24_address1;
output   feat2_24_ce1;
input  [31:0] feat2_24_q1;
output  [14:0] feat2_25_address0;
output   feat2_25_ce0;
input  [31:0] feat2_25_q0;
output  [14:0] feat2_25_address1;
output   feat2_25_ce1;
input  [31:0] feat2_25_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_10_address0;
output   p_ZZ9cnn_accelE5feat2_10_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_10_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_10_address1;
output   p_ZZ9cnn_accelE5feat2_10_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_10_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_11_address0;
output   p_ZZ9cnn_accelE5feat2_11_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_11_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_11_address1;
output   p_ZZ9cnn_accelE5feat2_11_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_11_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_12_address0;
output   p_ZZ9cnn_accelE5feat2_12_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_12_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_12_address1;
output   p_ZZ9cnn_accelE5feat2_12_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_12_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_13_address0;
output   p_ZZ9cnn_accelE5feat2_13_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_13_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_13_address1;
output   p_ZZ9cnn_accelE5feat2_13_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_13_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_14_address0;
output   p_ZZ9cnn_accelE5feat2_14_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_14_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_14_address1;
output   p_ZZ9cnn_accelE5feat2_14_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_14_q1;
output  [14:0] p_ZZ9cnn_accelE5feat2_15_address0;
output   p_ZZ9cnn_accelE5feat2_15_ce0;
input  [31:0] p_ZZ9cnn_accelE5feat2_15_q0;
output  [14:0] p_ZZ9cnn_accelE5feat2_15_address1;
output   p_ZZ9cnn_accelE5feat2_15_ce1;
input  [31:0] p_ZZ9cnn_accelE5feat2_15_q1;
output  [12:0] feat2_p_26_address0;
output   feat2_p_26_ce0;
output   feat2_p_26_we0;
output  [31:0] feat2_p_26_d0;
output  [12:0] feat2_p_27_address0;
output   feat2_p_27_ce0;
output   feat2_p_27_we0;
output  [31:0] feat2_p_27_d0;
output  [12:0] feat2_p_28_address0;
output   feat2_p_28_ce0;
output   feat2_p_28_we0;
output  [31:0] feat2_p_28_d0;
output  [12:0] feat2_p_29_address0;
output   feat2_p_29_ce0;
output   feat2_p_29_we0;
output  [31:0] feat2_p_29_d0;
output  [12:0] feat2_p_30_address0;
output   feat2_p_30_ce0;
output   feat2_p_30_we0;
output  [31:0] feat2_p_30_d0;
output  [12:0] feat2_p_31_address0;
output   feat2_p_31_ce0;
output   feat2_p_31_we0;
output  [31:0] feat2_p_31_d0;
output  [12:0] feat2_p_32_address0;
output   feat2_p_32_ce0;
output   feat2_p_32_we0;
output  [31:0] feat2_p_32_d0;
output  [12:0] feat2_p_33_address0;
output   feat2_p_33_ce0;
output   feat2_p_33_we0;
output  [31:0] feat2_p_33_d0;
output  [12:0] feat2_p_34_address0;
output   feat2_p_34_ce0;
output   feat2_p_34_we0;
output  [31:0] feat2_p_34_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_10_address0;
output   p_ZZ9cnn_accelE7feat2_p_10_ce0;
output   p_ZZ9cnn_accelE7feat2_p_10_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_10_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_11_address0;
output   p_ZZ9cnn_accelE7feat2_p_11_ce0;
output   p_ZZ9cnn_accelE7feat2_p_11_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_11_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_12_address0;
output   p_ZZ9cnn_accelE7feat2_p_12_ce0;
output   p_ZZ9cnn_accelE7feat2_p_12_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_12_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_13_address0;
output   p_ZZ9cnn_accelE7feat2_p_13_ce0;
output   p_ZZ9cnn_accelE7feat2_p_13_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_13_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_14_address0;
output   p_ZZ9cnn_accelE7feat2_p_14_ce0;
output   p_ZZ9cnn_accelE7feat2_p_14_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_14_d0;
output  [12:0] p_ZZ9cnn_accelE7feat2_p_15_address0;
output   p_ZZ9cnn_accelE7feat2_p_15_ce0;
output   p_ZZ9cnn_accelE7feat2_p_15_we0;
output  [31:0] p_ZZ9cnn_accelE7feat2_p_15_d0;
output  [31:0] grp_fu_1278_p_din0;
output  [31:0] grp_fu_1278_p_din1;
output  [4:0] grp_fu_1278_p_opcode;
input  [0:0] grp_fu_1278_p_dout0;
output   grp_fu_1278_p_ce;
output  [31:0] grp_fu_2863_p_din0;
output  [31:0] grp_fu_2863_p_din1;
output  [4:0] grp_fu_2863_p_opcode;
input  [0:0] grp_fu_2863_p_dout0;
output   grp_fu_2863_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln168_fu_1235_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [11:0] indvar_flatten97_load_reg_1919;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln168_reg_1924;
wire   [16:0] add_ln168_1_fu_1241_p2;
reg   [16:0] add_ln168_1_reg_1928;
wire   [0:0] icmp_ln170_fu_1262_p2;
reg   [0:0] icmp_ln170_reg_1933;
wire   [5:0] select_ln168_1_fu_1294_p3;
reg   [5:0] select_ln168_1_reg_1938;
wire   [4:0] m_3_mid2_fu_1314_p3;
reg   [4:0] m_3_mid2_reg_1945;
wire   [6:0] select_ln170_fu_1322_p3;
reg   [6:0] select_ln170_reg_1950;
reg   [6:0] select_ln170_reg_1950_pp0_iter1_reg;
wire   [14:0] tmp_39_cast_fu_1356_p1;
reg   [14:0] tmp_39_cast_reg_1956;
wire   [14:0] tmp_40_cast_fu_1394_p1;
reg   [14:0] tmp_40_cast_reg_2041;
wire   [3:0] trunc_ln172_fu_1424_p1;
reg   [3:0] trunc_ln172_reg_2126;
reg   [3:0] trunc_ln172_reg_2126_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_1060_p35;
reg   [31:0] m0_reg_2297;
wire   [31:0] grp_fu_1132_p35;
reg   [31:0] m2_reg_2304;
reg   [31:0] m1_reg_2311;
reg   [31:0] m3_reg_2318;
wire   [31:0] mx_fu_1656_p3;
reg   [31:0] mx_reg_2330;
wire   [31:0] my_fu_1745_p3;
reg   [31:0] my_reg_2337;
wire   [63:0] p_cast1_fu_1366_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] p_cast3_fu_1404_p1;
wire   [63:0] p_cast2_fu_1487_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast4_fu_1512_p1;
wire   [63:0] p_cast_fu_1752_p1;
reg   [4:0] m_fu_168;
wire   [4:0] add_ln172_fu_1532_p2;
wire    ap_loop_init;
reg   [6:0] j_fu_172;
reg   [11:0] indvar_flatten97_fu_176;
wire   [11:0] select_ln170_1_fu_1542_p3;
reg   [5:0] i_fu_180;
reg   [16:0] indvar_flatten110_fu_184;
reg    feat2_ce1_local;
reg   [14:0] feat2_address1_local;
reg    feat2_ce0_local;
reg   [14:0] feat2_address0_local;
reg    feat2_17_ce1_local;
reg   [14:0] feat2_17_address1_local;
reg    feat2_17_ce0_local;
reg   [14:0] feat2_17_address0_local;
reg    feat2_18_ce1_local;
reg   [14:0] feat2_18_address1_local;
reg    feat2_18_ce0_local;
reg   [14:0] feat2_18_address0_local;
reg    feat2_19_ce1_local;
reg   [14:0] feat2_19_address1_local;
reg    feat2_19_ce0_local;
reg   [14:0] feat2_19_address0_local;
reg    feat2_20_ce1_local;
reg   [14:0] feat2_20_address1_local;
reg    feat2_20_ce0_local;
reg   [14:0] feat2_20_address0_local;
reg    feat2_21_ce1_local;
reg   [14:0] feat2_21_address1_local;
reg    feat2_21_ce0_local;
reg   [14:0] feat2_21_address0_local;
reg    feat2_22_ce1_local;
reg   [14:0] feat2_22_address1_local;
reg    feat2_22_ce0_local;
reg   [14:0] feat2_22_address0_local;
reg    feat2_23_ce1_local;
reg   [14:0] feat2_23_address1_local;
reg    feat2_23_ce0_local;
reg   [14:0] feat2_23_address0_local;
reg    feat2_24_ce1_local;
reg   [14:0] feat2_24_address1_local;
reg    feat2_24_ce0_local;
reg   [14:0] feat2_24_address0_local;
reg    feat2_25_ce1_local;
reg   [14:0] feat2_25_address1_local;
reg    feat2_25_ce0_local;
reg   [14:0] feat2_25_address0_local;
reg    p_ZZ9cnn_accelE5feat2_10_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_10_address1_local;
reg    p_ZZ9cnn_accelE5feat2_10_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_10_address0_local;
reg    p_ZZ9cnn_accelE5feat2_11_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_11_address1_local;
reg    p_ZZ9cnn_accelE5feat2_11_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_11_address0_local;
reg    p_ZZ9cnn_accelE5feat2_12_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_12_address1_local;
reg    p_ZZ9cnn_accelE5feat2_12_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_12_address0_local;
reg    p_ZZ9cnn_accelE5feat2_13_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_13_address1_local;
reg    p_ZZ9cnn_accelE5feat2_13_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_13_address0_local;
reg    p_ZZ9cnn_accelE5feat2_14_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_14_address1_local;
reg    p_ZZ9cnn_accelE5feat2_14_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_14_address0_local;
reg    p_ZZ9cnn_accelE5feat2_15_ce1_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_15_address1_local;
reg    p_ZZ9cnn_accelE5feat2_15_ce0_local;
reg   [14:0] p_ZZ9cnn_accelE5feat2_15_address0_local;
reg    p_ZZ9cnn_accelE7feat2_p_14_we0_local;
wire   [31:0] select_ln180_fu_1853_p3;
reg    p_ZZ9cnn_accelE7feat2_p_14_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_13_we0_local;
reg    p_ZZ9cnn_accelE7feat2_p_13_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_12_we0_local;
reg    p_ZZ9cnn_accelE7feat2_p_12_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_11_we0_local;
reg    p_ZZ9cnn_accelE7feat2_p_11_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_10_we0_local;
reg    p_ZZ9cnn_accelE7feat2_p_10_ce0_local;
reg    feat2_p_34_we0_local;
reg    feat2_p_34_ce0_local;
reg    feat2_p_33_we0_local;
reg    feat2_p_33_ce0_local;
reg    feat2_p_32_we0_local;
reg    feat2_p_32_ce0_local;
reg    feat2_p_31_we0_local;
reg    feat2_p_31_ce0_local;
reg    feat2_p_30_we0_local;
reg    feat2_p_30_ce0_local;
reg    feat2_p_29_we0_local;
reg    feat2_p_29_ce0_local;
reg    feat2_p_28_we0_local;
reg    feat2_p_28_ce0_local;
reg    feat2_p_27_we0_local;
reg    feat2_p_27_ce0_local;
reg    feat2_p_26_we0_local;
reg    feat2_p_26_ce0_local;
reg    feat2_p_we0_local;
reg    feat2_p_ce0_local;
reg    p_ZZ9cnn_accelE7feat2_p_15_we0_local;
reg    p_ZZ9cnn_accelE7feat2_p_15_ce0_local;
reg   [31:0] grp_fu_1052_p0;
reg   [31:0] grp_fu_1052_p1;
wire   [31:0] grp_fu_1060_p33;
wire   [31:0] grp_fu_1132_p33;
wire   [0:0] icmp_ln172_fu_1282_p2;
wire   [0:0] xor_ln168_fu_1276_p2;
wire   [5:0] add_ln168_fu_1256_p2;
wire   [6:0] select_ln168_fu_1268_p3;
wire   [0:0] and_ln168_fu_1288_p2;
wire   [0:0] empty_fu_1308_p2;
wire   [6:0] add_ln170_fu_1302_p2;
wire   [6:0] tmp_s_fu_1330_p3;
wire   [6:0] empty_59_fu_1342_p0;
wire   [8:0] empty_59_fu_1342_p1;
wire   [7:0] tmp_3_fu_1348_p3;
wire   [14:0] empty_59_fu_1342_p2;
wire   [14:0] empty_62_fu_1360_p2;
wire   [7:0] tmp_4_fu_1386_p3;
wire   [14:0] empty_64_fu_1398_p2;
wire   [6:0] tmp_2_fu_1465_p3;
wire   [6:0] empty_60_fu_1476_p0;
wire   [8:0] empty_60_fu_1476_p1;
wire   [14:0] empty_60_fu_1476_p2;
wire   [14:0] empty_63_fu_1482_p2;
wire   [14:0] empty_65_fu_1507_p2;
wire   [11:0] add_ln170_1_fu_1537_p2;
wire   [31:0] bitcast_ln178_fu_1574_p1;
wire   [31:0] bitcast_ln178_1_fu_1591_p1;
wire   [7:0] tmp_5_fu_1577_p4;
wire   [22:0] trunc_ln178_fu_1587_p1;
wire   [0:0] icmp_ln178_1_fu_1614_p2;
wire   [0:0] icmp_ln178_fu_1608_p2;
wire   [7:0] tmp_6_fu_1594_p4;
wire   [22:0] trunc_ln178_1_fu_1604_p1;
wire   [0:0] icmp_ln178_3_fu_1632_p2;
wire   [0:0] icmp_ln178_2_fu_1626_p2;
wire   [0:0] or_ln178_fu_1620_p2;
wire   [0:0] or_ln178_1_fu_1638_p2;
wire   [0:0] and_ln178_fu_1644_p2;
wire   [0:0] and_ln178_1_fu_1650_p2;
wire   [31:0] bitcast_ln179_fu_1663_p1;
wire   [31:0] bitcast_ln179_1_fu_1680_p1;
wire   [7:0] tmp_8_fu_1666_p4;
wire   [22:0] trunc_ln179_fu_1676_p1;
wire   [0:0] icmp_ln179_1_fu_1703_p2;
wire   [0:0] icmp_ln179_fu_1697_p2;
wire   [7:0] tmp_9_fu_1683_p4;
wire   [22:0] trunc_ln179_1_fu_1693_p1;
wire   [0:0] icmp_ln179_3_fu_1721_p2;
wire   [0:0] icmp_ln179_2_fu_1715_p2;
wire   [0:0] or_ln179_fu_1709_p2;
wire   [0:0] or_ln179_1_fu_1727_p2;
wire   [0:0] and_ln179_fu_1733_p2;
wire   [0:0] and_ln179_1_fu_1739_p2;
wire   [12:0] grp_fu_1875_p3;
wire   [31:0] bitcast_ln180_fu_1771_p1;
wire   [31:0] bitcast_ln180_1_fu_1788_p1;
wire   [7:0] tmp_11_fu_1774_p4;
wire   [22:0] trunc_ln180_fu_1784_p1;
wire   [0:0] icmp_ln180_2_fu_1811_p2;
wire   [0:0] icmp_ln180_1_fu_1805_p2;
wire   [7:0] tmp_12_fu_1791_p4;
wire   [22:0] trunc_ln180_1_fu_1801_p1;
wire   [0:0] icmp_ln180_4_fu_1829_p2;
wire   [0:0] icmp_ln180_3_fu_1823_p2;
wire   [0:0] or_ln180_fu_1817_p2;
wire   [0:0] or_ln180_1_fu_1835_p2;
wire   [0:0] and_ln180_fu_1841_p2;
wire   [0:0] and_ln180_1_fu_1847_p2;
wire   [6:0] grp_fu_1875_p0;
wire   [5:0] grp_fu_1875_p1;
wire   [6:0] grp_fu_1875_p2;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] empty_59_fu_1342_p00;
wire   [14:0] empty_60_fu_1476_p00;
wire   [12:0] grp_fu_1875_p10;
wire   [12:0] grp_fu_1875_p20;
wire   [3:0] grp_fu_1060_p1;
wire   [3:0] grp_fu_1060_p3;
wire   [3:0] grp_fu_1060_p5;
wire   [3:0] grp_fu_1060_p7;
wire   [3:0] grp_fu_1060_p9;
wire   [3:0] grp_fu_1060_p11;
wire   [3:0] grp_fu_1060_p13;
wire   [3:0] grp_fu_1060_p15;
wire  signed [3:0] grp_fu_1060_p17;
wire  signed [3:0] grp_fu_1060_p19;
wire  signed [3:0] grp_fu_1060_p21;
wire  signed [3:0] grp_fu_1060_p23;
wire  signed [3:0] grp_fu_1060_p25;
wire  signed [3:0] grp_fu_1060_p27;
wire  signed [3:0] grp_fu_1060_p29;
wire  signed [3:0] grp_fu_1060_p31;
wire   [3:0] grp_fu_1132_p1;
wire   [3:0] grp_fu_1132_p3;
wire   [3:0] grp_fu_1132_p5;
wire   [3:0] grp_fu_1132_p7;
wire   [3:0] grp_fu_1132_p9;
wire   [3:0] grp_fu_1132_p11;
wire   [3:0] grp_fu_1132_p13;
wire   [3:0] grp_fu_1132_p15;
wire  signed [3:0] grp_fu_1132_p17;
wire  signed [3:0] grp_fu_1132_p19;
wire  signed [3:0] grp_fu_1132_p21;
wire  signed [3:0] grp_fu_1132_p23;
wire  signed [3:0] grp_fu_1132_p25;
wire  signed [3:0] grp_fu_1132_p27;
wire  signed [3:0] grp_fu_1132_p29;
wire  signed [3:0] grp_fu_1132_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 m_fu_168 = 5'd0;
#0 j_fu_172 = 7'd0;
#0 indvar_flatten97_fu_176 = 12'd0;
#0 i_fu_180 = 6'd0;
#0 indvar_flatten110_fu_184 = 17'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U96(
    .din0(feat2_q1),
    .din1(feat2_17_q1),
    .din2(feat2_18_q1),
    .din3(feat2_19_q1),
    .din4(feat2_20_q1),
    .din5(feat2_21_q1),
    .din6(feat2_22_q1),
    .din7(feat2_23_q1),
    .din8(feat2_24_q1),
    .din9(feat2_25_q1),
    .din10(p_ZZ9cnn_accelE5feat2_10_q1),
    .din11(p_ZZ9cnn_accelE5feat2_11_q1),
    .din12(p_ZZ9cnn_accelE5feat2_12_q1),
    .din13(p_ZZ9cnn_accelE5feat2_13_q1),
    .din14(p_ZZ9cnn_accelE5feat2_14_q1),
    .din15(p_ZZ9cnn_accelE5feat2_15_q1),
    .def(grp_fu_1060_p33),
    .sel(trunc_ln172_reg_2126),
    .dout(grp_fu_1060_p35)
);

(* dissolve_hierarchy = "yes" *) cnn_accel_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U97(
    .din0(feat2_q0),
    .din1(feat2_17_q0),
    .din2(feat2_18_q0),
    .din3(feat2_19_q0),
    .din4(feat2_20_q0),
    .din5(feat2_21_q0),
    .din6(feat2_22_q0),
    .din7(feat2_23_q0),
    .din8(feat2_24_q0),
    .din9(feat2_25_q0),
    .din10(p_ZZ9cnn_accelE5feat2_10_q0),
    .din11(p_ZZ9cnn_accelE5feat2_11_q0),
    .din12(p_ZZ9cnn_accelE5feat2_12_q0),
    .din13(p_ZZ9cnn_accelE5feat2_13_q0),
    .din14(p_ZZ9cnn_accelE5feat2_14_q0),
    .din15(p_ZZ9cnn_accelE5feat2_15_q0),
    .def(grp_fu_1132_p33),
    .sel(trunc_ln172_reg_2126),
    .dout(grp_fu_1132_p35)
);

cnn_accel_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U98(
    .din0(empty_59_fu_1342_p0),
    .din1(empty_59_fu_1342_p1),
    .dout(empty_59_fu_1342_p2)
);

cnn_accel_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U99(
    .din0(empty_60_fu_1476_p0),
    .din1(empty_60_fu_1476_p1),
    .dout(empty_60_fu_1476_p2)
);

cnn_accel_mac_muladd_7ns_6ns_7ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 13 ))
mac_muladd_7ns_6ns_7ns_13_4_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1875_p0),
    .din1(grp_fu_1875_p1),
    .din2(grp_fu_1875_p2),
    .ce(1'b1),
    .dout(grp_fu_1875_p3)
);

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_180 <= 6'd0;
        end else if (((icmp_ln168_reg_1924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_180 <= select_ln168_1_reg_1938;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten110_fu_184 <= 17'd0;
        end else if (((icmp_ln168_reg_1924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten110_fu_184 <= add_ln168_1_reg_1928;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten97_fu_176 <= 12'd0;
        end else if (((icmp_ln168_reg_1924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten97_fu_176 <= select_ln170_1_fu_1542_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_172 <= 7'd0;
        end else if (((icmp_ln168_reg_1924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_172 <= select_ln170_reg_1950;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m_fu_168 <= 5'd0;
        end else if (((icmp_ln168_reg_1924 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            m_fu_168 <= add_ln172_fu_1532_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln168_1_reg_1928 <= add_ln168_1_fu_1241_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln168_reg_1924 <= icmp_ln168_fu_1235_p2;
        icmp_ln170_reg_1933 <= icmp_ln170_fu_1262_p2;
        indvar_flatten97_load_reg_1919 <= indvar_flatten97_fu_176;
        m_3_mid2_reg_1945 <= m_3_mid2_fu_1314_p3;
        select_ln168_1_reg_1938 <= select_ln168_1_fu_1294_p3;
        select_ln170_reg_1950 <= select_ln170_fu_1322_p3;
        select_ln170_reg_1950_pp0_iter1_reg <= select_ln170_reg_1950;
        tmp_39_cast_reg_1956[7 : 1] <= tmp_39_cast_fu_1356_p1[7 : 1];
        tmp_40_cast_reg_2041[7 : 1] <= tmp_40_cast_fu_1394_p1[7 : 1];
        trunc_ln172_reg_2126 <= trunc_ln172_fu_1424_p1;
        trunc_ln172_reg_2126_pp0_iter1_reg <= trunc_ln172_reg_2126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_reg_2297 <= grp_fu_1060_p35;
        m2_reg_2304 <= grp_fu_1132_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m1_reg_2311 <= grp_fu_1060_p35;
        m3_reg_2318 <= grp_fu_1132_p35;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mx_reg_2330 <= mx_fu_1656_p3;
        my_reg_2337 <= my_fu_1745_p3;
    end
end

always @ (*) begin
    if (((icmp_ln168_fu_1235_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_17_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_17_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_17_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_17_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_17_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_17_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_17_ce0_local = 1'b1;
    end else begin
        feat2_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_17_ce1_local = 1'b1;
    end else begin
        feat2_17_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_18_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_18_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_18_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_18_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_18_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_18_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_18_ce0_local = 1'b1;
    end else begin
        feat2_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_18_ce1_local = 1'b1;
    end else begin
        feat2_18_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_19_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_19_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_19_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_19_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_19_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_19_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_19_ce0_local = 1'b1;
    end else begin
        feat2_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_19_ce1_local = 1'b1;
    end else begin
        feat2_19_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_20_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_20_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_20_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_20_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_20_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_20_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_20_ce0_local = 1'b1;
    end else begin
        feat2_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_20_ce1_local = 1'b1;
    end else begin
        feat2_20_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_21_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_21_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_21_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_21_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_21_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_21_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_21_ce0_local = 1'b1;
    end else begin
        feat2_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_21_ce1_local = 1'b1;
    end else begin
        feat2_21_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_22_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_22_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_22_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_22_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_22_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_22_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_22_ce0_local = 1'b1;
    end else begin
        feat2_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_22_ce1_local = 1'b1;
    end else begin
        feat2_22_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_23_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_23_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_23_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_23_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_23_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_23_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_23_ce0_local = 1'b1;
    end else begin
        feat2_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_23_ce1_local = 1'b1;
    end else begin
        feat2_23_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_24_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_24_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_24_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_24_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_24_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_24_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_24_ce0_local = 1'b1;
    end else begin
        feat2_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_24_ce1_local = 1'b1;
    end else begin
        feat2_24_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_25_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_25_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_25_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_25_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_25_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_25_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_25_ce0_local = 1'b1;
    end else begin
        feat2_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_25_ce1_local = 1'b1;
    end else begin
        feat2_25_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_address0_local = p_cast3_fu_1404_p1;
    end else begin
        feat2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feat2_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_address1_local = p_cast1_fu_1366_p1;
    end else begin
        feat2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_ce0_local = 1'b1;
    end else begin
        feat2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        feat2_ce1_local = 1'b1;
    end else begin
        feat2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_26_ce0_local = 1'b1;
    end else begin
        feat2_p_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_26_we0_local = 1'b1;
    end else begin
        feat2_p_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_27_ce0_local = 1'b1;
    end else begin
        feat2_p_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_27_we0_local = 1'b1;
    end else begin
        feat2_p_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_28_ce0_local = 1'b1;
    end else begin
        feat2_p_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_28_we0_local = 1'b1;
    end else begin
        feat2_p_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_29_ce0_local = 1'b1;
    end else begin
        feat2_p_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_29_we0_local = 1'b1;
    end else begin
        feat2_p_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_30_ce0_local = 1'b1;
    end else begin
        feat2_p_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_30_we0_local = 1'b1;
    end else begin
        feat2_p_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_31_ce0_local = 1'b1;
    end else begin
        feat2_p_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_31_we0_local = 1'b1;
    end else begin
        feat2_p_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_32_ce0_local = 1'b1;
    end else begin
        feat2_p_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_32_we0_local = 1'b1;
    end else begin
        feat2_p_32_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_33_ce0_local = 1'b1;
    end else begin
        feat2_p_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd8) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_33_we0_local = 1'b1;
    end else begin
        feat2_p_33_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_34_ce0_local = 1'b1;
    end else begin
        feat2_p_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_34_we0_local = 1'b1;
    end else begin
        feat2_p_34_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_ce0_local = 1'b1;
    end else begin
        feat2_p_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        feat2_p_we0_local = 1'b1;
    end else begin
        feat2_p_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1052_p0 = mx_fu_1656_p3;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_1052_p0 = m0_reg_2297;
    end else begin
        grp_fu_1052_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1052_p1 = my_fu_1745_p3;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_1052_p1 = grp_fu_1060_p35;
    end else begin
        grp_fu_1052_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_10_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_10_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_10_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_10_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_10_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_10_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_10_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_10_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_11_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_11_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_11_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_11_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_11_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_11_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_11_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_11_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_12_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_12_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_12_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_12_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_12_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_12_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_12_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_12_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_13_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_13_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_13_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_13_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_13_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_13_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_13_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_13_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_14_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_14_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_14_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_14_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_14_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_14_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_14_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_14_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_15_address0_local = p_cast4_fu_1512_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_15_address0_local = p_cast3_fu_1404_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_15_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZ9cnn_accelE5feat2_15_address1_local = p_cast2_fu_1487_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE5feat2_15_address1_local = p_cast1_fu_1366_p1;
    end else begin
        p_ZZ9cnn_accelE5feat2_15_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_15_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZZ9cnn_accelE5feat2_15_ce1_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE5feat2_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_10_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd10) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_10_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_11_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_11_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_12_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd12) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_12_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_13_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd13) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_13_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_14_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd14) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_14_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_15_ce0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (trunc_ln172_reg_2126_pp0_iter1_reg == 4'd15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ9cnn_accelE7feat2_p_15_we0_local = 1'b1;
    end else begin
        p_ZZ9cnn_accelE7feat2_p_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln168_1_fu_1241_p2 = (indvar_flatten110_fu_184 + 17'd1);

assign add_ln168_fu_1256_p2 = (i_fu_180 + 6'd1);

assign add_ln170_1_fu_1537_p2 = (indvar_flatten97_load_reg_1919 + 12'd1);

assign add_ln170_fu_1302_p2 = (select_ln168_fu_1268_p3 + 7'd1);

assign add_ln172_fu_1532_p2 = (m_3_mid2_reg_1945 + 5'd1);

assign and_ln168_fu_1288_p2 = (xor_ln168_fu_1276_p2 & icmp_ln172_fu_1282_p2);

assign and_ln178_1_fu_1650_p2 = (grp_fu_1278_p_dout0 & and_ln178_fu_1644_p2);

assign and_ln178_fu_1644_p2 = (or_ln178_fu_1620_p2 & or_ln178_1_fu_1638_p2);

assign and_ln179_1_fu_1739_p2 = (grp_fu_2863_p_dout0 & and_ln179_fu_1733_p2);

assign and_ln179_fu_1733_p2 = (or_ln179_fu_1709_p2 & or_ln179_1_fu_1727_p2);

assign and_ln180_1_fu_1847_p2 = (grp_fu_1278_p_dout0 & and_ln180_fu_1841_p2);

assign and_ln180_fu_1841_p2 = (or_ln180_fu_1817_p2 & or_ln180_1_fu_1835_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bitcast_ln178_1_fu_1591_p1 = m1_reg_2311;

assign bitcast_ln178_fu_1574_p1 = m0_reg_2297;

assign bitcast_ln179_1_fu_1680_p1 = m3_reg_2318;

assign bitcast_ln179_fu_1663_p1 = m2_reg_2304;

assign bitcast_ln180_1_fu_1788_p1 = my_reg_2337;

assign bitcast_ln180_fu_1771_p1 = mx_reg_2330;

assign empty_59_fu_1342_p0 = empty_59_fu_1342_p00;

assign empty_59_fu_1342_p00 = tmp_s_fu_1330_p3;

assign empty_59_fu_1342_p1 = 15'd157;

assign empty_60_fu_1476_p0 = empty_60_fu_1476_p00;

assign empty_60_fu_1476_p00 = tmp_2_fu_1465_p3;

assign empty_60_fu_1476_p1 = 15'd157;

assign empty_62_fu_1360_p2 = (empty_59_fu_1342_p2 + tmp_39_cast_fu_1356_p1);

assign empty_63_fu_1482_p2 = (empty_60_fu_1476_p2 + tmp_39_cast_reg_1956);

assign empty_64_fu_1398_p2 = (empty_59_fu_1342_p2 + tmp_40_cast_fu_1394_p1);

assign empty_65_fu_1507_p2 = (empty_60_fu_1476_p2 + tmp_40_cast_reg_2041);

assign empty_fu_1308_p2 = (icmp_ln170_fu_1262_p2 | and_ln168_fu_1288_p2);

assign feat2_17_address0 = feat2_17_address0_local;

assign feat2_17_address1 = feat2_17_address1_local;

assign feat2_17_ce0 = feat2_17_ce0_local;

assign feat2_17_ce1 = feat2_17_ce1_local;

assign feat2_18_address0 = feat2_18_address0_local;

assign feat2_18_address1 = feat2_18_address1_local;

assign feat2_18_ce0 = feat2_18_ce0_local;

assign feat2_18_ce1 = feat2_18_ce1_local;

assign feat2_19_address0 = feat2_19_address0_local;

assign feat2_19_address1 = feat2_19_address1_local;

assign feat2_19_ce0 = feat2_19_ce0_local;

assign feat2_19_ce1 = feat2_19_ce1_local;

assign feat2_20_address0 = feat2_20_address0_local;

assign feat2_20_address1 = feat2_20_address1_local;

assign feat2_20_ce0 = feat2_20_ce0_local;

assign feat2_20_ce1 = feat2_20_ce1_local;

assign feat2_21_address0 = feat2_21_address0_local;

assign feat2_21_address1 = feat2_21_address1_local;

assign feat2_21_ce0 = feat2_21_ce0_local;

assign feat2_21_ce1 = feat2_21_ce1_local;

assign feat2_22_address0 = feat2_22_address0_local;

assign feat2_22_address1 = feat2_22_address1_local;

assign feat2_22_ce0 = feat2_22_ce0_local;

assign feat2_22_ce1 = feat2_22_ce1_local;

assign feat2_23_address0 = feat2_23_address0_local;

assign feat2_23_address1 = feat2_23_address1_local;

assign feat2_23_ce0 = feat2_23_ce0_local;

assign feat2_23_ce1 = feat2_23_ce1_local;

assign feat2_24_address0 = feat2_24_address0_local;

assign feat2_24_address1 = feat2_24_address1_local;

assign feat2_24_ce0 = feat2_24_ce0_local;

assign feat2_24_ce1 = feat2_24_ce1_local;

assign feat2_25_address0 = feat2_25_address0_local;

assign feat2_25_address1 = feat2_25_address1_local;

assign feat2_25_ce0 = feat2_25_ce0_local;

assign feat2_25_ce1 = feat2_25_ce1_local;

assign feat2_address0 = feat2_address0_local;

assign feat2_address1 = feat2_address1_local;

assign feat2_ce0 = feat2_ce0_local;

assign feat2_ce1 = feat2_ce1_local;

assign feat2_p_26_address0 = p_cast_fu_1752_p1;

assign feat2_p_26_ce0 = feat2_p_26_ce0_local;

assign feat2_p_26_d0 = select_ln180_fu_1853_p3;

assign feat2_p_26_we0 = feat2_p_26_we0_local;

assign feat2_p_27_address0 = p_cast_fu_1752_p1;

assign feat2_p_27_ce0 = feat2_p_27_ce0_local;

assign feat2_p_27_d0 = select_ln180_fu_1853_p3;

assign feat2_p_27_we0 = feat2_p_27_we0_local;

assign feat2_p_28_address0 = p_cast_fu_1752_p1;

assign feat2_p_28_ce0 = feat2_p_28_ce0_local;

assign feat2_p_28_d0 = select_ln180_fu_1853_p3;

assign feat2_p_28_we0 = feat2_p_28_we0_local;

assign feat2_p_29_address0 = p_cast_fu_1752_p1;

assign feat2_p_29_ce0 = feat2_p_29_ce0_local;

assign feat2_p_29_d0 = select_ln180_fu_1853_p3;

assign feat2_p_29_we0 = feat2_p_29_we0_local;

assign feat2_p_30_address0 = p_cast_fu_1752_p1;

assign feat2_p_30_ce0 = feat2_p_30_ce0_local;

assign feat2_p_30_d0 = select_ln180_fu_1853_p3;

assign feat2_p_30_we0 = feat2_p_30_we0_local;

assign feat2_p_31_address0 = p_cast_fu_1752_p1;

assign feat2_p_31_ce0 = feat2_p_31_ce0_local;

assign feat2_p_31_d0 = select_ln180_fu_1853_p3;

assign feat2_p_31_we0 = feat2_p_31_we0_local;

assign feat2_p_32_address0 = p_cast_fu_1752_p1;

assign feat2_p_32_ce0 = feat2_p_32_ce0_local;

assign feat2_p_32_d0 = select_ln180_fu_1853_p3;

assign feat2_p_32_we0 = feat2_p_32_we0_local;

assign feat2_p_33_address0 = p_cast_fu_1752_p1;

assign feat2_p_33_ce0 = feat2_p_33_ce0_local;

assign feat2_p_33_d0 = select_ln180_fu_1853_p3;

assign feat2_p_33_we0 = feat2_p_33_we0_local;

assign feat2_p_34_address0 = p_cast_fu_1752_p1;

assign feat2_p_34_ce0 = feat2_p_34_ce0_local;

assign feat2_p_34_d0 = select_ln180_fu_1853_p3;

assign feat2_p_34_we0 = feat2_p_34_we0_local;

assign feat2_p_address0 = p_cast_fu_1752_p1;

assign feat2_p_ce0 = feat2_p_ce0_local;

assign feat2_p_d0 = select_ln180_fu_1853_p3;

assign feat2_p_we0 = feat2_p_we0_local;

assign grp_fu_1060_p33 = 'bx;

assign grp_fu_1132_p33 = 'bx;

assign grp_fu_1278_p_ce = 1'b1;

assign grp_fu_1278_p_din0 = grp_fu_1052_p0;

assign grp_fu_1278_p_din1 = grp_fu_1052_p1;

assign grp_fu_1278_p_opcode = 5'd2;

assign grp_fu_1875_p0 = 13'd78;

assign grp_fu_1875_p1 = grp_fu_1875_p10;

assign grp_fu_1875_p10 = select_ln168_1_reg_1938;

assign grp_fu_1875_p2 = grp_fu_1875_p20;

assign grp_fu_1875_p20 = select_ln170_reg_1950_pp0_iter1_reg;

assign grp_fu_2863_p_ce = 1'b1;

assign grp_fu_2863_p_din0 = m2_reg_2304;

assign grp_fu_2863_p_din1 = grp_fu_1132_p35;

assign grp_fu_2863_p_opcode = 5'd2;

assign icmp_ln168_fu_1235_p2 = ((indvar_flatten110_fu_184 == 17'd72384) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_1262_p2 = ((indvar_flatten97_fu_176 == 12'd1248) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_1282_p2 = ((m_fu_168 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln178_1_fu_1614_p2 = ((trunc_ln178_fu_1587_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln178_2_fu_1626_p2 = ((tmp_6_fu_1594_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln178_3_fu_1632_p2 = ((trunc_ln178_1_fu_1604_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln178_fu_1608_p2 = ((tmp_5_fu_1577_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln179_1_fu_1703_p2 = ((trunc_ln179_fu_1676_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_2_fu_1715_p2 = ((tmp_9_fu_1683_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln179_3_fu_1721_p2 = ((trunc_ln179_1_fu_1693_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_1697_p2 = ((tmp_8_fu_1666_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln180_1_fu_1805_p2 = ((tmp_11_fu_1774_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln180_2_fu_1811_p2 = ((trunc_ln180_fu_1784_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_3_fu_1823_p2 = ((tmp_12_fu_1791_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_1829_p2 = ((trunc_ln180_1_fu_1801_p1 == 23'd0) ? 1'b1 : 1'b0);

assign m_3_mid2_fu_1314_p3 = ((empty_fu_1308_p2[0:0] == 1'b1) ? 5'd0 : m_fu_168);

assign mx_fu_1656_p3 = ((and_ln178_1_fu_1650_p2[0:0] == 1'b1) ? m0_reg_2297 : m1_reg_2311);

assign my_fu_1745_p3 = ((and_ln179_1_fu_1739_p2[0:0] == 1'b1) ? m2_reg_2304 : m3_reg_2318);

assign or_ln178_1_fu_1638_p2 = (icmp_ln178_3_fu_1632_p2 | icmp_ln178_2_fu_1626_p2);

assign or_ln178_fu_1620_p2 = (icmp_ln178_fu_1608_p2 | icmp_ln178_1_fu_1614_p2);

assign or_ln179_1_fu_1727_p2 = (icmp_ln179_3_fu_1721_p2 | icmp_ln179_2_fu_1715_p2);

assign or_ln179_fu_1709_p2 = (icmp_ln179_fu_1697_p2 | icmp_ln179_1_fu_1703_p2);

assign or_ln180_1_fu_1835_p2 = (icmp_ln180_4_fu_1829_p2 | icmp_ln180_3_fu_1823_p2);

assign or_ln180_fu_1817_p2 = (icmp_ln180_2_fu_1811_p2 | icmp_ln180_1_fu_1805_p2);

assign p_ZZ9cnn_accelE5feat2_10_address0 = p_ZZ9cnn_accelE5feat2_10_address0_local;

assign p_ZZ9cnn_accelE5feat2_10_address1 = p_ZZ9cnn_accelE5feat2_10_address1_local;

assign p_ZZ9cnn_accelE5feat2_10_ce0 = p_ZZ9cnn_accelE5feat2_10_ce0_local;

assign p_ZZ9cnn_accelE5feat2_10_ce1 = p_ZZ9cnn_accelE5feat2_10_ce1_local;

assign p_ZZ9cnn_accelE5feat2_11_address0 = p_ZZ9cnn_accelE5feat2_11_address0_local;

assign p_ZZ9cnn_accelE5feat2_11_address1 = p_ZZ9cnn_accelE5feat2_11_address1_local;

assign p_ZZ9cnn_accelE5feat2_11_ce0 = p_ZZ9cnn_accelE5feat2_11_ce0_local;

assign p_ZZ9cnn_accelE5feat2_11_ce1 = p_ZZ9cnn_accelE5feat2_11_ce1_local;

assign p_ZZ9cnn_accelE5feat2_12_address0 = p_ZZ9cnn_accelE5feat2_12_address0_local;

assign p_ZZ9cnn_accelE5feat2_12_address1 = p_ZZ9cnn_accelE5feat2_12_address1_local;

assign p_ZZ9cnn_accelE5feat2_12_ce0 = p_ZZ9cnn_accelE5feat2_12_ce0_local;

assign p_ZZ9cnn_accelE5feat2_12_ce1 = p_ZZ9cnn_accelE5feat2_12_ce1_local;

assign p_ZZ9cnn_accelE5feat2_13_address0 = p_ZZ9cnn_accelE5feat2_13_address0_local;

assign p_ZZ9cnn_accelE5feat2_13_address1 = p_ZZ9cnn_accelE5feat2_13_address1_local;

assign p_ZZ9cnn_accelE5feat2_13_ce0 = p_ZZ9cnn_accelE5feat2_13_ce0_local;

assign p_ZZ9cnn_accelE5feat2_13_ce1 = p_ZZ9cnn_accelE5feat2_13_ce1_local;

assign p_ZZ9cnn_accelE5feat2_14_address0 = p_ZZ9cnn_accelE5feat2_14_address0_local;

assign p_ZZ9cnn_accelE5feat2_14_address1 = p_ZZ9cnn_accelE5feat2_14_address1_local;

assign p_ZZ9cnn_accelE5feat2_14_ce0 = p_ZZ9cnn_accelE5feat2_14_ce0_local;

assign p_ZZ9cnn_accelE5feat2_14_ce1 = p_ZZ9cnn_accelE5feat2_14_ce1_local;

assign p_ZZ9cnn_accelE5feat2_15_address0 = p_ZZ9cnn_accelE5feat2_15_address0_local;

assign p_ZZ9cnn_accelE5feat2_15_address1 = p_ZZ9cnn_accelE5feat2_15_address1_local;

assign p_ZZ9cnn_accelE5feat2_15_ce0 = p_ZZ9cnn_accelE5feat2_15_ce0_local;

assign p_ZZ9cnn_accelE5feat2_15_ce1 = p_ZZ9cnn_accelE5feat2_15_ce1_local;

assign p_ZZ9cnn_accelE7feat2_p_10_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_10_ce0 = p_ZZ9cnn_accelE7feat2_p_10_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_10_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_10_we0 = p_ZZ9cnn_accelE7feat2_p_10_we0_local;

assign p_ZZ9cnn_accelE7feat2_p_11_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_11_ce0 = p_ZZ9cnn_accelE7feat2_p_11_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_11_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_11_we0 = p_ZZ9cnn_accelE7feat2_p_11_we0_local;

assign p_ZZ9cnn_accelE7feat2_p_12_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_12_ce0 = p_ZZ9cnn_accelE7feat2_p_12_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_12_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_12_we0 = p_ZZ9cnn_accelE7feat2_p_12_we0_local;

assign p_ZZ9cnn_accelE7feat2_p_13_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_13_ce0 = p_ZZ9cnn_accelE7feat2_p_13_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_13_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_13_we0 = p_ZZ9cnn_accelE7feat2_p_13_we0_local;

assign p_ZZ9cnn_accelE7feat2_p_14_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_14_ce0 = p_ZZ9cnn_accelE7feat2_p_14_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_14_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_14_we0 = p_ZZ9cnn_accelE7feat2_p_14_we0_local;

assign p_ZZ9cnn_accelE7feat2_p_15_address0 = p_cast_fu_1752_p1;

assign p_ZZ9cnn_accelE7feat2_p_15_ce0 = p_ZZ9cnn_accelE7feat2_p_15_ce0_local;

assign p_ZZ9cnn_accelE7feat2_p_15_d0 = select_ln180_fu_1853_p3;

assign p_ZZ9cnn_accelE7feat2_p_15_we0 = p_ZZ9cnn_accelE7feat2_p_15_we0_local;

assign p_cast1_fu_1366_p1 = empty_62_fu_1360_p2;

assign p_cast2_fu_1487_p1 = empty_63_fu_1482_p2;

assign p_cast3_fu_1404_p1 = empty_64_fu_1398_p2;

assign p_cast4_fu_1512_p1 = empty_65_fu_1507_p2;

assign p_cast_fu_1752_p1 = grp_fu_1875_p3;

assign select_ln168_1_fu_1294_p3 = ((icmp_ln170_fu_1262_p2[0:0] == 1'b1) ? add_ln168_fu_1256_p2 : i_fu_180);

assign select_ln168_fu_1268_p3 = ((icmp_ln170_fu_1262_p2[0:0] == 1'b1) ? 7'd0 : j_fu_172);

assign select_ln170_1_fu_1542_p3 = ((icmp_ln170_reg_1933[0:0] == 1'b1) ? 12'd1 : add_ln170_1_fu_1537_p2);

assign select_ln170_fu_1322_p3 = ((and_ln168_fu_1288_p2[0:0] == 1'b1) ? add_ln170_fu_1302_p2 : select_ln168_fu_1268_p3);

assign select_ln180_fu_1853_p3 = ((and_ln180_1_fu_1847_p2[0:0] == 1'b1) ? mx_reg_2330 : my_reg_2337);

assign tmp_11_fu_1774_p4 = {{bitcast_ln180_fu_1771_p1[30:23]}};

assign tmp_12_fu_1791_p4 = {{bitcast_ln180_1_fu_1788_p1[30:23]}};

assign tmp_2_fu_1465_p3 = {{select_ln168_1_reg_1938}, {1'd1}};

assign tmp_39_cast_fu_1356_p1 = tmp_3_fu_1348_p3;

assign tmp_3_fu_1348_p3 = {{select_ln170_fu_1322_p3}, {1'd0}};

assign tmp_40_cast_fu_1394_p1 = tmp_4_fu_1386_p3;

assign tmp_4_fu_1386_p3 = {{select_ln170_fu_1322_p3}, {1'd1}};

assign tmp_5_fu_1577_p4 = {{bitcast_ln178_fu_1574_p1[30:23]}};

assign tmp_6_fu_1594_p4 = {{bitcast_ln178_1_fu_1591_p1[30:23]}};

assign tmp_8_fu_1666_p4 = {{bitcast_ln179_fu_1663_p1[30:23]}};

assign tmp_9_fu_1683_p4 = {{bitcast_ln179_1_fu_1680_p1[30:23]}};

assign tmp_s_fu_1330_p3 = {{select_ln168_1_fu_1294_p3}, {1'd0}};

assign trunc_ln172_fu_1424_p1 = m_3_mid2_fu_1314_p3[3:0];

assign trunc_ln178_1_fu_1604_p1 = bitcast_ln178_1_fu_1591_p1[22:0];

assign trunc_ln178_fu_1587_p1 = bitcast_ln178_fu_1574_p1[22:0];

assign trunc_ln179_1_fu_1693_p1 = bitcast_ln179_1_fu_1680_p1[22:0];

assign trunc_ln179_fu_1676_p1 = bitcast_ln179_fu_1663_p1[22:0];

assign trunc_ln180_1_fu_1801_p1 = bitcast_ln180_1_fu_1788_p1[22:0];

assign trunc_ln180_fu_1784_p1 = bitcast_ln180_fu_1771_p1[22:0];

assign xor_ln168_fu_1276_p2 = (icmp_ln170_fu_1262_p2 ^ 1'd1);

always @ (posedge ap_clk) begin
    tmp_39_cast_reg_1956[0] <= 1'b0;
    tmp_39_cast_reg_1956[14:8] <= 7'b0000000;
    tmp_40_cast_reg_2041[0] <= 1'b1;
    tmp_40_cast_reg_2041[14:8] <= 7'b0000000;
end

endmodule //cnn_accel_cnn_accel_Pipeline_POOL2_ROW_POOL2_COL_POOL2_CH
