// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_Block_entry_proc_Pipeline_LOAD_FC1B (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_B3mem_0_AWVALID,
        m_axi_B3mem_0_AWREADY,
        m_axi_B3mem_0_AWADDR,
        m_axi_B3mem_0_AWID,
        m_axi_B3mem_0_AWLEN,
        m_axi_B3mem_0_AWSIZE,
        m_axi_B3mem_0_AWBURST,
        m_axi_B3mem_0_AWLOCK,
        m_axi_B3mem_0_AWCACHE,
        m_axi_B3mem_0_AWPROT,
        m_axi_B3mem_0_AWQOS,
        m_axi_B3mem_0_AWREGION,
        m_axi_B3mem_0_AWUSER,
        m_axi_B3mem_0_WVALID,
        m_axi_B3mem_0_WREADY,
        m_axi_B3mem_0_WDATA,
        m_axi_B3mem_0_WSTRB,
        m_axi_B3mem_0_WLAST,
        m_axi_B3mem_0_WID,
        m_axi_B3mem_0_WUSER,
        m_axi_B3mem_0_ARVALID,
        m_axi_B3mem_0_ARREADY,
        m_axi_B3mem_0_ARADDR,
        m_axi_B3mem_0_ARID,
        m_axi_B3mem_0_ARLEN,
        m_axi_B3mem_0_ARSIZE,
        m_axi_B3mem_0_ARBURST,
        m_axi_B3mem_0_ARLOCK,
        m_axi_B3mem_0_ARCACHE,
        m_axi_B3mem_0_ARPROT,
        m_axi_B3mem_0_ARQOS,
        m_axi_B3mem_0_ARREGION,
        m_axi_B3mem_0_ARUSER,
        m_axi_B3mem_0_RVALID,
        m_axi_B3mem_0_RREADY,
        m_axi_B3mem_0_RDATA,
        m_axi_B3mem_0_RLAST,
        m_axi_B3mem_0_RID,
        m_axi_B3mem_0_RFIFONUM,
        m_axi_B3mem_0_RUSER,
        m_axi_B3mem_0_RRESP,
        m_axi_B3mem_0_BVALID,
        m_axi_B3mem_0_BREADY,
        m_axi_B3mem_0_BRESP,
        m_axi_B3mem_0_BID,
        m_axi_B3mem_0_BUSER,
        sext_ln144,
        p_ZZ9cnn_accelE11fc1_b_local_30,
        p_ZZ9cnn_accelE11fc1_b_local_30_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_29,
        p_ZZ9cnn_accelE11fc1_b_local_29_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_28,
        p_ZZ9cnn_accelE11fc1_b_local_28_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_27,
        p_ZZ9cnn_accelE11fc1_b_local_27_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_26,
        p_ZZ9cnn_accelE11fc1_b_local_26_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_25,
        p_ZZ9cnn_accelE11fc1_b_local_25_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_24,
        p_ZZ9cnn_accelE11fc1_b_local_24_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_23,
        p_ZZ9cnn_accelE11fc1_b_local_23_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_22,
        p_ZZ9cnn_accelE11fc1_b_local_22_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_21,
        p_ZZ9cnn_accelE11fc1_b_local_21_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_20,
        p_ZZ9cnn_accelE11fc1_b_local_20_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_19,
        p_ZZ9cnn_accelE11fc1_b_local_19_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_18,
        p_ZZ9cnn_accelE11fc1_b_local_18_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_17,
        p_ZZ9cnn_accelE11fc1_b_local_17_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_16,
        p_ZZ9cnn_accelE11fc1_b_local_16_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_15,
        p_ZZ9cnn_accelE11fc1_b_local_15_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_14,
        p_ZZ9cnn_accelE11fc1_b_local_14_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_13,
        p_ZZ9cnn_accelE11fc1_b_local_13_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_12,
        p_ZZ9cnn_accelE11fc1_b_local_12_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_11,
        p_ZZ9cnn_accelE11fc1_b_local_11_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_10,
        p_ZZ9cnn_accelE11fc1_b_local_10_ap_vld,
        fc1_b_local_50,
        fc1_b_local_50_ap_vld,
        fc1_b_local_49,
        fc1_b_local_49_ap_vld,
        fc1_b_local_48,
        fc1_b_local_48_ap_vld,
        fc1_b_local_47,
        fc1_b_local_47_ap_vld,
        fc1_b_local_46,
        fc1_b_local_46_ap_vld,
        fc1_b_local_45,
        fc1_b_local_45_ap_vld,
        fc1_b_local_44,
        fc1_b_local_44_ap_vld,
        fc1_b_local_43,
        fc1_b_local_43_ap_vld,
        fc1_b_local_42,
        fc1_b_local_42_ap_vld,
        fc1_b_local,
        fc1_b_local_ap_vld,
        p_ZZ9cnn_accelE11fc1_b_local_31,
        p_ZZ9cnn_accelE11fc1_b_local_31_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_B3mem_0_AWVALID;
input   m_axi_B3mem_0_AWREADY;
output  [63:0] m_axi_B3mem_0_AWADDR;
output  [0:0] m_axi_B3mem_0_AWID;
output  [31:0] m_axi_B3mem_0_AWLEN;
output  [2:0] m_axi_B3mem_0_AWSIZE;
output  [1:0] m_axi_B3mem_0_AWBURST;
output  [1:0] m_axi_B3mem_0_AWLOCK;
output  [3:0] m_axi_B3mem_0_AWCACHE;
output  [2:0] m_axi_B3mem_0_AWPROT;
output  [3:0] m_axi_B3mem_0_AWQOS;
output  [3:0] m_axi_B3mem_0_AWREGION;
output  [0:0] m_axi_B3mem_0_AWUSER;
output   m_axi_B3mem_0_WVALID;
input   m_axi_B3mem_0_WREADY;
output  [31:0] m_axi_B3mem_0_WDATA;
output  [3:0] m_axi_B3mem_0_WSTRB;
output   m_axi_B3mem_0_WLAST;
output  [0:0] m_axi_B3mem_0_WID;
output  [0:0] m_axi_B3mem_0_WUSER;
output   m_axi_B3mem_0_ARVALID;
input   m_axi_B3mem_0_ARREADY;
output  [63:0] m_axi_B3mem_0_ARADDR;
output  [0:0] m_axi_B3mem_0_ARID;
output  [31:0] m_axi_B3mem_0_ARLEN;
output  [2:0] m_axi_B3mem_0_ARSIZE;
output  [1:0] m_axi_B3mem_0_ARBURST;
output  [1:0] m_axi_B3mem_0_ARLOCK;
output  [3:0] m_axi_B3mem_0_ARCACHE;
output  [2:0] m_axi_B3mem_0_ARPROT;
output  [3:0] m_axi_B3mem_0_ARQOS;
output  [3:0] m_axi_B3mem_0_ARREGION;
output  [0:0] m_axi_B3mem_0_ARUSER;
input   m_axi_B3mem_0_RVALID;
output   m_axi_B3mem_0_RREADY;
input  [31:0] m_axi_B3mem_0_RDATA;
input   m_axi_B3mem_0_RLAST;
input  [0:0] m_axi_B3mem_0_RID;
input  [8:0] m_axi_B3mem_0_RFIFONUM;
input  [0:0] m_axi_B3mem_0_RUSER;
input  [1:0] m_axi_B3mem_0_RRESP;
input   m_axi_B3mem_0_BVALID;
output   m_axi_B3mem_0_BREADY;
input  [1:0] m_axi_B3mem_0_BRESP;
input  [0:0] m_axi_B3mem_0_BID;
input  [0:0] m_axi_B3mem_0_BUSER;
input  [61:0] sext_ln144;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_30;
output   p_ZZ9cnn_accelE11fc1_b_local_30_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_29;
output   p_ZZ9cnn_accelE11fc1_b_local_29_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_28;
output   p_ZZ9cnn_accelE11fc1_b_local_28_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_27;
output   p_ZZ9cnn_accelE11fc1_b_local_27_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_26;
output   p_ZZ9cnn_accelE11fc1_b_local_26_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_25;
output   p_ZZ9cnn_accelE11fc1_b_local_25_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_24;
output   p_ZZ9cnn_accelE11fc1_b_local_24_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_23;
output   p_ZZ9cnn_accelE11fc1_b_local_23_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_22;
output   p_ZZ9cnn_accelE11fc1_b_local_22_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_21;
output   p_ZZ9cnn_accelE11fc1_b_local_21_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_20;
output   p_ZZ9cnn_accelE11fc1_b_local_20_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_19;
output   p_ZZ9cnn_accelE11fc1_b_local_19_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_18;
output   p_ZZ9cnn_accelE11fc1_b_local_18_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_17;
output   p_ZZ9cnn_accelE11fc1_b_local_17_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_16;
output   p_ZZ9cnn_accelE11fc1_b_local_16_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_15;
output   p_ZZ9cnn_accelE11fc1_b_local_15_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_14;
output   p_ZZ9cnn_accelE11fc1_b_local_14_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_13;
output   p_ZZ9cnn_accelE11fc1_b_local_13_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_12;
output   p_ZZ9cnn_accelE11fc1_b_local_12_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_11;
output   p_ZZ9cnn_accelE11fc1_b_local_11_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_10;
output   p_ZZ9cnn_accelE11fc1_b_local_10_ap_vld;
output  [31:0] fc1_b_local_50;
output   fc1_b_local_50_ap_vld;
output  [31:0] fc1_b_local_49;
output   fc1_b_local_49_ap_vld;
output  [31:0] fc1_b_local_48;
output   fc1_b_local_48_ap_vld;
output  [31:0] fc1_b_local_47;
output   fc1_b_local_47_ap_vld;
output  [31:0] fc1_b_local_46;
output   fc1_b_local_46_ap_vld;
output  [31:0] fc1_b_local_45;
output   fc1_b_local_45_ap_vld;
output  [31:0] fc1_b_local_44;
output   fc1_b_local_44_ap_vld;
output  [31:0] fc1_b_local_43;
output   fc1_b_local_43_ap_vld;
output  [31:0] fc1_b_local_42;
output   fc1_b_local_42_ap_vld;
output  [31:0] fc1_b_local;
output   fc1_b_local_ap_vld;
output  [31:0] p_ZZ9cnn_accelE11fc1_b_local_31;
output   p_ZZ9cnn_accelE11fc1_b_local_31_ap_vld;

reg ap_idle;
reg m_axi_B3mem_0_RREADY;
reg p_ZZ9cnn_accelE11fc1_b_local_30_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_29_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_28_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_27_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_26_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_25_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_24_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_23_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_22_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_21_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_20_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_19_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_18_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_17_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_16_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_15_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_14_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_13_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_12_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_11_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_10_ap_vld;
reg fc1_b_local_50_ap_vld;
reg fc1_b_local_49_ap_vld;
reg fc1_b_local_48_ap_vld;
reg fc1_b_local_47_ap_vld;
reg fc1_b_local_46_ap_vld;
reg fc1_b_local_45_ap_vld;
reg fc1_b_local_44_ap_vld;
reg fc1_b_local_43_ap_vld;
reg fc1_b_local_42_ap_vld;
reg fc1_b_local_ap_vld;
reg p_ZZ9cnn_accelE11fc1_b_local_31_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln144_fu_199_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    B3mem_blk_n_R;
wire   [5:0] add_ln144_fu_205_p2;
reg   [5:0] add_ln144_reg_496;
wire   [4:0] trunc_ln144_fu_217_p1;
reg   [4:0] trunc_ln144_reg_506;
wire   [31:0] bitcast_ln146_fu_221_p1;
reg   [5:0] i_fu_172;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 i_fu_172 = 6'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_172 <= 6'd0;
    end else if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_172 <= add_ln144_reg_496;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln144_reg_496 <= add_ln144_fu_205_p2;
        trunc_ln144_reg_506 <= trunc_ln144_fu_217_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B3mem_blk_n_R = m_axi_B3mem_0_RVALID;
    end else begin
        B3mem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln144_fu_199_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_5 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd1))) begin
        fc1_b_local_42_ap_vld = 1'b1;
    end else begin
        fc1_b_local_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd2))) begin
        fc1_b_local_43_ap_vld = 1'b1;
    end else begin
        fc1_b_local_43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd3))) begin
        fc1_b_local_44_ap_vld = 1'b1;
    end else begin
        fc1_b_local_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd4))) begin
        fc1_b_local_45_ap_vld = 1'b1;
    end else begin
        fc1_b_local_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd5))) begin
        fc1_b_local_46_ap_vld = 1'b1;
    end else begin
        fc1_b_local_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd6))) begin
        fc1_b_local_47_ap_vld = 1'b1;
    end else begin
        fc1_b_local_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd7))) begin
        fc1_b_local_48_ap_vld = 1'b1;
    end else begin
        fc1_b_local_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd8))) begin
        fc1_b_local_49_ap_vld = 1'b1;
    end else begin
        fc1_b_local_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd9))) begin
        fc1_b_local_50_ap_vld = 1'b1;
    end else begin
        fc1_b_local_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd0))) begin
        fc1_b_local_ap_vld = 1'b1;
    end else begin
        fc1_b_local_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_B3mem_0_RREADY = 1'b1;
    end else begin
        m_axi_B3mem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd10))) begin
        p_ZZ9cnn_accelE11fc1_b_local_10_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd11))) begin
        p_ZZ9cnn_accelE11fc1_b_local_11_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd12))) begin
        p_ZZ9cnn_accelE11fc1_b_local_12_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd13))) begin
        p_ZZ9cnn_accelE11fc1_b_local_13_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd14))) begin
        p_ZZ9cnn_accelE11fc1_b_local_14_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd15))) begin
        p_ZZ9cnn_accelE11fc1_b_local_15_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd16))) begin
        p_ZZ9cnn_accelE11fc1_b_local_16_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd17))) begin
        p_ZZ9cnn_accelE11fc1_b_local_17_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd18))) begin
        p_ZZ9cnn_accelE11fc1_b_local_18_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd19))) begin
        p_ZZ9cnn_accelE11fc1_b_local_19_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd20))) begin
        p_ZZ9cnn_accelE11fc1_b_local_20_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd21))) begin
        p_ZZ9cnn_accelE11fc1_b_local_21_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd22))) begin
        p_ZZ9cnn_accelE11fc1_b_local_22_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd23))) begin
        p_ZZ9cnn_accelE11fc1_b_local_23_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd24))) begin
        p_ZZ9cnn_accelE11fc1_b_local_24_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd25))) begin
        p_ZZ9cnn_accelE11fc1_b_local_25_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd26))) begin
        p_ZZ9cnn_accelE11fc1_b_local_26_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd27))) begin
        p_ZZ9cnn_accelE11fc1_b_local_27_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd28))) begin
        p_ZZ9cnn_accelE11fc1_b_local_28_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd29))) begin
        p_ZZ9cnn_accelE11fc1_b_local_29_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd30))) begin
        p_ZZ9cnn_accelE11fc1_b_local_30_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2) & (trunc_ln144_reg_506 == 5'd31))) begin
        p_ZZ9cnn_accelE11fc1_b_local_31_ap_vld = 1'b1;
    end else begin
        p_ZZ9cnn_accelE11fc1_b_local_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln144_fu_199_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln144_fu_205_p2 = (ap_sig_allocacmp_i_5 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (m_axi_B3mem_0_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln146_fu_221_p1 = m_axi_B3mem_0_RDATA;

assign fc1_b_local = bitcast_ln146_fu_221_p1;

assign fc1_b_local_42 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_43 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_44 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_45 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_46 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_47 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_48 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_49 = bitcast_ln146_fu_221_p1;

assign fc1_b_local_50 = bitcast_ln146_fu_221_p1;

assign icmp_ln144_fu_199_p2 = ((ap_sig_allocacmp_i_5 == 6'd32) ? 1'b1 : 1'b0);

assign m_axi_B3mem_0_ARADDR = 64'd0;

assign m_axi_B3mem_0_ARBURST = 2'd0;

assign m_axi_B3mem_0_ARCACHE = 4'd0;

assign m_axi_B3mem_0_ARID = 1'd0;

assign m_axi_B3mem_0_ARLEN = 32'd0;

assign m_axi_B3mem_0_ARLOCK = 2'd0;

assign m_axi_B3mem_0_ARPROT = 3'd0;

assign m_axi_B3mem_0_ARQOS = 4'd0;

assign m_axi_B3mem_0_ARREGION = 4'd0;

assign m_axi_B3mem_0_ARSIZE = 3'd0;

assign m_axi_B3mem_0_ARUSER = 1'd0;

assign m_axi_B3mem_0_ARVALID = 1'b0;

assign m_axi_B3mem_0_AWADDR = 64'd0;

assign m_axi_B3mem_0_AWBURST = 2'd0;

assign m_axi_B3mem_0_AWCACHE = 4'd0;

assign m_axi_B3mem_0_AWID = 1'd0;

assign m_axi_B3mem_0_AWLEN = 32'd0;

assign m_axi_B3mem_0_AWLOCK = 2'd0;

assign m_axi_B3mem_0_AWPROT = 3'd0;

assign m_axi_B3mem_0_AWQOS = 4'd0;

assign m_axi_B3mem_0_AWREGION = 4'd0;

assign m_axi_B3mem_0_AWSIZE = 3'd0;

assign m_axi_B3mem_0_AWUSER = 1'd0;

assign m_axi_B3mem_0_AWVALID = 1'b0;

assign m_axi_B3mem_0_BREADY = 1'b0;

assign m_axi_B3mem_0_WDATA = 32'd0;

assign m_axi_B3mem_0_WID = 1'd0;

assign m_axi_B3mem_0_WLAST = 1'b0;

assign m_axi_B3mem_0_WSTRB = 4'd0;

assign m_axi_B3mem_0_WUSER = 1'd0;

assign m_axi_B3mem_0_WVALID = 1'b0;

assign p_ZZ9cnn_accelE11fc1_b_local_10 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_11 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_12 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_13 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_14 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_15 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_16 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_17 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_18 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_19 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_20 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_21 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_22 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_23 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_24 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_25 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_26 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_27 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_28 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_29 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_30 = bitcast_ln146_fu_221_p1;

assign p_ZZ9cnn_accelE11fc1_b_local_31 = bitcast_ln146_fu_221_p1;

assign trunc_ln144_fu_217_p1 = ap_sig_allocacmp_i_5[4:0];

endmodule //cnn_accel_Block_entry_proc_Pipeline_LOAD_FC1B
