// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_fc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_W3mem_0_AWVALID,
        m_axi_W3mem_0_AWREADY,
        m_axi_W3mem_0_AWADDR,
        m_axi_W3mem_0_AWID,
        m_axi_W3mem_0_AWLEN,
        m_axi_W3mem_0_AWSIZE,
        m_axi_W3mem_0_AWBURST,
        m_axi_W3mem_0_AWLOCK,
        m_axi_W3mem_0_AWCACHE,
        m_axi_W3mem_0_AWPROT,
        m_axi_W3mem_0_AWQOS,
        m_axi_W3mem_0_AWREGION,
        m_axi_W3mem_0_AWUSER,
        m_axi_W3mem_0_WVALID,
        m_axi_W3mem_0_WREADY,
        m_axi_W3mem_0_WDATA,
        m_axi_W3mem_0_WSTRB,
        m_axi_W3mem_0_WLAST,
        m_axi_W3mem_0_WID,
        m_axi_W3mem_0_WUSER,
        m_axi_W3mem_0_ARVALID,
        m_axi_W3mem_0_ARREADY,
        m_axi_W3mem_0_ARADDR,
        m_axi_W3mem_0_ARID,
        m_axi_W3mem_0_ARLEN,
        m_axi_W3mem_0_ARSIZE,
        m_axi_W3mem_0_ARBURST,
        m_axi_W3mem_0_ARLOCK,
        m_axi_W3mem_0_ARCACHE,
        m_axi_W3mem_0_ARPROT,
        m_axi_W3mem_0_ARQOS,
        m_axi_W3mem_0_ARREGION,
        m_axi_W3mem_0_ARUSER,
        m_axi_W3mem_0_RVALID,
        m_axi_W3mem_0_RREADY,
        m_axi_W3mem_0_RDATA,
        m_axi_W3mem_0_RLAST,
        m_axi_W3mem_0_RID,
        m_axi_W3mem_0_RFIFONUM,
        m_axi_W3mem_0_RUSER,
        m_axi_W3mem_0_RRESP,
        m_axi_W3mem_0_BVALID,
        m_axi_W3mem_0_BREADY,
        m_axi_W3mem_0_BRESP,
        m_axi_W3mem_0_BID,
        m_axi_W3mem_0_BUSER,
        FC1_W,
        m_axi_B3mem_0_AWVALID,
        m_axi_B3mem_0_AWREADY,
        m_axi_B3mem_0_AWADDR,
        m_axi_B3mem_0_AWID,
        m_axi_B3mem_0_AWLEN,
        m_axi_B3mem_0_AWSIZE,
        m_axi_B3mem_0_AWBURST,
        m_axi_B3mem_0_AWLOCK,
        m_axi_B3mem_0_AWCACHE,
        m_axi_B3mem_0_AWPROT,
        m_axi_B3mem_0_AWQOS,
        m_axi_B3mem_0_AWREGION,
        m_axi_B3mem_0_AWUSER,
        m_axi_B3mem_0_WVALID,
        m_axi_B3mem_0_WREADY,
        m_axi_B3mem_0_WDATA,
        m_axi_B3mem_0_WSTRB,
        m_axi_B3mem_0_WLAST,
        m_axi_B3mem_0_WID,
        m_axi_B3mem_0_WUSER,
        m_axi_B3mem_0_ARVALID,
        m_axi_B3mem_0_ARREADY,
        m_axi_B3mem_0_ARADDR,
        m_axi_B3mem_0_ARID,
        m_axi_B3mem_0_ARLEN,
        m_axi_B3mem_0_ARSIZE,
        m_axi_B3mem_0_ARBURST,
        m_axi_B3mem_0_ARLOCK,
        m_axi_B3mem_0_ARCACHE,
        m_axi_B3mem_0_ARPROT,
        m_axi_B3mem_0_ARQOS,
        m_axi_B3mem_0_ARREGION,
        m_axi_B3mem_0_ARUSER,
        m_axi_B3mem_0_RVALID,
        m_axi_B3mem_0_RREADY,
        m_axi_B3mem_0_RDATA,
        m_axi_B3mem_0_RLAST,
        m_axi_B3mem_0_RID,
        m_axi_B3mem_0_RFIFONUM,
        m_axi_B3mem_0_RUSER,
        m_axi_B3mem_0_RRESP,
        m_axi_B3mem_0_BVALID,
        m_axi_B3mem_0_BREADY,
        m_axi_B3mem_0_BRESP,
        m_axi_B3mem_0_BID,
        m_axi_B3mem_0_BUSER,
        FC1_B,
        vec1_address0,
        vec1_ce0,
        vec1_q0,
        vec2_address0,
        vec2_ce0,
        vec2_we0,
        vec2_d0
);

parameter    ap_ST_fsm_state1 = 84'd1;
parameter    ap_ST_fsm_state2 = 84'd2;
parameter    ap_ST_fsm_state3 = 84'd4;
parameter    ap_ST_fsm_state4 = 84'd8;
parameter    ap_ST_fsm_state5 = 84'd16;
parameter    ap_ST_fsm_state6 = 84'd32;
parameter    ap_ST_fsm_state7 = 84'd64;
parameter    ap_ST_fsm_state8 = 84'd128;
parameter    ap_ST_fsm_state9 = 84'd256;
parameter    ap_ST_fsm_state10 = 84'd512;
parameter    ap_ST_fsm_state11 = 84'd1024;
parameter    ap_ST_fsm_state12 = 84'd2048;
parameter    ap_ST_fsm_state13 = 84'd4096;
parameter    ap_ST_fsm_state14 = 84'd8192;
parameter    ap_ST_fsm_state15 = 84'd16384;
parameter    ap_ST_fsm_state16 = 84'd32768;
parameter    ap_ST_fsm_state17 = 84'd65536;
parameter    ap_ST_fsm_state18 = 84'd131072;
parameter    ap_ST_fsm_state19 = 84'd262144;
parameter    ap_ST_fsm_state20 = 84'd524288;
parameter    ap_ST_fsm_state21 = 84'd1048576;
parameter    ap_ST_fsm_state22 = 84'd2097152;
parameter    ap_ST_fsm_state23 = 84'd4194304;
parameter    ap_ST_fsm_state24 = 84'd8388608;
parameter    ap_ST_fsm_state25 = 84'd16777216;
parameter    ap_ST_fsm_state26 = 84'd33554432;
parameter    ap_ST_fsm_state27 = 84'd67108864;
parameter    ap_ST_fsm_state28 = 84'd134217728;
parameter    ap_ST_fsm_state29 = 84'd268435456;
parameter    ap_ST_fsm_state30 = 84'd536870912;
parameter    ap_ST_fsm_state31 = 84'd1073741824;
parameter    ap_ST_fsm_state32 = 84'd2147483648;
parameter    ap_ST_fsm_state33 = 84'd4294967296;
parameter    ap_ST_fsm_state34 = 84'd8589934592;
parameter    ap_ST_fsm_state35 = 84'd17179869184;
parameter    ap_ST_fsm_state36 = 84'd34359738368;
parameter    ap_ST_fsm_state37 = 84'd68719476736;
parameter    ap_ST_fsm_state38 = 84'd137438953472;
parameter    ap_ST_fsm_state39 = 84'd274877906944;
parameter    ap_ST_fsm_state40 = 84'd549755813888;
parameter    ap_ST_fsm_state41 = 84'd1099511627776;
parameter    ap_ST_fsm_state42 = 84'd2199023255552;
parameter    ap_ST_fsm_state43 = 84'd4398046511104;
parameter    ap_ST_fsm_state44 = 84'd8796093022208;
parameter    ap_ST_fsm_state45 = 84'd17592186044416;
parameter    ap_ST_fsm_state46 = 84'd35184372088832;
parameter    ap_ST_fsm_state47 = 84'd70368744177664;
parameter    ap_ST_fsm_state48 = 84'd140737488355328;
parameter    ap_ST_fsm_state49 = 84'd281474976710656;
parameter    ap_ST_fsm_state50 = 84'd562949953421312;
parameter    ap_ST_fsm_state51 = 84'd1125899906842624;
parameter    ap_ST_fsm_state52 = 84'd2251799813685248;
parameter    ap_ST_fsm_state53 = 84'd4503599627370496;
parameter    ap_ST_fsm_state54 = 84'd9007199254740992;
parameter    ap_ST_fsm_state55 = 84'd18014398509481984;
parameter    ap_ST_fsm_state56 = 84'd36028797018963968;
parameter    ap_ST_fsm_state57 = 84'd72057594037927936;
parameter    ap_ST_fsm_state58 = 84'd144115188075855872;
parameter    ap_ST_fsm_state59 = 84'd288230376151711744;
parameter    ap_ST_fsm_state60 = 84'd576460752303423488;
parameter    ap_ST_fsm_state61 = 84'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 84'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 84'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 84'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 84'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 84'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 84'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 84'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 84'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 84'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 84'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 84'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 84'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 84'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 84'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 84'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 84'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 84'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 84'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 84'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 84'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 84'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 84'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 84'd9671406556917033397649408;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_W3mem_0_AWVALID;
input   m_axi_W3mem_0_AWREADY;
output  [63:0] m_axi_W3mem_0_AWADDR;
output  [0:0] m_axi_W3mem_0_AWID;
output  [31:0] m_axi_W3mem_0_AWLEN;
output  [2:0] m_axi_W3mem_0_AWSIZE;
output  [1:0] m_axi_W3mem_0_AWBURST;
output  [1:0] m_axi_W3mem_0_AWLOCK;
output  [3:0] m_axi_W3mem_0_AWCACHE;
output  [2:0] m_axi_W3mem_0_AWPROT;
output  [3:0] m_axi_W3mem_0_AWQOS;
output  [3:0] m_axi_W3mem_0_AWREGION;
output  [0:0] m_axi_W3mem_0_AWUSER;
output   m_axi_W3mem_0_WVALID;
input   m_axi_W3mem_0_WREADY;
output  [31:0] m_axi_W3mem_0_WDATA;
output  [3:0] m_axi_W3mem_0_WSTRB;
output   m_axi_W3mem_0_WLAST;
output  [0:0] m_axi_W3mem_0_WID;
output  [0:0] m_axi_W3mem_0_WUSER;
output   m_axi_W3mem_0_ARVALID;
input   m_axi_W3mem_0_ARREADY;
output  [63:0] m_axi_W3mem_0_ARADDR;
output  [0:0] m_axi_W3mem_0_ARID;
output  [31:0] m_axi_W3mem_0_ARLEN;
output  [2:0] m_axi_W3mem_0_ARSIZE;
output  [1:0] m_axi_W3mem_0_ARBURST;
output  [1:0] m_axi_W3mem_0_ARLOCK;
output  [3:0] m_axi_W3mem_0_ARCACHE;
output  [2:0] m_axi_W3mem_0_ARPROT;
output  [3:0] m_axi_W3mem_0_ARQOS;
output  [3:0] m_axi_W3mem_0_ARREGION;
output  [0:0] m_axi_W3mem_0_ARUSER;
input   m_axi_W3mem_0_RVALID;
output   m_axi_W3mem_0_RREADY;
input  [31:0] m_axi_W3mem_0_RDATA;
input   m_axi_W3mem_0_RLAST;
input  [0:0] m_axi_W3mem_0_RID;
input  [8:0] m_axi_W3mem_0_RFIFONUM;
input  [0:0] m_axi_W3mem_0_RUSER;
input  [1:0] m_axi_W3mem_0_RRESP;
input   m_axi_W3mem_0_BVALID;
output   m_axi_W3mem_0_BREADY;
input  [1:0] m_axi_W3mem_0_BRESP;
input  [0:0] m_axi_W3mem_0_BID;
input  [0:0] m_axi_W3mem_0_BUSER;
input  [63:0] FC1_W;
output   m_axi_B3mem_0_AWVALID;
input   m_axi_B3mem_0_AWREADY;
output  [63:0] m_axi_B3mem_0_AWADDR;
output  [0:0] m_axi_B3mem_0_AWID;
output  [31:0] m_axi_B3mem_0_AWLEN;
output  [2:0] m_axi_B3mem_0_AWSIZE;
output  [1:0] m_axi_B3mem_0_AWBURST;
output  [1:0] m_axi_B3mem_0_AWLOCK;
output  [3:0] m_axi_B3mem_0_AWCACHE;
output  [2:0] m_axi_B3mem_0_AWPROT;
output  [3:0] m_axi_B3mem_0_AWQOS;
output  [3:0] m_axi_B3mem_0_AWREGION;
output  [0:0] m_axi_B3mem_0_AWUSER;
output   m_axi_B3mem_0_WVALID;
input   m_axi_B3mem_0_WREADY;
output  [31:0] m_axi_B3mem_0_WDATA;
output  [3:0] m_axi_B3mem_0_WSTRB;
output   m_axi_B3mem_0_WLAST;
output  [0:0] m_axi_B3mem_0_WID;
output  [0:0] m_axi_B3mem_0_WUSER;
output   m_axi_B3mem_0_ARVALID;
input   m_axi_B3mem_0_ARREADY;
output  [63:0] m_axi_B3mem_0_ARADDR;
output  [0:0] m_axi_B3mem_0_ARID;
output  [31:0] m_axi_B3mem_0_ARLEN;
output  [2:0] m_axi_B3mem_0_ARSIZE;
output  [1:0] m_axi_B3mem_0_ARBURST;
output  [1:0] m_axi_B3mem_0_ARLOCK;
output  [3:0] m_axi_B3mem_0_ARCACHE;
output  [2:0] m_axi_B3mem_0_ARPROT;
output  [3:0] m_axi_B3mem_0_ARQOS;
output  [3:0] m_axi_B3mem_0_ARREGION;
output  [0:0] m_axi_B3mem_0_ARUSER;
input   m_axi_B3mem_0_RVALID;
output   m_axi_B3mem_0_RREADY;
input  [31:0] m_axi_B3mem_0_RDATA;
input   m_axi_B3mem_0_RLAST;
input  [0:0] m_axi_B3mem_0_RID;
input  [8:0] m_axi_B3mem_0_RFIFONUM;
input  [0:0] m_axi_B3mem_0_RUSER;
input  [1:0] m_axi_B3mem_0_RRESP;
input   m_axi_B3mem_0_BVALID;
output   m_axi_B3mem_0_BREADY;
input  [1:0] m_axi_B3mem_0_BRESP;
input  [0:0] m_axi_B3mem_0_BID;
input  [0:0] m_axi_B3mem_0_BUSER;
input  [63:0] FC1_B;
output  [16:0] vec1_address0;
output   vec1_ce0;
input  [31:0] vec1_q0;
output  [4:0] vec2_address0;
output   vec2_ce0;
output   vec2_we0;
output  [31:0] vec2_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_W3mem_0_ARVALID;
reg m_axi_W3mem_0_RREADY;
reg m_axi_B3mem_0_ARVALID;
reg m_axi_B3mem_0_RREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [83:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    W3mem_blk_n_AR;
reg    W3mem_blk_n_R;
wire    ap_CS_fsm_state13;
reg    B3mem_blk_n_AR;
reg    B3mem_blk_n_R;
wire    ap_CS_fsm_state10;
reg   [0:0] icmp_ln267_reg_311;
reg    ap_block_state1;
reg    ap_block_state1_io;
wire   [0:0] icmp_ln267_fu_247_p2;
wire    ap_CS_fsm_state9;
wire   [5:0] add_ln267_fu_253_p2;
reg   [5:0] add_ln267_reg_315;
reg    ap_block_state10;
reg   [31:0] B3mem_addr_read_reg_320;
wire   [63:0] zext_ln267_fu_258_p1;
reg   [63:0] zext_ln267_reg_325;
wire    ap_CS_fsm_state11;
wire   [31:0] acc_fu_261_p1;
wire   [16:0] add_ln270_fu_270_p2;
reg   [16:0] add_ln270_reg_338;
wire    ap_CS_fsm_state12;
reg   [31:0] vec1_load_reg_348;
reg   [31:0] W3mem_addr_read_reg_353;
wire   [31:0] bitcast_ln272_fu_285_p1;
wire    ap_CS_fsm_state14;
wire   [31:0] grp_fu_193_p2;
reg   [31:0] mul9_i_i_reg_363;
wire    ap_CS_fsm_state17;
wire   [31:0] grp_fu_188_p2;
wire    ap_CS_fsm_state22;
wire    grp_generic_tanh_float_s_fu_175_ap_start;
wire    grp_generic_tanh_float_s_fu_175_ap_done;
wire    grp_generic_tanh_float_s_fu_175_ap_idle;
wire    grp_generic_tanh_float_s_fu_175_ap_ready;
wire   [31:0] grp_generic_tanh_float_s_fu_175_ap_return;
wire   [31:0] grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din0;
wire   [31:0] grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din1;
wire   [1:0] grp_generic_tanh_float_s_fu_175_grp_fu_188_p_opcode;
wire    grp_generic_tanh_float_s_fu_175_grp_fu_188_p_ce;
wire   [31:0] grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din0;
wire   [31:0] grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din1;
wire    grp_generic_tanh_float_s_fu_175_grp_fu_193_p_ce;
reg   [16:0] i_reg_154;
reg   [31:0] acc_1_reg_165;
reg    grp_generic_tanh_float_s_fu_175_ap_start_reg;
reg   [83:0] ap_NS_fsm;
wire    ap_NS_fsm_state23;
wire    ap_CS_fsm_state23;
wire   [63:0] zext_ln270_fu_276_p1;
wire   [0:0] icmp_ln270_fu_264_p2;
wire    ap_CS_fsm_state84;
wire  signed [63:0] sext_ln267_fu_207_p1;
wire  signed [63:0] sext_ln267_1_fu_228_p1;
reg   [5:0] o_fu_88;
reg    vec1_ce0_local;
reg    vec2_we0_local;
reg    vec2_ce0_local;
reg   [31:0] grp_fu_188_p0;
reg   [31:0] grp_fu_188_p1;
wire    ap_CS_fsm_state18;
reg   [31:0] grp_fu_193_p0;
reg   [31:0] grp_fu_193_p1;
wire   [61:0] trunc_ln_fu_197_p4;
wire   [61:0] trunc_ln267_1_fu_218_p4;
reg   [1:0] grp_fu_188_opcode;
reg    grp_fu_188_ce;
reg    grp_fu_193_ce;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_CS_fsm_state24;
wire    ap_ST_fsm_state24_blk;
wire    ap_CS_fsm_state25;
wire    ap_ST_fsm_state25_blk;
wire    ap_CS_fsm_state26;
wire    ap_ST_fsm_state26_blk;
wire    ap_CS_fsm_state27;
wire    ap_ST_fsm_state27_blk;
wire    ap_CS_fsm_state28;
wire    ap_ST_fsm_state28_blk;
wire    ap_CS_fsm_state29;
wire    ap_ST_fsm_state29_blk;
wire    ap_CS_fsm_state30;
wire    ap_ST_fsm_state30_blk;
wire    ap_CS_fsm_state31;
wire    ap_ST_fsm_state31_blk;
wire    ap_CS_fsm_state32;
wire    ap_ST_fsm_state32_blk;
wire    ap_CS_fsm_state33;
wire    ap_ST_fsm_state33_blk;
wire    ap_CS_fsm_state34;
wire    ap_ST_fsm_state34_blk;
wire    ap_CS_fsm_state35;
wire    ap_ST_fsm_state35_blk;
wire    ap_CS_fsm_state36;
wire    ap_ST_fsm_state36_blk;
wire    ap_CS_fsm_state37;
wire    ap_ST_fsm_state37_blk;
wire    ap_CS_fsm_state38;
wire    ap_ST_fsm_state38_blk;
wire    ap_CS_fsm_state39;
wire    ap_ST_fsm_state39_blk;
wire    ap_CS_fsm_state40;
wire    ap_ST_fsm_state40_blk;
wire    ap_CS_fsm_state41;
wire    ap_ST_fsm_state41_blk;
wire    ap_CS_fsm_state42;
wire    ap_ST_fsm_state42_blk;
wire    ap_CS_fsm_state43;
wire    ap_ST_fsm_state43_blk;
wire    ap_CS_fsm_state44;
wire    ap_ST_fsm_state44_blk;
wire    ap_CS_fsm_state45;
wire    ap_ST_fsm_state45_blk;
wire    ap_CS_fsm_state46;
wire    ap_ST_fsm_state46_blk;
wire    ap_CS_fsm_state47;
wire    ap_ST_fsm_state47_blk;
wire    ap_CS_fsm_state48;
wire    ap_ST_fsm_state48_blk;
wire    ap_CS_fsm_state49;
wire    ap_ST_fsm_state49_blk;
wire    ap_CS_fsm_state50;
wire    ap_ST_fsm_state50_blk;
wire    ap_CS_fsm_state51;
wire    ap_ST_fsm_state51_blk;
wire    ap_CS_fsm_state52;
wire    ap_ST_fsm_state52_blk;
wire    ap_CS_fsm_state53;
wire    ap_ST_fsm_state53_blk;
wire    ap_CS_fsm_state54;
wire    ap_ST_fsm_state54_blk;
wire    ap_CS_fsm_state55;
wire    ap_ST_fsm_state55_blk;
wire    ap_CS_fsm_state56;
wire    ap_ST_fsm_state56_blk;
wire    ap_CS_fsm_state57;
wire    ap_ST_fsm_state57_blk;
wire    ap_CS_fsm_state58;
wire    ap_ST_fsm_state58_blk;
wire    ap_CS_fsm_state59;
wire    ap_ST_fsm_state59_blk;
wire    ap_CS_fsm_state60;
wire    ap_ST_fsm_state60_blk;
wire    ap_CS_fsm_state61;
wire    ap_ST_fsm_state61_blk;
wire    ap_CS_fsm_state62;
wire    ap_ST_fsm_state62_blk;
wire    ap_CS_fsm_state63;
wire    ap_ST_fsm_state63_blk;
wire    ap_CS_fsm_state64;
wire    ap_ST_fsm_state64_blk;
wire    ap_CS_fsm_state65;
wire    ap_ST_fsm_state65_blk;
wire    ap_CS_fsm_state66;
wire    ap_ST_fsm_state66_blk;
wire    ap_CS_fsm_state67;
wire    ap_ST_fsm_state67_blk;
wire    ap_CS_fsm_state68;
wire    ap_ST_fsm_state68_blk;
wire    ap_CS_fsm_state69;
wire    ap_ST_fsm_state69_blk;
wire    ap_CS_fsm_state70;
wire    ap_ST_fsm_state70_blk;
wire    ap_CS_fsm_state71;
wire    ap_ST_fsm_state71_blk;
wire    ap_CS_fsm_state72;
wire    ap_ST_fsm_state72_blk;
wire    ap_CS_fsm_state73;
wire    ap_ST_fsm_state73_blk;
wire    ap_CS_fsm_state74;
wire    ap_ST_fsm_state74_blk;
wire    ap_CS_fsm_state75;
wire    ap_ST_fsm_state75_blk;
wire    ap_CS_fsm_state76;
wire    ap_ST_fsm_state76_blk;
wire    ap_CS_fsm_state77;
wire    ap_ST_fsm_state77_blk;
wire    ap_CS_fsm_state78;
wire    ap_ST_fsm_state78_blk;
wire    ap_CS_fsm_state79;
wire    ap_ST_fsm_state79_blk;
wire    ap_CS_fsm_state80;
wire    ap_ST_fsm_state80_blk;
wire    ap_CS_fsm_state81;
wire    ap_ST_fsm_state81_blk;
wire    ap_CS_fsm_state82;
wire    ap_ST_fsm_state82_blk;
wire    ap_CS_fsm_state83;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 84'd1;
#0 grp_generic_tanh_float_s_fu_175_ap_start_reg = 1'b0;
#0 o_fu_88 = 6'd0;
end

cnn_accel_generic_tanh_float_s grp_generic_tanh_float_s_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_tanh_float_s_fu_175_ap_start),
    .ap_done(grp_generic_tanh_float_s_fu_175_ap_done),
    .ap_idle(grp_generic_tanh_float_s_fu_175_ap_idle),
    .ap_ready(grp_generic_tanh_float_s_fu_175_ap_ready),
    .t_in(acc_1_reg_165),
    .ap_return(grp_generic_tanh_float_s_fu_175_ap_return),
    .grp_fu_188_p_din0(grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din0),
    .grp_fu_188_p_din1(grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din1),
    .grp_fu_188_p_opcode(grp_generic_tanh_float_s_fu_175_grp_fu_188_p_opcode),
    .grp_fu_188_p_dout0(grp_fu_188_p2),
    .grp_fu_188_p_ce(grp_generic_tanh_float_s_fu_175_grp_fu_188_p_ce),
    .grp_fu_193_p_din0(grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din0),
    .grp_fu_193_p_din1(grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din1),
    .grp_fu_193_p_dout0(grp_fu_193_p2),
    .grp_fu_193_p_ce(grp_generic_tanh_float_s_fu_175_grp_fu_193_p_ce)
);

cnn_accel_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U114(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_188_p0),
    .din1(grp_fu_188_p1),
    .opcode(grp_fu_188_opcode),
    .ce(grp_fu_188_ce),
    .dout(grp_fu_188_p2)
);

cnn_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U115(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_193_p0),
    .din1(grp_fu_193_p1),
    .ce(grp_fu_193_ce),
    .dout(grp_fu_193_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_tanh_float_s_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state23) & (1'b1 == ap_CS_fsm_state12))) begin
            grp_generic_tanh_float_s_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_generic_tanh_float_s_fu_175_ap_ready == 1'b1)) begin
            grp_generic_tanh_float_s_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        acc_1_reg_165 <= grp_fu_188_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        acc_1_reg_165 <= acc_fu_261_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        i_reg_154 <= add_ln270_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_reg_154 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        o_fu_88 <= 6'd0;
    end else if (((icmp_ln270_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        o_fu_88 <= add_ln267_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state10) & (1'b1 == ap_CS_fsm_state10))) begin
        B3mem_addr_read_reg_320 <= m_axi_B3mem_0_RDATA;
        add_ln267_reg_315 <= add_ln267_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (m_axi_W3mem_0_RVALID == 1'b1))) begin
        W3mem_addr_read_reg_353 <= m_axi_W3mem_0_RDATA;
        vec1_load_reg_348 <= vec1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln270_reg_338 <= add_ln270_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln267_reg_311 <= icmp_ln267_fu_247_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        mul9_i_i_reg_363 <= grp_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        zext_ln267_reg_325[5 : 0] <= zext_ln267_fu_258_p1[5 : 0];
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        B3mem_blk_n_AR = m_axi_B3mem_0_ARREADY;
    end else begin
        B3mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln267_reg_311 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        B3mem_blk_n_R = m_axi_B3mem_0_RVALID;
    end else begin
        B3mem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        W3mem_blk_n_AR = m_axi_W3mem_0_ARREADY;
    end else begin
        W3mem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        W3mem_blk_n_R = m_axi_W3mem_0_RVALID;
    end else begin
        W3mem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((m_axi_W3mem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_188_ce = grp_generic_tanh_float_s_fu_175_grp_fu_188_p_ce;
    end else begin
        grp_fu_188_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_188_opcode = grp_generic_tanh_float_s_fu_175_grp_fu_188_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_188_opcode = 2'd0;
    end else begin
        grp_fu_188_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_188_p0 = grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_188_p0 = acc_1_reg_165;
    end else begin
        grp_fu_188_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_188_p1 = grp_generic_tanh_float_s_fu_175_grp_fu_188_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_188_p1 = mul9_i_i_reg_363;
    end else begin
        grp_fu_188_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_193_ce = grp_generic_tanh_float_s_fu_175_grp_fu_193_p_ce;
    end else begin
        grp_fu_193_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_193_p0 = grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_193_p0 = vec1_load_reg_348;
    end else begin
        grp_fu_193_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 
    == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state23))) begin
        grp_fu_193_p1 = grp_generic_tanh_float_s_fu_175_grp_fu_193_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_193_p1 = bitcast_ln272_fu_285_p1;
    end else begin
        grp_fu_193_p1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_B3mem_0_ARVALID = 1'b1;
    end else begin
        m_axi_B3mem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_B3mem_0_RREADY = 1'b1;
    end else begin
        m_axi_B3mem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_W3mem_0_ARVALID = 1'b1;
    end else begin
        m_axi_W3mem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (m_axi_W3mem_0_RVALID == 1'b1))) begin
        m_axi_W3mem_0_RREADY = 1'b1;
    end else begin
        m_axi_W3mem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        vec1_ce0_local = 1'b1;
    end else begin
        vec1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        vec2_ce0_local = 1'b1;
    end else begin
        vec2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        vec2_we0_local = 1'b1;
    end else begin
        vec2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_io) | (1'b1 == ap_block_state1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state10) & (icmp_ln267_reg_311 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln270_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (m_axi_W3mem_0_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_261_p1 = B3mem_addr_read_reg_320;

assign add_ln267_fu_253_p2 = (o_fu_88 + 6'd1);

assign add_ln270_fu_270_p2 = (i_reg_154 + 17'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state23 = ap_NS_fsm[32'd22];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state10 = ((icmp_ln267_reg_311 == 1'd0) & (m_axi_B3mem_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state1_io = ((m_axi_B3mem_0_ARREADY == 1'b0) | (m_axi_W3mem_0_ARREADY == 1'b0));
end

assign bitcast_ln272_fu_285_p1 = W3mem_addr_read_reg_353;

assign grp_generic_tanh_float_s_fu_175_ap_start = grp_generic_tanh_float_s_fu_175_ap_start_reg;

assign icmp_ln267_fu_247_p2 = ((o_fu_88 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln270_fu_264_p2 = ((i_reg_154 == 17'd72384) ? 1'b1 : 1'b0);

assign m_axi_B3mem_0_ARADDR = sext_ln267_1_fu_228_p1;

assign m_axi_B3mem_0_ARBURST = 2'd0;

assign m_axi_B3mem_0_ARCACHE = 4'd0;

assign m_axi_B3mem_0_ARID = 1'd0;

assign m_axi_B3mem_0_ARLEN = 64'd32;

assign m_axi_B3mem_0_ARLOCK = 2'd0;

assign m_axi_B3mem_0_ARPROT = 3'd0;

assign m_axi_B3mem_0_ARQOS = 4'd0;

assign m_axi_B3mem_0_ARREGION = 4'd0;

assign m_axi_B3mem_0_ARSIZE = 3'd0;

assign m_axi_B3mem_0_ARUSER = 1'd0;

assign m_axi_B3mem_0_AWADDR = 64'd0;

assign m_axi_B3mem_0_AWBURST = 2'd0;

assign m_axi_B3mem_0_AWCACHE = 4'd0;

assign m_axi_B3mem_0_AWID = 1'd0;

assign m_axi_B3mem_0_AWLEN = 32'd0;

assign m_axi_B3mem_0_AWLOCK = 2'd0;

assign m_axi_B3mem_0_AWPROT = 3'd0;

assign m_axi_B3mem_0_AWQOS = 4'd0;

assign m_axi_B3mem_0_AWREGION = 4'd0;

assign m_axi_B3mem_0_AWSIZE = 3'd0;

assign m_axi_B3mem_0_AWUSER = 1'd0;

assign m_axi_B3mem_0_AWVALID = 1'b0;

assign m_axi_B3mem_0_BREADY = 1'b0;

assign m_axi_B3mem_0_WDATA = 32'd0;

assign m_axi_B3mem_0_WID = 1'd0;

assign m_axi_B3mem_0_WLAST = 1'b0;

assign m_axi_B3mem_0_WSTRB = 4'd0;

assign m_axi_B3mem_0_WUSER = 1'd0;

assign m_axi_B3mem_0_WVALID = 1'b0;

assign m_axi_W3mem_0_ARADDR = sext_ln267_fu_207_p1;

assign m_axi_W3mem_0_ARBURST = 2'd0;

assign m_axi_W3mem_0_ARCACHE = 4'd0;

assign m_axi_W3mem_0_ARID = 1'd0;

assign m_axi_W3mem_0_ARLEN = 64'd2316288;

assign m_axi_W3mem_0_ARLOCK = 2'd0;

assign m_axi_W3mem_0_ARPROT = 3'd0;

assign m_axi_W3mem_0_ARQOS = 4'd0;

assign m_axi_W3mem_0_ARREGION = 4'd0;

assign m_axi_W3mem_0_ARSIZE = 3'd0;

assign m_axi_W3mem_0_ARUSER = 1'd0;

assign m_axi_W3mem_0_AWADDR = 64'd0;

assign m_axi_W3mem_0_AWBURST = 2'd0;

assign m_axi_W3mem_0_AWCACHE = 4'd0;

assign m_axi_W3mem_0_AWID = 1'd0;

assign m_axi_W3mem_0_AWLEN = 32'd0;

assign m_axi_W3mem_0_AWLOCK = 2'd0;

assign m_axi_W3mem_0_AWPROT = 3'd0;

assign m_axi_W3mem_0_AWQOS = 4'd0;

assign m_axi_W3mem_0_AWREGION = 4'd0;

assign m_axi_W3mem_0_AWSIZE = 3'd0;

assign m_axi_W3mem_0_AWUSER = 1'd0;

assign m_axi_W3mem_0_AWVALID = 1'b0;

assign m_axi_W3mem_0_BREADY = 1'b0;

assign m_axi_W3mem_0_WDATA = 32'd0;

assign m_axi_W3mem_0_WID = 1'd0;

assign m_axi_W3mem_0_WLAST = 1'b0;

assign m_axi_W3mem_0_WSTRB = 4'd0;

assign m_axi_W3mem_0_WUSER = 1'd0;

assign m_axi_W3mem_0_WVALID = 1'b0;

assign sext_ln267_1_fu_228_p1 = $signed(trunc_ln267_1_fu_218_p4);

assign sext_ln267_fu_207_p1 = $signed(trunc_ln_fu_197_p4);

assign trunc_ln267_1_fu_218_p4 = {{FC1_B[63:2]}};

assign trunc_ln_fu_197_p4 = {{FC1_W[63:2]}};

assign vec1_address0 = zext_ln270_fu_276_p1;

assign vec1_ce0 = vec1_ce0_local;

assign vec2_address0 = zext_ln267_reg_325;

assign vec2_ce0 = vec2_ce0_local;

assign vec2_d0 = grp_generic_tanh_float_s_fu_175_ap_return;

assign vec2_we0 = vec2_we0_local;

assign zext_ln267_fu_258_p1 = o_fu_88;

assign zext_ln270_fu_276_p1 = i_reg_154;

always @ (posedge ap_clk) begin
    zext_ln267_reg_325[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_accel_fc1
